// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// KeyManagerMock implements mm_records.KeyManager
type KeyManagerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcEnsureActive          func() (kp1 *models.KeyVersion, err error)
	funcEnsureActiveOrigin    string
	inspectFuncEnsureActive   func()
	afterEnsureActiveCounter  uint64
	beforeEnsureActiveCounter uint64
	EnsureActiveMock          mKeyManagerMockEnsureActive
}

// NewKeyManagerMock returns a mock for mm_records.KeyManager
func NewKeyManagerMock(t minimock.Tester) *KeyManagerMock {
	m := &KeyManagerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.EnsureActiveMock = mKeyManagerMockEnsureActive{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mKeyManagerMockEnsureActive struct {
	optional           bool
	mock               *KeyManagerMock
	defaultExpectation *KeyManagerMockEnsureActiveExpectation
	expectations       []*KeyManagerMockEnsureActiveExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// KeyManagerMockEnsureActiveExpectation specifies expectation struct of the KeyManager.EnsureActive
type KeyManagerMockEnsureActiveExpectation struct {
	mock *KeyManagerMock

	results      *KeyManagerMockEnsureActiveResults
	returnOrigin string
	Counter      uint64
}

// KeyManagerMockEnsureActiveResults contains results of the KeyManager.EnsureActive
type KeyManagerMockEnsureActiveResults struct {
	kp1 *models.KeyVersion
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmEnsureActive *mKeyManagerMockEnsureActive) Optional() *mKeyManagerMockEnsureActive {
	mmEnsureActive.optional = true
	return mmEnsureActive
}

// Expect sets up expected params for KeyManager.EnsureActive
func (mmEnsureActive *mKeyManagerMockEnsureActive) Expect() *mKeyManagerMockEnsureActive {
	if mmEnsureActive.mock.funcEnsureActive != nil {
		mmEnsureActive.mock.t.Fatalf("KeyManagerMock.EnsureActive mock is already set by Set")
	}

	if mmEnsureActive.defaultExpectation == nil {
		mmEnsureActive.defaultExpectation = &KeyManagerMockEnsureActiveExpectation{}
	}

	return mmEnsureActive
}

// Inspect accepts an inspector function that has same arguments as the KeyManager.EnsureActive
func (mmEnsureActive *mKeyManagerMockEnsureActive) Inspect(f func()) *mKeyManagerMockEnsureActive {
	if mmEnsureActive.mock.inspectFuncEnsureActive != nil {
		mmEnsureActive.mock.t.Fatalf("Inspect function is already set for KeyManagerMock.EnsureActive")
	}

	mmEnsureActive.mock.inspectFuncEnsureActive = f

	return mmEnsureActive
}

// Return sets up results that will be returned by KeyManager.EnsureActive
func (mmEnsureActive *mKeyManagerMockEnsureActive) Return(kp1 *models.KeyVersion, err error) *KeyManagerMock {
	if mmEnsureActive.mock.funcEnsureActive != nil {
		mmEnsureActive.mock.t.Fatalf("KeyManagerMock.EnsureActive mock is already set by Set")
	}

	if mmEnsureActive.defaultExpectation == nil {
		mmEnsureActive.defaultExpectation = &KeyManagerMockEnsureActiveExpectation{mock: mmEnsureActive.mock}
	}
	mmEnsureActive.defaultExpectation.results = &KeyManagerMockEnsureActiveResults{kp1, err}
	mmEnsureActive.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmEnsureActive.mock
}

// Set uses given function f to mock the KeyManager.EnsureActive method
func (mmEnsureActive *mKeyManagerMockEnsureActive) Set(f func() (kp1 *models.KeyVersion, err error)) *KeyManagerMock {
	if mmEnsureActive.defaultExpectation != nil {
		mmEnsureActive.mock.t.Fatalf("Default expectation is already set for the KeyManager.EnsureActive method")
	}

	if len(mmEnsureActive.expectations) > 0 {
		mmEnsureActive.mock.t.Fatalf("Some expectations are already set for the KeyManager.EnsureActive method")
	}

	mmEnsureActive.mock.funcEnsureActive = f
	mmEnsureActive.mock.funcEnsureActiveOrigin = minimock.CallerInfo(1)
	return mmEnsureActive.mock
}

// Times sets number of times KeyManager.EnsureActive should be invoked
func (mmEnsureActive *mKeyManagerMockEnsureActive) Times(n uint64) *mKeyManagerMockEnsureActive {
	if n == 0 {
		mmEnsureActive.mock.t.Fatalf("Times of KeyManagerMock.EnsureActive mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmEnsureActive.expectedInvocations, n)
	mmEnsureActive.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmEnsureActive
}

func (mmEnsureActive *mKeyManagerMockEnsureActive) invocationsDone() bool {
	if len(mmEnsureActive.expectations) == 0 && mmEnsureActive.defaultExpectation == nil && mmEnsureActive.mock.funcEnsureActive == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmEnsureActive.mock.afterEnsureActiveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmEnsureActive.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// EnsureActive implements mm_records.KeyManager
func (mmEnsureActive *KeyManagerMock) EnsureActive() (kp1 *models.KeyVersion, err error) {
	mm_atomic.AddUint64(&mmEnsureActive.beforeEnsureActiveCounter, 1)
	defer mm_atomic.AddUint64(&mmEnsureActive.afterEnsureActiveCounter, 1)

	mmEnsureActive.t.Helper()

	if mmEnsureActive.inspectFuncEnsureActive != nil {
		mmEnsureActive.inspectFuncEnsureActive()
	}

	if mmEnsureActive.EnsureActiveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmEnsureActive.EnsureActiveMock.defaultExpectation.Counter, 1)

		mm_results := mmEnsureActive.EnsureActiveMock.defaultExpectation.results
		if mm_results == nil {
			mmEnsureActive.t.Fatal("No results are set for the KeyManagerMock.EnsureActive")
		}
		return (*mm_results).kp1, (*mm_results).err
	}
	if mmEnsureActive.funcEnsureActive != nil {
		return mmEnsureActive.funcEnsureActive()
	}
	mmEnsureActive.t.Fatalf("Unexpected call to KeyManagerMock.EnsureActive.")
	return
}

// EnsureActiveAfterCounter returns a count of finished KeyManagerMock.EnsureActive invocations
func (mmEnsureActive *KeyManagerMock) EnsureActiveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEnsureActive.afterEnsureActiveCounter)
}

// EnsureActiveBeforeCounter returns a count of KeyManagerMock.EnsureActive invocations
func (mmEnsureActive *KeyManagerMock) EnsureActiveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmEnsureActive.beforeEnsureActiveCounter)
}

// MinimockEnsureActiveDone returns true if the count of the EnsureActive invocations corresponds
// the number of defined expectations
func (m *KeyManagerMock) MinimockEnsureActiveDone() bool {
	if m.EnsureActiveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.EnsureActiveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.EnsureActiveMock.invocationsDone()
}

// MinimockEnsureActiveInspect logs each unmet expectation
func (m *KeyManagerMock) MinimockEnsureActiveInspect() {
	for _, e := range m.EnsureActiveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to KeyManagerMock.EnsureActive")
		}
	}

	afterEnsureActiveCounter := mm_atomic.LoadUint64(&m.afterEnsureActiveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.EnsureActiveMock.defaultExpectation != nil && afterEnsureActiveCounter < 1 {
		m.t.Errorf("Expected call to KeyManagerMock.EnsureActive at\n%s", m.EnsureActiveMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcEnsureActive != nil && afterEnsureActiveCounter < 1 {
		m.t.Errorf("Expected call to KeyManagerMock.EnsureActive at\n%s", m.funcEnsureActiveOrigin)
	}

	if !m.EnsureActiveMock.invocationsDone() && afterEnsureActiveCounter > 0 {
		m.t.Errorf("Expected %d calls to KeyManagerMock.EnsureActive at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.EnsureActiveMock.expectedInvocations), m.EnsureActiveMock.expectedInvocationsOrigin, afterEnsureActiveCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *KeyManagerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockEnsureActiveInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *KeyManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *KeyManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockEnsureActiveDone()
}
