// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// UserServiceMock implements mm_auth_login_v1_post.UserService
type UserServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLogin          func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) (accessToken string, refreshToken string, err error)
	funcLoginOrigin    string
	inspectFuncLogin   func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string)
	afterLoginCounter  uint64
	beforeLoginCounter uint64
	LoginMock          mUserServiceMockLogin
}

// NewUserServiceMock returns a mock for mm_auth_login_v1_post.UserService
func NewUserServiceMock(t minimock.Tester) *UserServiceMock {
	m := &UserServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LoginMock = mUserServiceMockLogin{mock: m}
	m.LoginMock.callArgs = []*UserServiceMockLoginParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserServiceMockLogin struct {
	optional           bool
	mock               *UserServiceMock
	defaultExpectation *UserServiceMockLoginExpectation
	expectations       []*UserServiceMockLoginExpectation

	callArgs []*UserServiceMockLoginParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserServiceMockLoginExpectation specifies expectation struct of the UserService.Login
type UserServiceMockLoginExpectation struct {
	mock               *UserServiceMock
	params             *UserServiceMockLoginParams
	paramPtrs          *UserServiceMockLoginParamPtrs
	expectationOrigins UserServiceMockLoginExpectationOrigins
	results            *UserServiceMockLoginResults
	returnOrigin       string
	Counter            uint64
}

// UserServiceMockLoginParams contains parameters of the UserService.Login
type UserServiceMockLoginParams struct {
	ctx        context.Context
	email      string
	password   string
	deviceID   string
	deviceName string
	clientType string
}

// UserServiceMockLoginParamPtrs contains pointers to parameters of the UserService.Login
type UserServiceMockLoginParamPtrs struct {
	ctx        *context.Context
	email      *string
	password   *string
	deviceID   *string
	deviceName *string
	clientType *string
}

// UserServiceMockLoginResults contains results of the UserService.Login
type UserServiceMockLoginResults struct {
	accessToken  string
	refreshToken string
	err          error
}

// UserServiceMockLoginOrigins contains origins of expectations of the UserService.Login
type UserServiceMockLoginExpectationOrigins struct {
	origin           string
	originCtx        string
	originEmail      string
	originPassword   string
	originDeviceID   string
	originDeviceName string
	originClientType string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLogin *mUserServiceMockLogin) Optional() *mUserServiceMockLogin {
	mmLogin.optional = true
	return mmLogin
}

// Expect sets up expected params for UserService.Login
func (mmLogin *mUserServiceMockLogin) Expect(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.paramPtrs != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by ExpectParams functions")
	}

	mmLogin.defaultExpectation.params = &UserServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType}
	mmLogin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLogin.expectations {
		if minimock.Equal(e.params, mmLogin.defaultExpectation.params) {
			mmLogin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLogin.defaultExpectation.params)
		}
	}

	return mmLogin
}

// ExpectCtxParam1 sets up expected param ctx for UserService.Login
func (mmLogin *mUserServiceMockLogin) ExpectCtxParam1(ctx context.Context) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UserServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.ctx = &ctx
	mmLogin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectEmailParam2 sets up expected param email for UserService.Login
func (mmLogin *mUserServiceMockLogin) ExpectEmailParam2(email string) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UserServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.email = &email
	mmLogin.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectPasswordParam3 sets up expected param password for UserService.Login
func (mmLogin *mUserServiceMockLogin) ExpectPasswordParam3(password string) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UserServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.password = &password
	mmLogin.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectDeviceIDParam4 sets up expected param deviceID for UserService.Login
func (mmLogin *mUserServiceMockLogin) ExpectDeviceIDParam4(deviceID string) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UserServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.deviceID = &deviceID
	mmLogin.defaultExpectation.expectationOrigins.originDeviceID = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectDeviceNameParam5 sets up expected param deviceName for UserService.Login
func (mmLogin *mUserServiceMockLogin) ExpectDeviceNameParam5(deviceName string) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UserServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.deviceName = &deviceName
	mmLogin.defaultExpectation.expectationOrigins.originDeviceName = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectClientTypeParam6 sets up expected param clientType for UserService.Login
func (mmLogin *mUserServiceMockLogin) ExpectClientTypeParam6(clientType string) *mUserServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &UserServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.clientType = &clientType
	mmLogin.defaultExpectation.expectationOrigins.originClientType = minimock.CallerInfo(1)

	return mmLogin
}

// Inspect accepts an inspector function that has same arguments as the UserService.Login
func (mmLogin *mUserServiceMockLogin) Inspect(f func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string)) *mUserServiceMockLogin {
	if mmLogin.mock.inspectFuncLogin != nil {
		mmLogin.mock.t.Fatalf("Inspect function is already set for UserServiceMock.Login")
	}

	mmLogin.mock.inspectFuncLogin = f

	return mmLogin
}

// Return sets up results that will be returned by UserService.Login
func (mmLogin *mUserServiceMockLogin) Return(accessToken string, refreshToken string, err error) *UserServiceMock {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &UserServiceMockLoginExpectation{mock: mmLogin.mock}
	}
	mmLogin.defaultExpectation.results = &UserServiceMockLoginResults{accessToken, refreshToken, err}
	mmLogin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLogin.mock
}

// Set uses given function f to mock the UserService.Login method
func (mmLogin *mUserServiceMockLogin) Set(f func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) (accessToken string, refreshToken string, err error)) *UserServiceMock {
	if mmLogin.defaultExpectation != nil {
		mmLogin.mock.t.Fatalf("Default expectation is already set for the UserService.Login method")
	}

	if len(mmLogin.expectations) > 0 {
		mmLogin.mock.t.Fatalf("Some expectations are already set for the UserService.Login method")
	}

	mmLogin.mock.funcLogin = f
	mmLogin.mock.funcLoginOrigin = minimock.CallerInfo(1)
	return mmLogin.mock
}

// When sets expectation for the UserService.Login which will trigger the result defined by the following
// Then helper
func (mmLogin *mUserServiceMockLogin) When(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) *UserServiceMockLoginExpectation {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("UserServiceMock.Login mock is already set by Set")
	}

	expectation := &UserServiceMockLoginExpectation{
		mock:               mmLogin.mock,
		params:             &UserServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType},
		expectationOrigins: UserServiceMockLoginExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLogin.expectations = append(mmLogin.expectations, expectation)
	return expectation
}

// Then sets up UserService.Login return parameters for the expectation previously defined by the When method
func (e *UserServiceMockLoginExpectation) Then(accessToken string, refreshToken string, err error) *UserServiceMock {
	e.results = &UserServiceMockLoginResults{accessToken, refreshToken, err}
	return e.mock
}

// Times sets number of times UserService.Login should be invoked
func (mmLogin *mUserServiceMockLogin) Times(n uint64) *mUserServiceMockLogin {
	if n == 0 {
		mmLogin.mock.t.Fatalf("Times of UserServiceMock.Login mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLogin.expectedInvocations, n)
	mmLogin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLogin
}

func (mmLogin *mUserServiceMockLogin) invocationsDone() bool {
	if len(mmLogin.expectations) == 0 && mmLogin.defaultExpectation == nil && mmLogin.mock.funcLogin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLogin.mock.afterLoginCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLogin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Login implements mm_auth_login_v1_post.UserService
func (mmLogin *UserServiceMock) Login(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) (accessToken string, refreshToken string, err error) {
	mm_atomic.AddUint64(&mmLogin.beforeLoginCounter, 1)
	defer mm_atomic.AddUint64(&mmLogin.afterLoginCounter, 1)

	mmLogin.t.Helper()

	if mmLogin.inspectFuncLogin != nil {
		mmLogin.inspectFuncLogin(ctx, email, password, deviceID, deviceName, clientType)
	}

	mm_params := UserServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType}

	// Record call args
	mmLogin.LoginMock.mutex.Lock()
	mmLogin.LoginMock.callArgs = append(mmLogin.LoginMock.callArgs, &mm_params)
	mmLogin.LoginMock.mutex.Unlock()

	for _, e := range mmLogin.LoginMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.accessToken, e.results.refreshToken, e.results.err
		}
	}

	if mmLogin.LoginMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLogin.LoginMock.defaultExpectation.Counter, 1)
		mm_want := mmLogin.LoginMock.defaultExpectation.params
		mm_want_ptrs := mmLogin.LoginMock.defaultExpectation.paramPtrs

		mm_got := UserServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

			if mm_want_ptrs.deviceID != nil && !minimock.Equal(*mm_want_ptrs.deviceID, mm_got.deviceID) {
				mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameter deviceID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originDeviceID, *mm_want_ptrs.deviceID, mm_got.deviceID, minimock.Diff(*mm_want_ptrs.deviceID, mm_got.deviceID))
			}

			if mm_want_ptrs.deviceName != nil && !minimock.Equal(*mm_want_ptrs.deviceName, mm_got.deviceName) {
				mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameter deviceName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originDeviceName, *mm_want_ptrs.deviceName, mm_got.deviceName, minimock.Diff(*mm_want_ptrs.deviceName, mm_got.deviceName))
			}

			if mm_want_ptrs.clientType != nil && !minimock.Equal(*mm_want_ptrs.clientType, mm_got.clientType) {
				mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameter clientType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originClientType, *mm_want_ptrs.clientType, mm_got.clientType, minimock.Diff(*mm_want_ptrs.clientType, mm_got.clientType))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLogin.t.Errorf("UserServiceMock.Login got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLogin.LoginMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLogin.LoginMock.defaultExpectation.results
		if mm_results == nil {
			mmLogin.t.Fatal("No results are set for the UserServiceMock.Login")
		}
		return (*mm_results).accessToken, (*mm_results).refreshToken, (*mm_results).err
	}
	if mmLogin.funcLogin != nil {
		return mmLogin.funcLogin(ctx, email, password, deviceID, deviceName, clientType)
	}
	mmLogin.t.Fatalf("Unexpected call to UserServiceMock.Login. %v %v %v %v %v %v", ctx, email, password, deviceID, deviceName, clientType)
	return
}

// LoginAfterCounter returns a count of finished UserServiceMock.Login invocations
func (mmLogin *UserServiceMock) LoginAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogin.afterLoginCounter)
}

// LoginBeforeCounter returns a count of UserServiceMock.Login invocations
func (mmLogin *UserServiceMock) LoginBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogin.beforeLoginCounter)
}

// Calls returns a list of arguments used in each call to UserServiceMock.Login.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLogin *mUserServiceMockLogin) Calls() []*UserServiceMockLoginParams {
	mmLogin.mutex.RLock()

	argCopy := make([]*UserServiceMockLoginParams, len(mmLogin.callArgs))
	copy(argCopy, mmLogin.callArgs)

	mmLogin.mutex.RUnlock()

	return argCopy
}

// MinimockLoginDone returns true if the count of the Login invocations corresponds
// the number of defined expectations
func (m *UserServiceMock) MinimockLoginDone() bool {
	if m.LoginMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LoginMock.invocationsDone()
}

// MinimockLoginInspect logs each unmet expectation
func (m *UserServiceMock) MinimockLoginInspect() {
	for _, e := range m.LoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserServiceMock.Login at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLoginCounter := mm_atomic.LoadUint64(&m.afterLoginCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LoginMock.defaultExpectation != nil && afterLoginCounter < 1 {
		if m.LoginMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserServiceMock.Login at\n%s", m.LoginMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserServiceMock.Login at\n%s with params: %#v", m.LoginMock.defaultExpectation.expectationOrigins.origin, *m.LoginMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLogin != nil && afterLoginCounter < 1 {
		m.t.Errorf("Expected call to UserServiceMock.Login at\n%s", m.funcLoginOrigin)
	}

	if !m.LoginMock.invocationsDone() && afterLoginCounter > 0 {
		m.t.Errorf("Expected %d calls to UserServiceMock.Login at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LoginMock.expectedInvocations), m.LoginMock.expectedInvocationsOrigin, afterLoginCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLoginInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLoginDone()
}
