// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuthServiceMock implements mm_app.AuthService
type AuthServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLogin          func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) (s1 string, s2 string, err error)
	funcLoginOrigin    string
	inspectFuncLogin   func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string)
	afterLoginCounter  uint64
	beforeLoginCounter uint64
	LoginMock          mAuthServiceMockLogin

	funcLogout          func(ctx context.Context, accessToken string) (err error)
	funcLogoutOrigin    string
	inspectFuncLogout   func(ctx context.Context, accessToken string)
	afterLogoutCounter  uint64
	beforeLogoutCounter uint64
	LogoutMock          mAuthServiceMockLogout

	funcRefresh          func(ctx context.Context, refreshToken string) (s1 string, s2 string, err error)
	funcRefreshOrigin    string
	inspectFuncRefresh   func(ctx context.Context, refreshToken string)
	afterRefreshCounter  uint64
	beforeRefreshCounter uint64
	RefreshMock          mAuthServiceMockRefresh

	funcRegister          func(ctx context.Context, email string, password string) (i1 int64, err error)
	funcRegisterOrigin    string
	inspectFuncRegister   func(ctx context.Context, email string, password string)
	afterRegisterCounter  uint64
	beforeRegisterCounter uint64
	RegisterMock          mAuthServiceMockRegister

	funcValidateSession          func(token string) (i1 int64, err error)
	funcValidateSessionOrigin    string
	inspectFuncValidateSession   func(token string)
	afterValidateSessionCounter  uint64
	beforeValidateSessionCounter uint64
	ValidateSessionMock          mAuthServiceMockValidateSession

	funcValidateToken          func(token string) (i1 int64, err error)
	funcValidateTokenOrigin    string
	inspectFuncValidateToken   func(token string)
	afterValidateTokenCounter  uint64
	beforeValidateTokenCounter uint64
	ValidateTokenMock          mAuthServiceMockValidateToken
}

// NewAuthServiceMock returns a mock for mm_app.AuthService
func NewAuthServiceMock(t minimock.Tester) *AuthServiceMock {
	m := &AuthServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LoginMock = mAuthServiceMockLogin{mock: m}
	m.LoginMock.callArgs = []*AuthServiceMockLoginParams{}

	m.LogoutMock = mAuthServiceMockLogout{mock: m}
	m.LogoutMock.callArgs = []*AuthServiceMockLogoutParams{}

	m.RefreshMock = mAuthServiceMockRefresh{mock: m}
	m.RefreshMock.callArgs = []*AuthServiceMockRefreshParams{}

	m.RegisterMock = mAuthServiceMockRegister{mock: m}
	m.RegisterMock.callArgs = []*AuthServiceMockRegisterParams{}

	m.ValidateSessionMock = mAuthServiceMockValidateSession{mock: m}
	m.ValidateSessionMock.callArgs = []*AuthServiceMockValidateSessionParams{}

	m.ValidateTokenMock = mAuthServiceMockValidateToken{mock: m}
	m.ValidateTokenMock.callArgs = []*AuthServiceMockValidateTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthServiceMockLogin struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockLoginExpectation
	expectations       []*AuthServiceMockLoginExpectation

	callArgs []*AuthServiceMockLoginParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockLoginExpectation specifies expectation struct of the AuthService.Login
type AuthServiceMockLoginExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockLoginParams
	paramPtrs          *AuthServiceMockLoginParamPtrs
	expectationOrigins AuthServiceMockLoginExpectationOrigins
	results            *AuthServiceMockLoginResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockLoginParams contains parameters of the AuthService.Login
type AuthServiceMockLoginParams struct {
	ctx        context.Context
	email      string
	password   string
	deviceID   string
	deviceName string
	clientType string
}

// AuthServiceMockLoginParamPtrs contains pointers to parameters of the AuthService.Login
type AuthServiceMockLoginParamPtrs struct {
	ctx        *context.Context
	email      *string
	password   *string
	deviceID   *string
	deviceName *string
	clientType *string
}

// AuthServiceMockLoginResults contains results of the AuthService.Login
type AuthServiceMockLoginResults struct {
	s1  string
	s2  string
	err error
}

// AuthServiceMockLoginOrigins contains origins of expectations of the AuthService.Login
type AuthServiceMockLoginExpectationOrigins struct {
	origin           string
	originCtx        string
	originEmail      string
	originPassword   string
	originDeviceID   string
	originDeviceName string
	originClientType string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLogin *mAuthServiceMockLogin) Optional() *mAuthServiceMockLogin {
	mmLogin.optional = true
	return mmLogin
}

// Expect sets up expected params for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) Expect(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.paramPtrs != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by ExpectParams functions")
	}

	mmLogin.defaultExpectation.params = &AuthServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType}
	mmLogin.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLogin.expectations {
		if minimock.Equal(e.params, mmLogin.defaultExpectation.params) {
			mmLogin.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLogin.defaultExpectation.params)
		}
	}

	return mmLogin
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) ExpectCtxParam1(ctx context.Context) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &AuthServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.ctx = &ctx
	mmLogin.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectEmailParam2 sets up expected param email for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) ExpectEmailParam2(email string) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &AuthServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.email = &email
	mmLogin.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectPasswordParam3 sets up expected param password for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) ExpectPasswordParam3(password string) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &AuthServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.password = &password
	mmLogin.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectDeviceIDParam4 sets up expected param deviceID for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) ExpectDeviceIDParam4(deviceID string) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &AuthServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.deviceID = &deviceID
	mmLogin.defaultExpectation.expectationOrigins.originDeviceID = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectDeviceNameParam5 sets up expected param deviceName for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) ExpectDeviceNameParam5(deviceName string) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &AuthServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.deviceName = &deviceName
	mmLogin.defaultExpectation.expectationOrigins.originDeviceName = minimock.CallerInfo(1)

	return mmLogin
}

// ExpectClientTypeParam6 sets up expected param clientType for AuthService.Login
func (mmLogin *mAuthServiceMockLogin) ExpectClientTypeParam6(clientType string) *mAuthServiceMockLogin {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{}
	}

	if mmLogin.defaultExpectation.params != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Expect")
	}

	if mmLogin.defaultExpectation.paramPtrs == nil {
		mmLogin.defaultExpectation.paramPtrs = &AuthServiceMockLoginParamPtrs{}
	}
	mmLogin.defaultExpectation.paramPtrs.clientType = &clientType
	mmLogin.defaultExpectation.expectationOrigins.originClientType = minimock.CallerInfo(1)

	return mmLogin
}

// Inspect accepts an inspector function that has same arguments as the AuthService.Login
func (mmLogin *mAuthServiceMockLogin) Inspect(f func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string)) *mAuthServiceMockLogin {
	if mmLogin.mock.inspectFuncLogin != nil {
		mmLogin.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.Login")
	}

	mmLogin.mock.inspectFuncLogin = f

	return mmLogin
}

// Return sets up results that will be returned by AuthService.Login
func (mmLogin *mAuthServiceMockLogin) Return(s1 string, s2 string, err error) *AuthServiceMock {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	if mmLogin.defaultExpectation == nil {
		mmLogin.defaultExpectation = &AuthServiceMockLoginExpectation{mock: mmLogin.mock}
	}
	mmLogin.defaultExpectation.results = &AuthServiceMockLoginResults{s1, s2, err}
	mmLogin.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLogin.mock
}

// Set uses given function f to mock the AuthService.Login method
func (mmLogin *mAuthServiceMockLogin) Set(f func(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) (s1 string, s2 string, err error)) *AuthServiceMock {
	if mmLogin.defaultExpectation != nil {
		mmLogin.mock.t.Fatalf("Default expectation is already set for the AuthService.Login method")
	}

	if len(mmLogin.expectations) > 0 {
		mmLogin.mock.t.Fatalf("Some expectations are already set for the AuthService.Login method")
	}

	mmLogin.mock.funcLogin = f
	mmLogin.mock.funcLoginOrigin = minimock.CallerInfo(1)
	return mmLogin.mock
}

// When sets expectation for the AuthService.Login which will trigger the result defined by the following
// Then helper
func (mmLogin *mAuthServiceMockLogin) When(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) *AuthServiceMockLoginExpectation {
	if mmLogin.mock.funcLogin != nil {
		mmLogin.mock.t.Fatalf("AuthServiceMock.Login mock is already set by Set")
	}

	expectation := &AuthServiceMockLoginExpectation{
		mock:               mmLogin.mock,
		params:             &AuthServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType},
		expectationOrigins: AuthServiceMockLoginExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLogin.expectations = append(mmLogin.expectations, expectation)
	return expectation
}

// Then sets up AuthService.Login return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockLoginExpectation) Then(s1 string, s2 string, err error) *AuthServiceMock {
	e.results = &AuthServiceMockLoginResults{s1, s2, err}
	return e.mock
}

// Times sets number of times AuthService.Login should be invoked
func (mmLogin *mAuthServiceMockLogin) Times(n uint64) *mAuthServiceMockLogin {
	if n == 0 {
		mmLogin.mock.t.Fatalf("Times of AuthServiceMock.Login mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLogin.expectedInvocations, n)
	mmLogin.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLogin
}

func (mmLogin *mAuthServiceMockLogin) invocationsDone() bool {
	if len(mmLogin.expectations) == 0 && mmLogin.defaultExpectation == nil && mmLogin.mock.funcLogin == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLogin.mock.afterLoginCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLogin.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Login implements mm_app.AuthService
func (mmLogin *AuthServiceMock) Login(ctx context.Context, email string, password string, deviceID string, deviceName string, clientType string) (s1 string, s2 string, err error) {
	mm_atomic.AddUint64(&mmLogin.beforeLoginCounter, 1)
	defer mm_atomic.AddUint64(&mmLogin.afterLoginCounter, 1)

	mmLogin.t.Helper()

	if mmLogin.inspectFuncLogin != nil {
		mmLogin.inspectFuncLogin(ctx, email, password, deviceID, deviceName, clientType)
	}

	mm_params := AuthServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType}

	// Record call args
	mmLogin.LoginMock.mutex.Lock()
	mmLogin.LoginMock.callArgs = append(mmLogin.LoginMock.callArgs, &mm_params)
	mmLogin.LoginMock.mutex.Unlock()

	for _, e := range mmLogin.LoginMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.s2, e.results.err
		}
	}

	if mmLogin.LoginMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLogin.LoginMock.defaultExpectation.Counter, 1)
		mm_want := mmLogin.LoginMock.defaultExpectation.params
		mm_want_ptrs := mmLogin.LoginMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockLoginParams{ctx, email, password, deviceID, deviceName, clientType}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

			if mm_want_ptrs.deviceID != nil && !minimock.Equal(*mm_want_ptrs.deviceID, mm_got.deviceID) {
				mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameter deviceID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originDeviceID, *mm_want_ptrs.deviceID, mm_got.deviceID, minimock.Diff(*mm_want_ptrs.deviceID, mm_got.deviceID))
			}

			if mm_want_ptrs.deviceName != nil && !minimock.Equal(*mm_want_ptrs.deviceName, mm_got.deviceName) {
				mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameter deviceName, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originDeviceName, *mm_want_ptrs.deviceName, mm_got.deviceName, minimock.Diff(*mm_want_ptrs.deviceName, mm_got.deviceName))
			}

			if mm_want_ptrs.clientType != nil && !minimock.Equal(*mm_want_ptrs.clientType, mm_got.clientType) {
				mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameter clientType, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogin.LoginMock.defaultExpectation.expectationOrigins.originClientType, *mm_want_ptrs.clientType, mm_got.clientType, minimock.Diff(*mm_want_ptrs.clientType, mm_got.clientType))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLogin.t.Errorf("AuthServiceMock.Login got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLogin.LoginMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLogin.LoginMock.defaultExpectation.results
		if mm_results == nil {
			mmLogin.t.Fatal("No results are set for the AuthServiceMock.Login")
		}
		return (*mm_results).s1, (*mm_results).s2, (*mm_results).err
	}
	if mmLogin.funcLogin != nil {
		return mmLogin.funcLogin(ctx, email, password, deviceID, deviceName, clientType)
	}
	mmLogin.t.Fatalf("Unexpected call to AuthServiceMock.Login. %v %v %v %v %v %v", ctx, email, password, deviceID, deviceName, clientType)
	return
}

// LoginAfterCounter returns a count of finished AuthServiceMock.Login invocations
func (mmLogin *AuthServiceMock) LoginAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogin.afterLoginCounter)
}

// LoginBeforeCounter returns a count of AuthServiceMock.Login invocations
func (mmLogin *AuthServiceMock) LoginBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogin.beforeLoginCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.Login.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLogin *mAuthServiceMockLogin) Calls() []*AuthServiceMockLoginParams {
	mmLogin.mutex.RLock()

	argCopy := make([]*AuthServiceMockLoginParams, len(mmLogin.callArgs))
	copy(argCopy, mmLogin.callArgs)

	mmLogin.mutex.RUnlock()

	return argCopy
}

// MinimockLoginDone returns true if the count of the Login invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockLoginDone() bool {
	if m.LoginMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LoginMock.invocationsDone()
}

// MinimockLoginInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockLoginInspect() {
	for _, e := range m.LoginMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.Login at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLoginCounter := mm_atomic.LoadUint64(&m.afterLoginCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LoginMock.defaultExpectation != nil && afterLoginCounter < 1 {
		if m.LoginMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.Login at\n%s", m.LoginMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.Login at\n%s with params: %#v", m.LoginMock.defaultExpectation.expectationOrigins.origin, *m.LoginMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLogin != nil && afterLoginCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.Login at\n%s", m.funcLoginOrigin)
	}

	if !m.LoginMock.invocationsDone() && afterLoginCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.Login at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LoginMock.expectedInvocations), m.LoginMock.expectedInvocationsOrigin, afterLoginCounter)
	}
}

type mAuthServiceMockLogout struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockLogoutExpectation
	expectations       []*AuthServiceMockLogoutExpectation

	callArgs []*AuthServiceMockLogoutParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockLogoutExpectation specifies expectation struct of the AuthService.Logout
type AuthServiceMockLogoutExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockLogoutParams
	paramPtrs          *AuthServiceMockLogoutParamPtrs
	expectationOrigins AuthServiceMockLogoutExpectationOrigins
	results            *AuthServiceMockLogoutResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockLogoutParams contains parameters of the AuthService.Logout
type AuthServiceMockLogoutParams struct {
	ctx         context.Context
	accessToken string
}

// AuthServiceMockLogoutParamPtrs contains pointers to parameters of the AuthService.Logout
type AuthServiceMockLogoutParamPtrs struct {
	ctx         *context.Context
	accessToken *string
}

// AuthServiceMockLogoutResults contains results of the AuthService.Logout
type AuthServiceMockLogoutResults struct {
	err error
}

// AuthServiceMockLogoutOrigins contains origins of expectations of the AuthService.Logout
type AuthServiceMockLogoutExpectationOrigins struct {
	origin            string
	originCtx         string
	originAccessToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLogout *mAuthServiceMockLogout) Optional() *mAuthServiceMockLogout {
	mmLogout.optional = true
	return mmLogout
}

// Expect sets up expected params for AuthService.Logout
func (mmLogout *mAuthServiceMockLogout) Expect(ctx context.Context, accessToken string) *mAuthServiceMockLogout {
	if mmLogout.mock.funcLogout != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Set")
	}

	if mmLogout.defaultExpectation == nil {
		mmLogout.defaultExpectation = &AuthServiceMockLogoutExpectation{}
	}

	if mmLogout.defaultExpectation.paramPtrs != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by ExpectParams functions")
	}

	mmLogout.defaultExpectation.params = &AuthServiceMockLogoutParams{ctx, accessToken}
	mmLogout.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLogout.expectations {
		if minimock.Equal(e.params, mmLogout.defaultExpectation.params) {
			mmLogout.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLogout.defaultExpectation.params)
		}
	}

	return mmLogout
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.Logout
func (mmLogout *mAuthServiceMockLogout) ExpectCtxParam1(ctx context.Context) *mAuthServiceMockLogout {
	if mmLogout.mock.funcLogout != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Set")
	}

	if mmLogout.defaultExpectation == nil {
		mmLogout.defaultExpectation = &AuthServiceMockLogoutExpectation{}
	}

	if mmLogout.defaultExpectation.params != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Expect")
	}

	if mmLogout.defaultExpectation.paramPtrs == nil {
		mmLogout.defaultExpectation.paramPtrs = &AuthServiceMockLogoutParamPtrs{}
	}
	mmLogout.defaultExpectation.paramPtrs.ctx = &ctx
	mmLogout.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLogout
}

// ExpectAccessTokenParam2 sets up expected param accessToken for AuthService.Logout
func (mmLogout *mAuthServiceMockLogout) ExpectAccessTokenParam2(accessToken string) *mAuthServiceMockLogout {
	if mmLogout.mock.funcLogout != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Set")
	}

	if mmLogout.defaultExpectation == nil {
		mmLogout.defaultExpectation = &AuthServiceMockLogoutExpectation{}
	}

	if mmLogout.defaultExpectation.params != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Expect")
	}

	if mmLogout.defaultExpectation.paramPtrs == nil {
		mmLogout.defaultExpectation.paramPtrs = &AuthServiceMockLogoutParamPtrs{}
	}
	mmLogout.defaultExpectation.paramPtrs.accessToken = &accessToken
	mmLogout.defaultExpectation.expectationOrigins.originAccessToken = minimock.CallerInfo(1)

	return mmLogout
}

// Inspect accepts an inspector function that has same arguments as the AuthService.Logout
func (mmLogout *mAuthServiceMockLogout) Inspect(f func(ctx context.Context, accessToken string)) *mAuthServiceMockLogout {
	if mmLogout.mock.inspectFuncLogout != nil {
		mmLogout.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.Logout")
	}

	mmLogout.mock.inspectFuncLogout = f

	return mmLogout
}

// Return sets up results that will be returned by AuthService.Logout
func (mmLogout *mAuthServiceMockLogout) Return(err error) *AuthServiceMock {
	if mmLogout.mock.funcLogout != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Set")
	}

	if mmLogout.defaultExpectation == nil {
		mmLogout.defaultExpectation = &AuthServiceMockLogoutExpectation{mock: mmLogout.mock}
	}
	mmLogout.defaultExpectation.results = &AuthServiceMockLogoutResults{err}
	mmLogout.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLogout.mock
}

// Set uses given function f to mock the AuthService.Logout method
func (mmLogout *mAuthServiceMockLogout) Set(f func(ctx context.Context, accessToken string) (err error)) *AuthServiceMock {
	if mmLogout.defaultExpectation != nil {
		mmLogout.mock.t.Fatalf("Default expectation is already set for the AuthService.Logout method")
	}

	if len(mmLogout.expectations) > 0 {
		mmLogout.mock.t.Fatalf("Some expectations are already set for the AuthService.Logout method")
	}

	mmLogout.mock.funcLogout = f
	mmLogout.mock.funcLogoutOrigin = minimock.CallerInfo(1)
	return mmLogout.mock
}

// When sets expectation for the AuthService.Logout which will trigger the result defined by the following
// Then helper
func (mmLogout *mAuthServiceMockLogout) When(ctx context.Context, accessToken string) *AuthServiceMockLogoutExpectation {
	if mmLogout.mock.funcLogout != nil {
		mmLogout.mock.t.Fatalf("AuthServiceMock.Logout mock is already set by Set")
	}

	expectation := &AuthServiceMockLogoutExpectation{
		mock:               mmLogout.mock,
		params:             &AuthServiceMockLogoutParams{ctx, accessToken},
		expectationOrigins: AuthServiceMockLogoutExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLogout.expectations = append(mmLogout.expectations, expectation)
	return expectation
}

// Then sets up AuthService.Logout return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockLogoutExpectation) Then(err error) *AuthServiceMock {
	e.results = &AuthServiceMockLogoutResults{err}
	return e.mock
}

// Times sets number of times AuthService.Logout should be invoked
func (mmLogout *mAuthServiceMockLogout) Times(n uint64) *mAuthServiceMockLogout {
	if n == 0 {
		mmLogout.mock.t.Fatalf("Times of AuthServiceMock.Logout mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLogout.expectedInvocations, n)
	mmLogout.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLogout
}

func (mmLogout *mAuthServiceMockLogout) invocationsDone() bool {
	if len(mmLogout.expectations) == 0 && mmLogout.defaultExpectation == nil && mmLogout.mock.funcLogout == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLogout.mock.afterLogoutCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLogout.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Logout implements mm_app.AuthService
func (mmLogout *AuthServiceMock) Logout(ctx context.Context, accessToken string) (err error) {
	mm_atomic.AddUint64(&mmLogout.beforeLogoutCounter, 1)
	defer mm_atomic.AddUint64(&mmLogout.afterLogoutCounter, 1)

	mmLogout.t.Helper()

	if mmLogout.inspectFuncLogout != nil {
		mmLogout.inspectFuncLogout(ctx, accessToken)
	}

	mm_params := AuthServiceMockLogoutParams{ctx, accessToken}

	// Record call args
	mmLogout.LogoutMock.mutex.Lock()
	mmLogout.LogoutMock.callArgs = append(mmLogout.LogoutMock.callArgs, &mm_params)
	mmLogout.LogoutMock.mutex.Unlock()

	for _, e := range mmLogout.LogoutMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmLogout.LogoutMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLogout.LogoutMock.defaultExpectation.Counter, 1)
		mm_want := mmLogout.LogoutMock.defaultExpectation.params
		mm_want_ptrs := mmLogout.LogoutMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockLogoutParams{ctx, accessToken}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLogout.t.Errorf("AuthServiceMock.Logout got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogout.LogoutMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.accessToken != nil && !minimock.Equal(*mm_want_ptrs.accessToken, mm_got.accessToken) {
				mmLogout.t.Errorf("AuthServiceMock.Logout got unexpected parameter accessToken, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLogout.LogoutMock.defaultExpectation.expectationOrigins.originAccessToken, *mm_want_ptrs.accessToken, mm_got.accessToken, minimock.Diff(*mm_want_ptrs.accessToken, mm_got.accessToken))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLogout.t.Errorf("AuthServiceMock.Logout got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLogout.LogoutMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLogout.LogoutMock.defaultExpectation.results
		if mm_results == nil {
			mmLogout.t.Fatal("No results are set for the AuthServiceMock.Logout")
		}
		return (*mm_results).err
	}
	if mmLogout.funcLogout != nil {
		return mmLogout.funcLogout(ctx, accessToken)
	}
	mmLogout.t.Fatalf("Unexpected call to AuthServiceMock.Logout. %v %v", ctx, accessToken)
	return
}

// LogoutAfterCounter returns a count of finished AuthServiceMock.Logout invocations
func (mmLogout *AuthServiceMock) LogoutAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogout.afterLogoutCounter)
}

// LogoutBeforeCounter returns a count of AuthServiceMock.Logout invocations
func (mmLogout *AuthServiceMock) LogoutBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLogout.beforeLogoutCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.Logout.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLogout *mAuthServiceMockLogout) Calls() []*AuthServiceMockLogoutParams {
	mmLogout.mutex.RLock()

	argCopy := make([]*AuthServiceMockLogoutParams, len(mmLogout.callArgs))
	copy(argCopy, mmLogout.callArgs)

	mmLogout.mutex.RUnlock()

	return argCopy
}

// MinimockLogoutDone returns true if the count of the Logout invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockLogoutDone() bool {
	if m.LogoutMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LogoutMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LogoutMock.invocationsDone()
}

// MinimockLogoutInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockLogoutInspect() {
	for _, e := range m.LogoutMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.Logout at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLogoutCounter := mm_atomic.LoadUint64(&m.afterLogoutCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LogoutMock.defaultExpectation != nil && afterLogoutCounter < 1 {
		if m.LogoutMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.Logout at\n%s", m.LogoutMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.Logout at\n%s with params: %#v", m.LogoutMock.defaultExpectation.expectationOrigins.origin, *m.LogoutMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLogout != nil && afterLogoutCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.Logout at\n%s", m.funcLogoutOrigin)
	}

	if !m.LogoutMock.invocationsDone() && afterLogoutCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.Logout at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LogoutMock.expectedInvocations), m.LogoutMock.expectedInvocationsOrigin, afterLogoutCounter)
	}
}

type mAuthServiceMockRefresh struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockRefreshExpectation
	expectations       []*AuthServiceMockRefreshExpectation

	callArgs []*AuthServiceMockRefreshParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockRefreshExpectation specifies expectation struct of the AuthService.Refresh
type AuthServiceMockRefreshExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockRefreshParams
	paramPtrs          *AuthServiceMockRefreshParamPtrs
	expectationOrigins AuthServiceMockRefreshExpectationOrigins
	results            *AuthServiceMockRefreshResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockRefreshParams contains parameters of the AuthService.Refresh
type AuthServiceMockRefreshParams struct {
	ctx          context.Context
	refreshToken string
}

// AuthServiceMockRefreshParamPtrs contains pointers to parameters of the AuthService.Refresh
type AuthServiceMockRefreshParamPtrs struct {
	ctx          *context.Context
	refreshToken *string
}

// AuthServiceMockRefreshResults contains results of the AuthService.Refresh
type AuthServiceMockRefreshResults struct {
	s1  string
	s2  string
	err error
}

// AuthServiceMockRefreshOrigins contains origins of expectations of the AuthService.Refresh
type AuthServiceMockRefreshExpectationOrigins struct {
	origin             string
	originCtx          string
	originRefreshToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRefresh *mAuthServiceMockRefresh) Optional() *mAuthServiceMockRefresh {
	mmRefresh.optional = true
	return mmRefresh
}

// Expect sets up expected params for AuthService.Refresh
func (mmRefresh *mAuthServiceMockRefresh) Expect(ctx context.Context, refreshToken string) *mAuthServiceMockRefresh {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &AuthServiceMockRefreshExpectation{}
	}

	if mmRefresh.defaultExpectation.paramPtrs != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by ExpectParams functions")
	}

	mmRefresh.defaultExpectation.params = &AuthServiceMockRefreshParams{ctx, refreshToken}
	mmRefresh.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRefresh.expectations {
		if minimock.Equal(e.params, mmRefresh.defaultExpectation.params) {
			mmRefresh.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRefresh.defaultExpectation.params)
		}
	}

	return mmRefresh
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.Refresh
func (mmRefresh *mAuthServiceMockRefresh) ExpectCtxParam1(ctx context.Context) *mAuthServiceMockRefresh {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &AuthServiceMockRefreshExpectation{}
	}

	if mmRefresh.defaultExpectation.params != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Expect")
	}

	if mmRefresh.defaultExpectation.paramPtrs == nil {
		mmRefresh.defaultExpectation.paramPtrs = &AuthServiceMockRefreshParamPtrs{}
	}
	mmRefresh.defaultExpectation.paramPtrs.ctx = &ctx
	mmRefresh.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRefresh
}

// ExpectRefreshTokenParam2 sets up expected param refreshToken for AuthService.Refresh
func (mmRefresh *mAuthServiceMockRefresh) ExpectRefreshTokenParam2(refreshToken string) *mAuthServiceMockRefresh {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &AuthServiceMockRefreshExpectation{}
	}

	if mmRefresh.defaultExpectation.params != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Expect")
	}

	if mmRefresh.defaultExpectation.paramPtrs == nil {
		mmRefresh.defaultExpectation.paramPtrs = &AuthServiceMockRefreshParamPtrs{}
	}
	mmRefresh.defaultExpectation.paramPtrs.refreshToken = &refreshToken
	mmRefresh.defaultExpectation.expectationOrigins.originRefreshToken = minimock.CallerInfo(1)

	return mmRefresh
}

// Inspect accepts an inspector function that has same arguments as the AuthService.Refresh
func (mmRefresh *mAuthServiceMockRefresh) Inspect(f func(ctx context.Context, refreshToken string)) *mAuthServiceMockRefresh {
	if mmRefresh.mock.inspectFuncRefresh != nil {
		mmRefresh.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.Refresh")
	}

	mmRefresh.mock.inspectFuncRefresh = f

	return mmRefresh
}

// Return sets up results that will be returned by AuthService.Refresh
func (mmRefresh *mAuthServiceMockRefresh) Return(s1 string, s2 string, err error) *AuthServiceMock {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Set")
	}

	if mmRefresh.defaultExpectation == nil {
		mmRefresh.defaultExpectation = &AuthServiceMockRefreshExpectation{mock: mmRefresh.mock}
	}
	mmRefresh.defaultExpectation.results = &AuthServiceMockRefreshResults{s1, s2, err}
	mmRefresh.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRefresh.mock
}

// Set uses given function f to mock the AuthService.Refresh method
func (mmRefresh *mAuthServiceMockRefresh) Set(f func(ctx context.Context, refreshToken string) (s1 string, s2 string, err error)) *AuthServiceMock {
	if mmRefresh.defaultExpectation != nil {
		mmRefresh.mock.t.Fatalf("Default expectation is already set for the AuthService.Refresh method")
	}

	if len(mmRefresh.expectations) > 0 {
		mmRefresh.mock.t.Fatalf("Some expectations are already set for the AuthService.Refresh method")
	}

	mmRefresh.mock.funcRefresh = f
	mmRefresh.mock.funcRefreshOrigin = minimock.CallerInfo(1)
	return mmRefresh.mock
}

// When sets expectation for the AuthService.Refresh which will trigger the result defined by the following
// Then helper
func (mmRefresh *mAuthServiceMockRefresh) When(ctx context.Context, refreshToken string) *AuthServiceMockRefreshExpectation {
	if mmRefresh.mock.funcRefresh != nil {
		mmRefresh.mock.t.Fatalf("AuthServiceMock.Refresh mock is already set by Set")
	}

	expectation := &AuthServiceMockRefreshExpectation{
		mock:               mmRefresh.mock,
		params:             &AuthServiceMockRefreshParams{ctx, refreshToken},
		expectationOrigins: AuthServiceMockRefreshExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRefresh.expectations = append(mmRefresh.expectations, expectation)
	return expectation
}

// Then sets up AuthService.Refresh return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockRefreshExpectation) Then(s1 string, s2 string, err error) *AuthServiceMock {
	e.results = &AuthServiceMockRefreshResults{s1, s2, err}
	return e.mock
}

// Times sets number of times AuthService.Refresh should be invoked
func (mmRefresh *mAuthServiceMockRefresh) Times(n uint64) *mAuthServiceMockRefresh {
	if n == 0 {
		mmRefresh.mock.t.Fatalf("Times of AuthServiceMock.Refresh mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRefresh.expectedInvocations, n)
	mmRefresh.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRefresh
}

func (mmRefresh *mAuthServiceMockRefresh) invocationsDone() bool {
	if len(mmRefresh.expectations) == 0 && mmRefresh.defaultExpectation == nil && mmRefresh.mock.funcRefresh == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRefresh.mock.afterRefreshCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRefresh.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Refresh implements mm_app.AuthService
func (mmRefresh *AuthServiceMock) Refresh(ctx context.Context, refreshToken string) (s1 string, s2 string, err error) {
	mm_atomic.AddUint64(&mmRefresh.beforeRefreshCounter, 1)
	defer mm_atomic.AddUint64(&mmRefresh.afterRefreshCounter, 1)

	mmRefresh.t.Helper()

	if mmRefresh.inspectFuncRefresh != nil {
		mmRefresh.inspectFuncRefresh(ctx, refreshToken)
	}

	mm_params := AuthServiceMockRefreshParams{ctx, refreshToken}

	// Record call args
	mmRefresh.RefreshMock.mutex.Lock()
	mmRefresh.RefreshMock.callArgs = append(mmRefresh.RefreshMock.callArgs, &mm_params)
	mmRefresh.RefreshMock.mutex.Unlock()

	for _, e := range mmRefresh.RefreshMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.s2, e.results.err
		}
	}

	if mmRefresh.RefreshMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRefresh.RefreshMock.defaultExpectation.Counter, 1)
		mm_want := mmRefresh.RefreshMock.defaultExpectation.params
		mm_want_ptrs := mmRefresh.RefreshMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockRefreshParams{ctx, refreshToken}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRefresh.t.Errorf("AuthServiceMock.Refresh got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefresh.RefreshMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.refreshToken != nil && !minimock.Equal(*mm_want_ptrs.refreshToken, mm_got.refreshToken) {
				mmRefresh.t.Errorf("AuthServiceMock.Refresh got unexpected parameter refreshToken, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRefresh.RefreshMock.defaultExpectation.expectationOrigins.originRefreshToken, *mm_want_ptrs.refreshToken, mm_got.refreshToken, minimock.Diff(*mm_want_ptrs.refreshToken, mm_got.refreshToken))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRefresh.t.Errorf("AuthServiceMock.Refresh got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRefresh.RefreshMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRefresh.RefreshMock.defaultExpectation.results
		if mm_results == nil {
			mmRefresh.t.Fatal("No results are set for the AuthServiceMock.Refresh")
		}
		return (*mm_results).s1, (*mm_results).s2, (*mm_results).err
	}
	if mmRefresh.funcRefresh != nil {
		return mmRefresh.funcRefresh(ctx, refreshToken)
	}
	mmRefresh.t.Fatalf("Unexpected call to AuthServiceMock.Refresh. %v %v", ctx, refreshToken)
	return
}

// RefreshAfterCounter returns a count of finished AuthServiceMock.Refresh invocations
func (mmRefresh *AuthServiceMock) RefreshAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefresh.afterRefreshCounter)
}

// RefreshBeforeCounter returns a count of AuthServiceMock.Refresh invocations
func (mmRefresh *AuthServiceMock) RefreshBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRefresh.beforeRefreshCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.Refresh.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRefresh *mAuthServiceMockRefresh) Calls() []*AuthServiceMockRefreshParams {
	mmRefresh.mutex.RLock()

	argCopy := make([]*AuthServiceMockRefreshParams, len(mmRefresh.callArgs))
	copy(argCopy, mmRefresh.callArgs)

	mmRefresh.mutex.RUnlock()

	return argCopy
}

// MinimockRefreshDone returns true if the count of the Refresh invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockRefreshDone() bool {
	if m.RefreshMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RefreshMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RefreshMock.invocationsDone()
}

// MinimockRefreshInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockRefreshInspect() {
	for _, e := range m.RefreshMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.Refresh at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRefreshCounter := mm_atomic.LoadUint64(&m.afterRefreshCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RefreshMock.defaultExpectation != nil && afterRefreshCounter < 1 {
		if m.RefreshMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.Refresh at\n%s", m.RefreshMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.Refresh at\n%s with params: %#v", m.RefreshMock.defaultExpectation.expectationOrigins.origin, *m.RefreshMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRefresh != nil && afterRefreshCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.Refresh at\n%s", m.funcRefreshOrigin)
	}

	if !m.RefreshMock.invocationsDone() && afterRefreshCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.Refresh at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RefreshMock.expectedInvocations), m.RefreshMock.expectedInvocationsOrigin, afterRefreshCounter)
	}
}

type mAuthServiceMockRegister struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockRegisterExpectation
	expectations       []*AuthServiceMockRegisterExpectation

	callArgs []*AuthServiceMockRegisterParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockRegisterExpectation specifies expectation struct of the AuthService.Register
type AuthServiceMockRegisterExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockRegisterParams
	paramPtrs          *AuthServiceMockRegisterParamPtrs
	expectationOrigins AuthServiceMockRegisterExpectationOrigins
	results            *AuthServiceMockRegisterResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockRegisterParams contains parameters of the AuthService.Register
type AuthServiceMockRegisterParams struct {
	ctx      context.Context
	email    string
	password string
}

// AuthServiceMockRegisterParamPtrs contains pointers to parameters of the AuthService.Register
type AuthServiceMockRegisterParamPtrs struct {
	ctx      *context.Context
	email    *string
	password *string
}

// AuthServiceMockRegisterResults contains results of the AuthService.Register
type AuthServiceMockRegisterResults struct {
	i1  int64
	err error
}

// AuthServiceMockRegisterOrigins contains origins of expectations of the AuthService.Register
type AuthServiceMockRegisterExpectationOrigins struct {
	origin         string
	originCtx      string
	originEmail    string
	originPassword string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRegister *mAuthServiceMockRegister) Optional() *mAuthServiceMockRegister {
	mmRegister.optional = true
	return mmRegister
}

// Expect sets up expected params for AuthService.Register
func (mmRegister *mAuthServiceMockRegister) Expect(ctx context.Context, email string, password string) *mAuthServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.paramPtrs != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by ExpectParams functions")
	}

	mmRegister.defaultExpectation.params = &AuthServiceMockRegisterParams{ctx, email, password}
	mmRegister.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRegister.expectations {
		if minimock.Equal(e.params, mmRegister.defaultExpectation.params) {
			mmRegister.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRegister.defaultExpectation.params)
		}
	}

	return mmRegister
}

// ExpectCtxParam1 sets up expected param ctx for AuthService.Register
func (mmRegister *mAuthServiceMockRegister) ExpectCtxParam1(ctx context.Context) *mAuthServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthServiceMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.ctx = &ctx
	mmRegister.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectEmailParam2 sets up expected param email for AuthService.Register
func (mmRegister *mAuthServiceMockRegister) ExpectEmailParam2(email string) *mAuthServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthServiceMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.email = &email
	mmRegister.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmRegister
}

// ExpectPasswordParam3 sets up expected param password for AuthService.Register
func (mmRegister *mAuthServiceMockRegister) ExpectPasswordParam3(password string) *mAuthServiceMockRegister {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthServiceMockRegisterExpectation{}
	}

	if mmRegister.defaultExpectation.params != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Expect")
	}

	if mmRegister.defaultExpectation.paramPtrs == nil {
		mmRegister.defaultExpectation.paramPtrs = &AuthServiceMockRegisterParamPtrs{}
	}
	mmRegister.defaultExpectation.paramPtrs.password = &password
	mmRegister.defaultExpectation.expectationOrigins.originPassword = minimock.CallerInfo(1)

	return mmRegister
}

// Inspect accepts an inspector function that has same arguments as the AuthService.Register
func (mmRegister *mAuthServiceMockRegister) Inspect(f func(ctx context.Context, email string, password string)) *mAuthServiceMockRegister {
	if mmRegister.mock.inspectFuncRegister != nil {
		mmRegister.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.Register")
	}

	mmRegister.mock.inspectFuncRegister = f

	return mmRegister
}

// Return sets up results that will be returned by AuthService.Register
func (mmRegister *mAuthServiceMockRegister) Return(i1 int64, err error) *AuthServiceMock {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Set")
	}

	if mmRegister.defaultExpectation == nil {
		mmRegister.defaultExpectation = &AuthServiceMockRegisterExpectation{mock: mmRegister.mock}
	}
	mmRegister.defaultExpectation.results = &AuthServiceMockRegisterResults{i1, err}
	mmRegister.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// Set uses given function f to mock the AuthService.Register method
func (mmRegister *mAuthServiceMockRegister) Set(f func(ctx context.Context, email string, password string) (i1 int64, err error)) *AuthServiceMock {
	if mmRegister.defaultExpectation != nil {
		mmRegister.mock.t.Fatalf("Default expectation is already set for the AuthService.Register method")
	}

	if len(mmRegister.expectations) > 0 {
		mmRegister.mock.t.Fatalf("Some expectations are already set for the AuthService.Register method")
	}

	mmRegister.mock.funcRegister = f
	mmRegister.mock.funcRegisterOrigin = minimock.CallerInfo(1)
	return mmRegister.mock
}

// When sets expectation for the AuthService.Register which will trigger the result defined by the following
// Then helper
func (mmRegister *mAuthServiceMockRegister) When(ctx context.Context, email string, password string) *AuthServiceMockRegisterExpectation {
	if mmRegister.mock.funcRegister != nil {
		mmRegister.mock.t.Fatalf("AuthServiceMock.Register mock is already set by Set")
	}

	expectation := &AuthServiceMockRegisterExpectation{
		mock:               mmRegister.mock,
		params:             &AuthServiceMockRegisterParams{ctx, email, password},
		expectationOrigins: AuthServiceMockRegisterExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRegister.expectations = append(mmRegister.expectations, expectation)
	return expectation
}

// Then sets up AuthService.Register return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockRegisterExpectation) Then(i1 int64, err error) *AuthServiceMock {
	e.results = &AuthServiceMockRegisterResults{i1, err}
	return e.mock
}

// Times sets number of times AuthService.Register should be invoked
func (mmRegister *mAuthServiceMockRegister) Times(n uint64) *mAuthServiceMockRegister {
	if n == 0 {
		mmRegister.mock.t.Fatalf("Times of AuthServiceMock.Register mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRegister.expectedInvocations, n)
	mmRegister.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRegister
}

func (mmRegister *mAuthServiceMockRegister) invocationsDone() bool {
	if len(mmRegister.expectations) == 0 && mmRegister.defaultExpectation == nil && mmRegister.mock.funcRegister == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRegister.mock.afterRegisterCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRegister.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Register implements mm_app.AuthService
func (mmRegister *AuthServiceMock) Register(ctx context.Context, email string, password string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmRegister.beforeRegisterCounter, 1)
	defer mm_atomic.AddUint64(&mmRegister.afterRegisterCounter, 1)

	mmRegister.t.Helper()

	if mmRegister.inspectFuncRegister != nil {
		mmRegister.inspectFuncRegister(ctx, email, password)
	}

	mm_params := AuthServiceMockRegisterParams{ctx, email, password}

	// Record call args
	mmRegister.RegisterMock.mutex.Lock()
	mmRegister.RegisterMock.callArgs = append(mmRegister.RegisterMock.callArgs, &mm_params)
	mmRegister.RegisterMock.mutex.Unlock()

	for _, e := range mmRegister.RegisterMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmRegister.RegisterMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRegister.RegisterMock.defaultExpectation.Counter, 1)
		mm_want := mmRegister.RegisterMock.defaultExpectation.params
		mm_want_ptrs := mmRegister.RegisterMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockRegisterParams{ctx, email, password}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRegister.t.Errorf("AuthServiceMock.Register got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmRegister.t.Errorf("AuthServiceMock.Register got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

			if mm_want_ptrs.password != nil && !minimock.Equal(*mm_want_ptrs.password, mm_got.password) {
				mmRegister.t.Errorf("AuthServiceMock.Register got unexpected parameter password, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRegister.RegisterMock.defaultExpectation.expectationOrigins.originPassword, *mm_want_ptrs.password, mm_got.password, minimock.Diff(*mm_want_ptrs.password, mm_got.password))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRegister.t.Errorf("AuthServiceMock.Register got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRegister.RegisterMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRegister.RegisterMock.defaultExpectation.results
		if mm_results == nil {
			mmRegister.t.Fatal("No results are set for the AuthServiceMock.Register")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmRegister.funcRegister != nil {
		return mmRegister.funcRegister(ctx, email, password)
	}
	mmRegister.t.Fatalf("Unexpected call to AuthServiceMock.Register. %v %v %v", ctx, email, password)
	return
}

// RegisterAfterCounter returns a count of finished AuthServiceMock.Register invocations
func (mmRegister *AuthServiceMock) RegisterAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.afterRegisterCounter)
}

// RegisterBeforeCounter returns a count of AuthServiceMock.Register invocations
func (mmRegister *AuthServiceMock) RegisterBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRegister.beforeRegisterCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.Register.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRegister *mAuthServiceMockRegister) Calls() []*AuthServiceMockRegisterParams {
	mmRegister.mutex.RLock()

	argCopy := make([]*AuthServiceMockRegisterParams, len(mmRegister.callArgs))
	copy(argCopy, mmRegister.callArgs)

	mmRegister.mutex.RUnlock()

	return argCopy
}

// MinimockRegisterDone returns true if the count of the Register invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockRegisterDone() bool {
	if m.RegisterMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RegisterMock.invocationsDone()
}

// MinimockRegisterInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockRegisterInspect() {
	for _, e := range m.RegisterMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.Register at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRegisterCounter := mm_atomic.LoadUint64(&m.afterRegisterCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RegisterMock.defaultExpectation != nil && afterRegisterCounter < 1 {
		if m.RegisterMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.Register at\n%s", m.RegisterMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.Register at\n%s with params: %#v", m.RegisterMock.defaultExpectation.expectationOrigins.origin, *m.RegisterMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRegister != nil && afterRegisterCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.Register at\n%s", m.funcRegisterOrigin)
	}

	if !m.RegisterMock.invocationsDone() && afterRegisterCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.Register at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RegisterMock.expectedInvocations), m.RegisterMock.expectedInvocationsOrigin, afterRegisterCounter)
	}
}

type mAuthServiceMockValidateSession struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockValidateSessionExpectation
	expectations       []*AuthServiceMockValidateSessionExpectation

	callArgs []*AuthServiceMockValidateSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockValidateSessionExpectation specifies expectation struct of the AuthService.ValidateSession
type AuthServiceMockValidateSessionExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockValidateSessionParams
	paramPtrs          *AuthServiceMockValidateSessionParamPtrs
	expectationOrigins AuthServiceMockValidateSessionExpectationOrigins
	results            *AuthServiceMockValidateSessionResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockValidateSessionParams contains parameters of the AuthService.ValidateSession
type AuthServiceMockValidateSessionParams struct {
	token string
}

// AuthServiceMockValidateSessionParamPtrs contains pointers to parameters of the AuthService.ValidateSession
type AuthServiceMockValidateSessionParamPtrs struct {
	token *string
}

// AuthServiceMockValidateSessionResults contains results of the AuthService.ValidateSession
type AuthServiceMockValidateSessionResults struct {
	i1  int64
	err error
}

// AuthServiceMockValidateSessionOrigins contains origins of expectations of the AuthService.ValidateSession
type AuthServiceMockValidateSessionExpectationOrigins struct {
	origin      string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidateSession *mAuthServiceMockValidateSession) Optional() *mAuthServiceMockValidateSession {
	mmValidateSession.optional = true
	return mmValidateSession
}

// Expect sets up expected params for AuthService.ValidateSession
func (mmValidateSession *mAuthServiceMockValidateSession) Expect(token string) *mAuthServiceMockValidateSession {
	if mmValidateSession.mock.funcValidateSession != nil {
		mmValidateSession.mock.t.Fatalf("AuthServiceMock.ValidateSession mock is already set by Set")
	}

	if mmValidateSession.defaultExpectation == nil {
		mmValidateSession.defaultExpectation = &AuthServiceMockValidateSessionExpectation{}
	}

	if mmValidateSession.defaultExpectation.paramPtrs != nil {
		mmValidateSession.mock.t.Fatalf("AuthServiceMock.ValidateSession mock is already set by ExpectParams functions")
	}

	mmValidateSession.defaultExpectation.params = &AuthServiceMockValidateSessionParams{token}
	mmValidateSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValidateSession.expectations {
		if minimock.Equal(e.params, mmValidateSession.defaultExpectation.params) {
			mmValidateSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidateSession.defaultExpectation.params)
		}
	}

	return mmValidateSession
}

// ExpectTokenParam1 sets up expected param token for AuthService.ValidateSession
func (mmValidateSession *mAuthServiceMockValidateSession) ExpectTokenParam1(token string) *mAuthServiceMockValidateSession {
	if mmValidateSession.mock.funcValidateSession != nil {
		mmValidateSession.mock.t.Fatalf("AuthServiceMock.ValidateSession mock is already set by Set")
	}

	if mmValidateSession.defaultExpectation == nil {
		mmValidateSession.defaultExpectation = &AuthServiceMockValidateSessionExpectation{}
	}

	if mmValidateSession.defaultExpectation.params != nil {
		mmValidateSession.mock.t.Fatalf("AuthServiceMock.ValidateSession mock is already set by Expect")
	}

	if mmValidateSession.defaultExpectation.paramPtrs == nil {
		mmValidateSession.defaultExpectation.paramPtrs = &AuthServiceMockValidateSessionParamPtrs{}
	}
	mmValidateSession.defaultExpectation.paramPtrs.token = &token
	mmValidateSession.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmValidateSession
}

// Inspect accepts an inspector function that has same arguments as the AuthService.ValidateSession
func (mmValidateSession *mAuthServiceMockValidateSession) Inspect(f func(token string)) *mAuthServiceMockValidateSession {
	if mmValidateSession.mock.inspectFuncValidateSession != nil {
		mmValidateSession.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.ValidateSession")
	}

	mmValidateSession.mock.inspectFuncValidateSession = f

	return mmValidateSession
}

// Return sets up results that will be returned by AuthService.ValidateSession
func (mmValidateSession *mAuthServiceMockValidateSession) Return(i1 int64, err error) *AuthServiceMock {
	if mmValidateSession.mock.funcValidateSession != nil {
		mmValidateSession.mock.t.Fatalf("AuthServiceMock.ValidateSession mock is already set by Set")
	}

	if mmValidateSession.defaultExpectation == nil {
		mmValidateSession.defaultExpectation = &AuthServiceMockValidateSessionExpectation{mock: mmValidateSession.mock}
	}
	mmValidateSession.defaultExpectation.results = &AuthServiceMockValidateSessionResults{i1, err}
	mmValidateSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValidateSession.mock
}

// Set uses given function f to mock the AuthService.ValidateSession method
func (mmValidateSession *mAuthServiceMockValidateSession) Set(f func(token string) (i1 int64, err error)) *AuthServiceMock {
	if mmValidateSession.defaultExpectation != nil {
		mmValidateSession.mock.t.Fatalf("Default expectation is already set for the AuthService.ValidateSession method")
	}

	if len(mmValidateSession.expectations) > 0 {
		mmValidateSession.mock.t.Fatalf("Some expectations are already set for the AuthService.ValidateSession method")
	}

	mmValidateSession.mock.funcValidateSession = f
	mmValidateSession.mock.funcValidateSessionOrigin = minimock.CallerInfo(1)
	return mmValidateSession.mock
}

// When sets expectation for the AuthService.ValidateSession which will trigger the result defined by the following
// Then helper
func (mmValidateSession *mAuthServiceMockValidateSession) When(token string) *AuthServiceMockValidateSessionExpectation {
	if mmValidateSession.mock.funcValidateSession != nil {
		mmValidateSession.mock.t.Fatalf("AuthServiceMock.ValidateSession mock is already set by Set")
	}

	expectation := &AuthServiceMockValidateSessionExpectation{
		mock:               mmValidateSession.mock,
		params:             &AuthServiceMockValidateSessionParams{token},
		expectationOrigins: AuthServiceMockValidateSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValidateSession.expectations = append(mmValidateSession.expectations, expectation)
	return expectation
}

// Then sets up AuthService.ValidateSession return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockValidateSessionExpectation) Then(i1 int64, err error) *AuthServiceMock {
	e.results = &AuthServiceMockValidateSessionResults{i1, err}
	return e.mock
}

// Times sets number of times AuthService.ValidateSession should be invoked
func (mmValidateSession *mAuthServiceMockValidateSession) Times(n uint64) *mAuthServiceMockValidateSession {
	if n == 0 {
		mmValidateSession.mock.t.Fatalf("Times of AuthServiceMock.ValidateSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidateSession.expectedInvocations, n)
	mmValidateSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValidateSession
}

func (mmValidateSession *mAuthServiceMockValidateSession) invocationsDone() bool {
	if len(mmValidateSession.expectations) == 0 && mmValidateSession.defaultExpectation == nil && mmValidateSession.mock.funcValidateSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidateSession.mock.afterValidateSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidateSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ValidateSession implements mm_app.AuthService
func (mmValidateSession *AuthServiceMock) ValidateSession(token string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmValidateSession.beforeValidateSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmValidateSession.afterValidateSessionCounter, 1)

	mmValidateSession.t.Helper()

	if mmValidateSession.inspectFuncValidateSession != nil {
		mmValidateSession.inspectFuncValidateSession(token)
	}

	mm_params := AuthServiceMockValidateSessionParams{token}

	// Record call args
	mmValidateSession.ValidateSessionMock.mutex.Lock()
	mmValidateSession.ValidateSessionMock.callArgs = append(mmValidateSession.ValidateSessionMock.callArgs, &mm_params)
	mmValidateSession.ValidateSessionMock.mutex.Unlock()

	for _, e := range mmValidateSession.ValidateSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmValidateSession.ValidateSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidateSession.ValidateSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmValidateSession.ValidateSessionMock.defaultExpectation.params
		mm_want_ptrs := mmValidateSession.ValidateSessionMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockValidateSessionParams{token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmValidateSession.t.Errorf("AuthServiceMock.ValidateSession got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateSession.ValidateSessionMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidateSession.t.Errorf("AuthServiceMock.ValidateSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValidateSession.ValidateSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidateSession.ValidateSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmValidateSession.t.Fatal("No results are set for the AuthServiceMock.ValidateSession")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmValidateSession.funcValidateSession != nil {
		return mmValidateSession.funcValidateSession(token)
	}
	mmValidateSession.t.Fatalf("Unexpected call to AuthServiceMock.ValidateSession. %v", token)
	return
}

// ValidateSessionAfterCounter returns a count of finished AuthServiceMock.ValidateSession invocations
func (mmValidateSession *AuthServiceMock) ValidateSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateSession.afterValidateSessionCounter)
}

// ValidateSessionBeforeCounter returns a count of AuthServiceMock.ValidateSession invocations
func (mmValidateSession *AuthServiceMock) ValidateSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateSession.beforeValidateSessionCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.ValidateSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidateSession *mAuthServiceMockValidateSession) Calls() []*AuthServiceMockValidateSessionParams {
	mmValidateSession.mutex.RLock()

	argCopy := make([]*AuthServiceMockValidateSessionParams, len(mmValidateSession.callArgs))
	copy(argCopy, mmValidateSession.callArgs)

	mmValidateSession.mutex.RUnlock()

	return argCopy
}

// MinimockValidateSessionDone returns true if the count of the ValidateSession invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockValidateSessionDone() bool {
	if m.ValidateSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateSessionMock.invocationsDone()
}

// MinimockValidateSessionInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockValidateSessionInspect() {
	for _, e := range m.ValidateSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.ValidateSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidateSessionCounter := mm_atomic.LoadUint64(&m.afterValidateSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateSessionMock.defaultExpectation != nil && afterValidateSessionCounter < 1 {
		if m.ValidateSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.ValidateSession at\n%s", m.ValidateSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.ValidateSession at\n%s with params: %#v", m.ValidateSessionMock.defaultExpectation.expectationOrigins.origin, *m.ValidateSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidateSession != nil && afterValidateSessionCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.ValidateSession at\n%s", m.funcValidateSessionOrigin)
	}

	if !m.ValidateSessionMock.invocationsDone() && afterValidateSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.ValidateSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateSessionMock.expectedInvocations), m.ValidateSessionMock.expectedInvocationsOrigin, afterValidateSessionCounter)
	}
}

type mAuthServiceMockValidateToken struct {
	optional           bool
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockValidateTokenExpectation
	expectations       []*AuthServiceMockValidateTokenExpectation

	callArgs []*AuthServiceMockValidateTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthServiceMockValidateTokenExpectation specifies expectation struct of the AuthService.ValidateToken
type AuthServiceMockValidateTokenExpectation struct {
	mock               *AuthServiceMock
	params             *AuthServiceMockValidateTokenParams
	paramPtrs          *AuthServiceMockValidateTokenParamPtrs
	expectationOrigins AuthServiceMockValidateTokenExpectationOrigins
	results            *AuthServiceMockValidateTokenResults
	returnOrigin       string
	Counter            uint64
}

// AuthServiceMockValidateTokenParams contains parameters of the AuthService.ValidateToken
type AuthServiceMockValidateTokenParams struct {
	token string
}

// AuthServiceMockValidateTokenParamPtrs contains pointers to parameters of the AuthService.ValidateToken
type AuthServiceMockValidateTokenParamPtrs struct {
	token *string
}

// AuthServiceMockValidateTokenResults contains results of the AuthService.ValidateToken
type AuthServiceMockValidateTokenResults struct {
	i1  int64
	err error
}

// AuthServiceMockValidateTokenOrigins contains origins of expectations of the AuthService.ValidateToken
type AuthServiceMockValidateTokenExpectationOrigins struct {
	origin      string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidateToken *mAuthServiceMockValidateToken) Optional() *mAuthServiceMockValidateToken {
	mmValidateToken.optional = true
	return mmValidateToken
}

// Expect sets up expected params for AuthService.ValidateToken
func (mmValidateToken *mAuthServiceMockValidateToken) Expect(token string) *mAuthServiceMockValidateToken {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("AuthServiceMock.ValidateToken mock is already set by Set")
	}

	if mmValidateToken.defaultExpectation == nil {
		mmValidateToken.defaultExpectation = &AuthServiceMockValidateTokenExpectation{}
	}

	if mmValidateToken.defaultExpectation.paramPtrs != nil {
		mmValidateToken.mock.t.Fatalf("AuthServiceMock.ValidateToken mock is already set by ExpectParams functions")
	}

	mmValidateToken.defaultExpectation.params = &AuthServiceMockValidateTokenParams{token}
	mmValidateToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValidateToken.expectations {
		if minimock.Equal(e.params, mmValidateToken.defaultExpectation.params) {
			mmValidateToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidateToken.defaultExpectation.params)
		}
	}

	return mmValidateToken
}

// ExpectTokenParam1 sets up expected param token for AuthService.ValidateToken
func (mmValidateToken *mAuthServiceMockValidateToken) ExpectTokenParam1(token string) *mAuthServiceMockValidateToken {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("AuthServiceMock.ValidateToken mock is already set by Set")
	}

	if mmValidateToken.defaultExpectation == nil {
		mmValidateToken.defaultExpectation = &AuthServiceMockValidateTokenExpectation{}
	}

	if mmValidateToken.defaultExpectation.params != nil {
		mmValidateToken.mock.t.Fatalf("AuthServiceMock.ValidateToken mock is already set by Expect")
	}

	if mmValidateToken.defaultExpectation.paramPtrs == nil {
		mmValidateToken.defaultExpectation.paramPtrs = &AuthServiceMockValidateTokenParamPtrs{}
	}
	mmValidateToken.defaultExpectation.paramPtrs.token = &token
	mmValidateToken.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmValidateToken
}

// Inspect accepts an inspector function that has same arguments as the AuthService.ValidateToken
func (mmValidateToken *mAuthServiceMockValidateToken) Inspect(f func(token string)) *mAuthServiceMockValidateToken {
	if mmValidateToken.mock.inspectFuncValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.ValidateToken")
	}

	mmValidateToken.mock.inspectFuncValidateToken = f

	return mmValidateToken
}

// Return sets up results that will be returned by AuthService.ValidateToken
func (mmValidateToken *mAuthServiceMockValidateToken) Return(i1 int64, err error) *AuthServiceMock {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("AuthServiceMock.ValidateToken mock is already set by Set")
	}

	if mmValidateToken.defaultExpectation == nil {
		mmValidateToken.defaultExpectation = &AuthServiceMockValidateTokenExpectation{mock: mmValidateToken.mock}
	}
	mmValidateToken.defaultExpectation.results = &AuthServiceMockValidateTokenResults{i1, err}
	mmValidateToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValidateToken.mock
}

// Set uses given function f to mock the AuthService.ValidateToken method
func (mmValidateToken *mAuthServiceMockValidateToken) Set(f func(token string) (i1 int64, err error)) *AuthServiceMock {
	if mmValidateToken.defaultExpectation != nil {
		mmValidateToken.mock.t.Fatalf("Default expectation is already set for the AuthService.ValidateToken method")
	}

	if len(mmValidateToken.expectations) > 0 {
		mmValidateToken.mock.t.Fatalf("Some expectations are already set for the AuthService.ValidateToken method")
	}

	mmValidateToken.mock.funcValidateToken = f
	mmValidateToken.mock.funcValidateTokenOrigin = minimock.CallerInfo(1)
	return mmValidateToken.mock
}

// When sets expectation for the AuthService.ValidateToken which will trigger the result defined by the following
// Then helper
func (mmValidateToken *mAuthServiceMockValidateToken) When(token string) *AuthServiceMockValidateTokenExpectation {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("AuthServiceMock.ValidateToken mock is already set by Set")
	}

	expectation := &AuthServiceMockValidateTokenExpectation{
		mock:               mmValidateToken.mock,
		params:             &AuthServiceMockValidateTokenParams{token},
		expectationOrigins: AuthServiceMockValidateTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValidateToken.expectations = append(mmValidateToken.expectations, expectation)
	return expectation
}

// Then sets up AuthService.ValidateToken return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockValidateTokenExpectation) Then(i1 int64, err error) *AuthServiceMock {
	e.results = &AuthServiceMockValidateTokenResults{i1, err}
	return e.mock
}

// Times sets number of times AuthService.ValidateToken should be invoked
func (mmValidateToken *mAuthServiceMockValidateToken) Times(n uint64) *mAuthServiceMockValidateToken {
	if n == 0 {
		mmValidateToken.mock.t.Fatalf("Times of AuthServiceMock.ValidateToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidateToken.expectedInvocations, n)
	mmValidateToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValidateToken
}

func (mmValidateToken *mAuthServiceMockValidateToken) invocationsDone() bool {
	if len(mmValidateToken.expectations) == 0 && mmValidateToken.defaultExpectation == nil && mmValidateToken.mock.funcValidateToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidateToken.mock.afterValidateTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidateToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ValidateToken implements mm_app.AuthService
func (mmValidateToken *AuthServiceMock) ValidateToken(token string) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmValidateToken.beforeValidateTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmValidateToken.afterValidateTokenCounter, 1)

	mmValidateToken.t.Helper()

	if mmValidateToken.inspectFuncValidateToken != nil {
		mmValidateToken.inspectFuncValidateToken(token)
	}

	mm_params := AuthServiceMockValidateTokenParams{token}

	// Record call args
	mmValidateToken.ValidateTokenMock.mutex.Lock()
	mmValidateToken.ValidateTokenMock.callArgs = append(mmValidateToken.ValidateTokenMock.callArgs, &mm_params)
	mmValidateToken.ValidateTokenMock.mutex.Unlock()

	for _, e := range mmValidateToken.ValidateTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmValidateToken.ValidateTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidateToken.ValidateTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmValidateToken.ValidateTokenMock.defaultExpectation.params
		mm_want_ptrs := mmValidateToken.ValidateTokenMock.defaultExpectation.paramPtrs

		mm_got := AuthServiceMockValidateTokenParams{token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmValidateToken.t.Errorf("AuthServiceMock.ValidateToken got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateToken.ValidateTokenMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidateToken.t.Errorf("AuthServiceMock.ValidateToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValidateToken.ValidateTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidateToken.ValidateTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmValidateToken.t.Fatal("No results are set for the AuthServiceMock.ValidateToken")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmValidateToken.funcValidateToken != nil {
		return mmValidateToken.funcValidateToken(token)
	}
	mmValidateToken.t.Fatalf("Unexpected call to AuthServiceMock.ValidateToken. %v", token)
	return
}

// ValidateTokenAfterCounter returns a count of finished AuthServiceMock.ValidateToken invocations
func (mmValidateToken *AuthServiceMock) ValidateTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateToken.afterValidateTokenCounter)
}

// ValidateTokenBeforeCounter returns a count of AuthServiceMock.ValidateToken invocations
func (mmValidateToken *AuthServiceMock) ValidateTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateToken.beforeValidateTokenCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.ValidateToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidateToken *mAuthServiceMockValidateToken) Calls() []*AuthServiceMockValidateTokenParams {
	mmValidateToken.mutex.RLock()

	argCopy := make([]*AuthServiceMockValidateTokenParams, len(mmValidateToken.callArgs))
	copy(argCopy, mmValidateToken.callArgs)

	mmValidateToken.mutex.RUnlock()

	return argCopy
}

// MinimockValidateTokenDone returns true if the count of the ValidateToken invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockValidateTokenDone() bool {
	if m.ValidateTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateTokenMock.invocationsDone()
}

// MinimockValidateTokenInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockValidateTokenInspect() {
	for _, e := range m.ValidateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.ValidateToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidateTokenCounter := mm_atomic.LoadUint64(&m.afterValidateTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateTokenMock.defaultExpectation != nil && afterValidateTokenCounter < 1 {
		if m.ValidateTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthServiceMock.ValidateToken at\n%s", m.ValidateTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.ValidateToken at\n%s with params: %#v", m.ValidateTokenMock.defaultExpectation.expectationOrigins.origin, *m.ValidateTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidateToken != nil && afterValidateTokenCounter < 1 {
		m.t.Errorf("Expected call to AuthServiceMock.ValidateToken at\n%s", m.funcValidateTokenOrigin)
	}

	if !m.ValidateTokenMock.invocationsDone() && afterValidateTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthServiceMock.ValidateToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateTokenMock.expectedInvocations), m.ValidateTokenMock.expectedInvocationsOrigin, afterValidateTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLoginInspect()

			m.MinimockLogoutInspect()

			m.MinimockRefreshInspect()

			m.MinimockRegisterInspect()

			m.MinimockValidateSessionInspect()

			m.MinimockValidateTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLoginDone() &&
		m.MinimockLogoutDone() &&
		m.MinimockRefreshDone() &&
		m.MinimockRegisterDone() &&
		m.MinimockValidateSessionDone() &&
		m.MinimockValidateTokenDone()
}
