// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// SessionRepoMock implements mm_auth.SessionRepo
type SessionRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateSession          func(session *models.Session) (err error)
	funcCreateSessionOrigin    string
	inspectFuncCreateSession   func(session *models.Session)
	afterCreateSessionCounter  uint64
	beforeCreateSessionCounter uint64
	CreateSessionMock          mSessionRepoMockCreateSession

	funcGetSession          func(id int64) (sp1 *models.Session, err error)
	funcGetSessionOrigin    string
	inspectFuncGetSession   func(id int64)
	afterGetSessionCounter  uint64
	beforeGetSessionCounter uint64
	GetSessionMock          mSessionRepoMockGetSession

	funcGetSessionByRefreshToken          func(token string) (sp1 *models.Session, err error)
	funcGetSessionByRefreshTokenOrigin    string
	inspectFuncGetSessionByRefreshToken   func(token string)
	afterGetSessionByRefreshTokenCounter  uint64
	beforeGetSessionByRefreshTokenCounter uint64
	GetSessionByRefreshTokenMock          mSessionRepoMockGetSessionByRefreshToken

	funcRevokeSession          func(id int64) (err error)
	funcRevokeSessionOrigin    string
	inspectFuncRevokeSession   func(id int64)
	afterRevokeSessionCounter  uint64
	beforeRevokeSessionCounter uint64
	RevokeSessionMock          mSessionRepoMockRevokeSession

	funcRevokeSessionsByUser          func(userID int64) (err error)
	funcRevokeSessionsByUserOrigin    string
	inspectFuncRevokeSessionsByUser   func(userID int64)
	afterRevokeSessionsByUserCounter  uint64
	beforeRevokeSessionsByUserCounter uint64
	RevokeSessionsByUserMock          mSessionRepoMockRevokeSessionsByUser

	funcUpdateLastSeenAt          func(id int64) (err error)
	funcUpdateLastSeenAtOrigin    string
	inspectFuncUpdateLastSeenAt   func(id int64)
	afterUpdateLastSeenAtCounter  uint64
	beforeUpdateLastSeenAtCounter uint64
	UpdateLastSeenAtMock          mSessionRepoMockUpdateLastSeenAt
}

// NewSessionRepoMock returns a mock for mm_auth.SessionRepo
func NewSessionRepoMock(t minimock.Tester) *SessionRepoMock {
	m := &SessionRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateSessionMock = mSessionRepoMockCreateSession{mock: m}
	m.CreateSessionMock.callArgs = []*SessionRepoMockCreateSessionParams{}

	m.GetSessionMock = mSessionRepoMockGetSession{mock: m}
	m.GetSessionMock.callArgs = []*SessionRepoMockGetSessionParams{}

	m.GetSessionByRefreshTokenMock = mSessionRepoMockGetSessionByRefreshToken{mock: m}
	m.GetSessionByRefreshTokenMock.callArgs = []*SessionRepoMockGetSessionByRefreshTokenParams{}

	m.RevokeSessionMock = mSessionRepoMockRevokeSession{mock: m}
	m.RevokeSessionMock.callArgs = []*SessionRepoMockRevokeSessionParams{}

	m.RevokeSessionsByUserMock = mSessionRepoMockRevokeSessionsByUser{mock: m}
	m.RevokeSessionsByUserMock.callArgs = []*SessionRepoMockRevokeSessionsByUserParams{}

	m.UpdateLastSeenAtMock = mSessionRepoMockUpdateLastSeenAt{mock: m}
	m.UpdateLastSeenAtMock.callArgs = []*SessionRepoMockUpdateLastSeenAtParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSessionRepoMockCreateSession struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockCreateSessionExpectation
	expectations       []*SessionRepoMockCreateSessionExpectation

	callArgs []*SessionRepoMockCreateSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockCreateSessionExpectation specifies expectation struct of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockCreateSessionParams
	paramPtrs          *SessionRepoMockCreateSessionParamPtrs
	expectationOrigins SessionRepoMockCreateSessionExpectationOrigins
	results            *SessionRepoMockCreateSessionResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockCreateSessionParams contains parameters of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionParams struct {
	session *models.Session
}

// SessionRepoMockCreateSessionParamPtrs contains pointers to parameters of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionParamPtrs struct {
	session **models.Session
}

// SessionRepoMockCreateSessionResults contains results of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionResults struct {
	err error
}

// SessionRepoMockCreateSessionOrigins contains origins of expectations of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionExpectationOrigins struct {
	origin        string
	originSession string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateSession *mSessionRepoMockCreateSession) Optional() *mSessionRepoMockCreateSession {
	mmCreateSession.optional = true
	return mmCreateSession
}

// Expect sets up expected params for SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) Expect(session *models.Session) *mSessionRepoMockCreateSession {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	if mmCreateSession.defaultExpectation == nil {
		mmCreateSession.defaultExpectation = &SessionRepoMockCreateSessionExpectation{}
	}

	if mmCreateSession.defaultExpectation.paramPtrs != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by ExpectParams functions")
	}

	mmCreateSession.defaultExpectation.params = &SessionRepoMockCreateSessionParams{session}
	mmCreateSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateSession.expectations {
		if minimock.Equal(e.params, mmCreateSession.defaultExpectation.params) {
			mmCreateSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateSession.defaultExpectation.params)
		}
	}

	return mmCreateSession
}

// ExpectSessionParam1 sets up expected param session for SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) ExpectSessionParam1(session *models.Session) *mSessionRepoMockCreateSession {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	if mmCreateSession.defaultExpectation == nil {
		mmCreateSession.defaultExpectation = &SessionRepoMockCreateSessionExpectation{}
	}

	if mmCreateSession.defaultExpectation.params != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Expect")
	}

	if mmCreateSession.defaultExpectation.paramPtrs == nil {
		mmCreateSession.defaultExpectation.paramPtrs = &SessionRepoMockCreateSessionParamPtrs{}
	}
	mmCreateSession.defaultExpectation.paramPtrs.session = &session
	mmCreateSession.defaultExpectation.expectationOrigins.originSession = minimock.CallerInfo(1)

	return mmCreateSession
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) Inspect(f func(session *models.Session)) *mSessionRepoMockCreateSession {
	if mmCreateSession.mock.inspectFuncCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.CreateSession")
	}

	mmCreateSession.mock.inspectFuncCreateSession = f

	return mmCreateSession
}

// Return sets up results that will be returned by SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) Return(err error) *SessionRepoMock {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	if mmCreateSession.defaultExpectation == nil {
		mmCreateSession.defaultExpectation = &SessionRepoMockCreateSessionExpectation{mock: mmCreateSession.mock}
	}
	mmCreateSession.defaultExpectation.results = &SessionRepoMockCreateSessionResults{err}
	mmCreateSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateSession.mock
}

// Set uses given function f to mock the SessionRepo.CreateSession method
func (mmCreateSession *mSessionRepoMockCreateSession) Set(f func(session *models.Session) (err error)) *SessionRepoMock {
	if mmCreateSession.defaultExpectation != nil {
		mmCreateSession.mock.t.Fatalf("Default expectation is already set for the SessionRepo.CreateSession method")
	}

	if len(mmCreateSession.expectations) > 0 {
		mmCreateSession.mock.t.Fatalf("Some expectations are already set for the SessionRepo.CreateSession method")
	}

	mmCreateSession.mock.funcCreateSession = f
	mmCreateSession.mock.funcCreateSessionOrigin = minimock.CallerInfo(1)
	return mmCreateSession.mock
}

// When sets expectation for the SessionRepo.CreateSession which will trigger the result defined by the following
// Then helper
func (mmCreateSession *mSessionRepoMockCreateSession) When(session *models.Session) *SessionRepoMockCreateSessionExpectation {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	expectation := &SessionRepoMockCreateSessionExpectation{
		mock:               mmCreateSession.mock,
		params:             &SessionRepoMockCreateSessionParams{session},
		expectationOrigins: SessionRepoMockCreateSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateSession.expectations = append(mmCreateSession.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.CreateSession return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockCreateSessionExpectation) Then(err error) *SessionRepoMock {
	e.results = &SessionRepoMockCreateSessionResults{err}
	return e.mock
}

// Times sets number of times SessionRepo.CreateSession should be invoked
func (mmCreateSession *mSessionRepoMockCreateSession) Times(n uint64) *mSessionRepoMockCreateSession {
	if n == 0 {
		mmCreateSession.mock.t.Fatalf("Times of SessionRepoMock.CreateSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateSession.expectedInvocations, n)
	mmCreateSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateSession
}

func (mmCreateSession *mSessionRepoMockCreateSession) invocationsDone() bool {
	if len(mmCreateSession.expectations) == 0 && mmCreateSession.defaultExpectation == nil && mmCreateSession.mock.funcCreateSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateSession.mock.afterCreateSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateSession implements mm_auth.SessionRepo
func (mmCreateSession *SessionRepoMock) CreateSession(session *models.Session) (err error) {
	mm_atomic.AddUint64(&mmCreateSession.beforeCreateSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateSession.afterCreateSessionCounter, 1)

	mmCreateSession.t.Helper()

	if mmCreateSession.inspectFuncCreateSession != nil {
		mmCreateSession.inspectFuncCreateSession(session)
	}

	mm_params := SessionRepoMockCreateSessionParams{session}

	// Record call args
	mmCreateSession.CreateSessionMock.mutex.Lock()
	mmCreateSession.CreateSessionMock.callArgs = append(mmCreateSession.CreateSessionMock.callArgs, &mm_params)
	mmCreateSession.CreateSessionMock.mutex.Unlock()

	for _, e := range mmCreateSession.CreateSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateSession.CreateSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateSession.CreateSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateSession.CreateSessionMock.defaultExpectation.params
		mm_want_ptrs := mmCreateSession.CreateSessionMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockCreateSessionParams{session}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.session != nil && !minimock.Equal(*mm_want_ptrs.session, mm_got.session) {
				mmCreateSession.t.Errorf("SessionRepoMock.CreateSession got unexpected parameter session, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateSession.CreateSessionMock.defaultExpectation.expectationOrigins.originSession, *mm_want_ptrs.session, mm_got.session, minimock.Diff(*mm_want_ptrs.session, mm_got.session))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateSession.t.Errorf("SessionRepoMock.CreateSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateSession.CreateSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateSession.CreateSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateSession.t.Fatal("No results are set for the SessionRepoMock.CreateSession")
		}
		return (*mm_results).err
	}
	if mmCreateSession.funcCreateSession != nil {
		return mmCreateSession.funcCreateSession(session)
	}
	mmCreateSession.t.Fatalf("Unexpected call to SessionRepoMock.CreateSession. %v", session)
	return
}

// CreateSessionAfterCounter returns a count of finished SessionRepoMock.CreateSession invocations
func (mmCreateSession *SessionRepoMock) CreateSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateSession.afterCreateSessionCounter)
}

// CreateSessionBeforeCounter returns a count of SessionRepoMock.CreateSession invocations
func (mmCreateSession *SessionRepoMock) CreateSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateSession.beforeCreateSessionCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.CreateSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateSession *mSessionRepoMockCreateSession) Calls() []*SessionRepoMockCreateSessionParams {
	mmCreateSession.mutex.RLock()

	argCopy := make([]*SessionRepoMockCreateSessionParams, len(mmCreateSession.callArgs))
	copy(argCopy, mmCreateSession.callArgs)

	mmCreateSession.mutex.RUnlock()

	return argCopy
}

// MinimockCreateSessionDone returns true if the count of the CreateSession invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockCreateSessionDone() bool {
	if m.CreateSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateSessionMock.invocationsDone()
}

// MinimockCreateSessionInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockCreateSessionInspect() {
	for _, e := range m.CreateSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateSessionCounter := mm_atomic.LoadUint64(&m.afterCreateSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateSessionMock.defaultExpectation != nil && afterCreateSessionCounter < 1 {
		if m.CreateSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s", m.CreateSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s with params: %#v", m.CreateSessionMock.defaultExpectation.expectationOrigins.origin, *m.CreateSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateSession != nil && afterCreateSessionCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s", m.funcCreateSessionOrigin)
	}

	if !m.CreateSessionMock.invocationsDone() && afterCreateSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.CreateSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateSessionMock.expectedInvocations), m.CreateSessionMock.expectedInvocationsOrigin, afterCreateSessionCounter)
	}
}

type mSessionRepoMockGetSession struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockGetSessionExpectation
	expectations       []*SessionRepoMockGetSessionExpectation

	callArgs []*SessionRepoMockGetSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockGetSessionExpectation specifies expectation struct of the SessionRepo.GetSession
type SessionRepoMockGetSessionExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockGetSessionParams
	paramPtrs          *SessionRepoMockGetSessionParamPtrs
	expectationOrigins SessionRepoMockGetSessionExpectationOrigins
	results            *SessionRepoMockGetSessionResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockGetSessionParams contains parameters of the SessionRepo.GetSession
type SessionRepoMockGetSessionParams struct {
	id int64
}

// SessionRepoMockGetSessionParamPtrs contains pointers to parameters of the SessionRepo.GetSession
type SessionRepoMockGetSessionParamPtrs struct {
	id *int64
}

// SessionRepoMockGetSessionResults contains results of the SessionRepo.GetSession
type SessionRepoMockGetSessionResults struct {
	sp1 *models.Session
	err error
}

// SessionRepoMockGetSessionOrigins contains origins of expectations of the SessionRepo.GetSession
type SessionRepoMockGetSessionExpectationOrigins struct {
	origin   string
	originId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetSession *mSessionRepoMockGetSession) Optional() *mSessionRepoMockGetSession {
	mmGetSession.optional = true
	return mmGetSession
}

// Expect sets up expected params for SessionRepo.GetSession
func (mmGetSession *mSessionRepoMockGetSession) Expect(id int64) *mSessionRepoMockGetSession {
	if mmGetSession.mock.funcGetSession != nil {
		mmGetSession.mock.t.Fatalf("SessionRepoMock.GetSession mock is already set by Set")
	}

	if mmGetSession.defaultExpectation == nil {
		mmGetSession.defaultExpectation = &SessionRepoMockGetSessionExpectation{}
	}

	if mmGetSession.defaultExpectation.paramPtrs != nil {
		mmGetSession.mock.t.Fatalf("SessionRepoMock.GetSession mock is already set by ExpectParams functions")
	}

	mmGetSession.defaultExpectation.params = &SessionRepoMockGetSessionParams{id}
	mmGetSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetSession.expectations {
		if minimock.Equal(e.params, mmGetSession.defaultExpectation.params) {
			mmGetSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetSession.defaultExpectation.params)
		}
	}

	return mmGetSession
}

// ExpectIdParam1 sets up expected param id for SessionRepo.GetSession
func (mmGetSession *mSessionRepoMockGetSession) ExpectIdParam1(id int64) *mSessionRepoMockGetSession {
	if mmGetSession.mock.funcGetSession != nil {
		mmGetSession.mock.t.Fatalf("SessionRepoMock.GetSession mock is already set by Set")
	}

	if mmGetSession.defaultExpectation == nil {
		mmGetSession.defaultExpectation = &SessionRepoMockGetSessionExpectation{}
	}

	if mmGetSession.defaultExpectation.params != nil {
		mmGetSession.mock.t.Fatalf("SessionRepoMock.GetSession mock is already set by Expect")
	}

	if mmGetSession.defaultExpectation.paramPtrs == nil {
		mmGetSession.defaultExpectation.paramPtrs = &SessionRepoMockGetSessionParamPtrs{}
	}
	mmGetSession.defaultExpectation.paramPtrs.id = &id
	mmGetSession.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetSession
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.GetSession
func (mmGetSession *mSessionRepoMockGetSession) Inspect(f func(id int64)) *mSessionRepoMockGetSession {
	if mmGetSession.mock.inspectFuncGetSession != nil {
		mmGetSession.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.GetSession")
	}

	mmGetSession.mock.inspectFuncGetSession = f

	return mmGetSession
}

// Return sets up results that will be returned by SessionRepo.GetSession
func (mmGetSession *mSessionRepoMockGetSession) Return(sp1 *models.Session, err error) *SessionRepoMock {
	if mmGetSession.mock.funcGetSession != nil {
		mmGetSession.mock.t.Fatalf("SessionRepoMock.GetSession mock is already set by Set")
	}

	if mmGetSession.defaultExpectation == nil {
		mmGetSession.defaultExpectation = &SessionRepoMockGetSessionExpectation{mock: mmGetSession.mock}
	}
	mmGetSession.defaultExpectation.results = &SessionRepoMockGetSessionResults{sp1, err}
	mmGetSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetSession.mock
}

// Set uses given function f to mock the SessionRepo.GetSession method
func (mmGetSession *mSessionRepoMockGetSession) Set(f func(id int64) (sp1 *models.Session, err error)) *SessionRepoMock {
	if mmGetSession.defaultExpectation != nil {
		mmGetSession.mock.t.Fatalf("Default expectation is already set for the SessionRepo.GetSession method")
	}

	if len(mmGetSession.expectations) > 0 {
		mmGetSession.mock.t.Fatalf("Some expectations are already set for the SessionRepo.GetSession method")
	}

	mmGetSession.mock.funcGetSession = f
	mmGetSession.mock.funcGetSessionOrigin = minimock.CallerInfo(1)
	return mmGetSession.mock
}

// When sets expectation for the SessionRepo.GetSession which will trigger the result defined by the following
// Then helper
func (mmGetSession *mSessionRepoMockGetSession) When(id int64) *SessionRepoMockGetSessionExpectation {
	if mmGetSession.mock.funcGetSession != nil {
		mmGetSession.mock.t.Fatalf("SessionRepoMock.GetSession mock is already set by Set")
	}

	expectation := &SessionRepoMockGetSessionExpectation{
		mock:               mmGetSession.mock,
		params:             &SessionRepoMockGetSessionParams{id},
		expectationOrigins: SessionRepoMockGetSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetSession.expectations = append(mmGetSession.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.GetSession return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockGetSessionExpectation) Then(sp1 *models.Session, err error) *SessionRepoMock {
	e.results = &SessionRepoMockGetSessionResults{sp1, err}
	return e.mock
}

// Times sets number of times SessionRepo.GetSession should be invoked
func (mmGetSession *mSessionRepoMockGetSession) Times(n uint64) *mSessionRepoMockGetSession {
	if n == 0 {
		mmGetSession.mock.t.Fatalf("Times of SessionRepoMock.GetSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetSession.expectedInvocations, n)
	mmGetSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetSession
}

func (mmGetSession *mSessionRepoMockGetSession) invocationsDone() bool {
	if len(mmGetSession.expectations) == 0 && mmGetSession.defaultExpectation == nil && mmGetSession.mock.funcGetSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetSession.mock.afterGetSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetSession implements mm_auth.SessionRepo
func (mmGetSession *SessionRepoMock) GetSession(id int64) (sp1 *models.Session, err error) {
	mm_atomic.AddUint64(&mmGetSession.beforeGetSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmGetSession.afterGetSessionCounter, 1)

	mmGetSession.t.Helper()

	if mmGetSession.inspectFuncGetSession != nil {
		mmGetSession.inspectFuncGetSession(id)
	}

	mm_params := SessionRepoMockGetSessionParams{id}

	// Record call args
	mmGetSession.GetSessionMock.mutex.Lock()
	mmGetSession.GetSessionMock.callArgs = append(mmGetSession.GetSessionMock.callArgs, &mm_params)
	mmGetSession.GetSessionMock.mutex.Unlock()

	for _, e := range mmGetSession.GetSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetSession.GetSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetSession.GetSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmGetSession.GetSessionMock.defaultExpectation.params
		mm_want_ptrs := mmGetSession.GetSessionMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockGetSessionParams{id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetSession.t.Errorf("SessionRepoMock.GetSession got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetSession.GetSessionMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetSession.t.Errorf("SessionRepoMock.GetSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetSession.GetSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetSession.GetSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmGetSession.t.Fatal("No results are set for the SessionRepoMock.GetSession")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetSession.funcGetSession != nil {
		return mmGetSession.funcGetSession(id)
	}
	mmGetSession.t.Fatalf("Unexpected call to SessionRepoMock.GetSession. %v", id)
	return
}

// GetSessionAfterCounter returns a count of finished SessionRepoMock.GetSession invocations
func (mmGetSession *SessionRepoMock) GetSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetSession.afterGetSessionCounter)
}

// GetSessionBeforeCounter returns a count of SessionRepoMock.GetSession invocations
func (mmGetSession *SessionRepoMock) GetSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetSession.beforeGetSessionCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.GetSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetSession *mSessionRepoMockGetSession) Calls() []*SessionRepoMockGetSessionParams {
	mmGetSession.mutex.RLock()

	argCopy := make([]*SessionRepoMockGetSessionParams, len(mmGetSession.callArgs))
	copy(argCopy, mmGetSession.callArgs)

	mmGetSession.mutex.RUnlock()

	return argCopy
}

// MinimockGetSessionDone returns true if the count of the GetSession invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockGetSessionDone() bool {
	if m.GetSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetSessionMock.invocationsDone()
}

// MinimockGetSessionInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockGetSessionInspect() {
	for _, e := range m.GetSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.GetSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetSessionCounter := mm_atomic.LoadUint64(&m.afterGetSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetSessionMock.defaultExpectation != nil && afterGetSessionCounter < 1 {
		if m.GetSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.GetSession at\n%s", m.GetSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.GetSession at\n%s with params: %#v", m.GetSessionMock.defaultExpectation.expectationOrigins.origin, *m.GetSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetSession != nil && afterGetSessionCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.GetSession at\n%s", m.funcGetSessionOrigin)
	}

	if !m.GetSessionMock.invocationsDone() && afterGetSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.GetSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetSessionMock.expectedInvocations), m.GetSessionMock.expectedInvocationsOrigin, afterGetSessionCounter)
	}
}

type mSessionRepoMockGetSessionByRefreshToken struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockGetSessionByRefreshTokenExpectation
	expectations       []*SessionRepoMockGetSessionByRefreshTokenExpectation

	callArgs []*SessionRepoMockGetSessionByRefreshTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockGetSessionByRefreshTokenExpectation specifies expectation struct of the SessionRepo.GetSessionByRefreshToken
type SessionRepoMockGetSessionByRefreshTokenExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockGetSessionByRefreshTokenParams
	paramPtrs          *SessionRepoMockGetSessionByRefreshTokenParamPtrs
	expectationOrigins SessionRepoMockGetSessionByRefreshTokenExpectationOrigins
	results            *SessionRepoMockGetSessionByRefreshTokenResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockGetSessionByRefreshTokenParams contains parameters of the SessionRepo.GetSessionByRefreshToken
type SessionRepoMockGetSessionByRefreshTokenParams struct {
	token string
}

// SessionRepoMockGetSessionByRefreshTokenParamPtrs contains pointers to parameters of the SessionRepo.GetSessionByRefreshToken
type SessionRepoMockGetSessionByRefreshTokenParamPtrs struct {
	token *string
}

// SessionRepoMockGetSessionByRefreshTokenResults contains results of the SessionRepo.GetSessionByRefreshToken
type SessionRepoMockGetSessionByRefreshTokenResults struct {
	sp1 *models.Session
	err error
}

// SessionRepoMockGetSessionByRefreshTokenOrigins contains origins of expectations of the SessionRepo.GetSessionByRefreshToken
type SessionRepoMockGetSessionByRefreshTokenExpectationOrigins struct {
	origin      string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Optional() *mSessionRepoMockGetSessionByRefreshToken {
	mmGetSessionByRefreshToken.optional = true
	return mmGetSessionByRefreshToken
}

// Expect sets up expected params for SessionRepo.GetSessionByRefreshToken
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Expect(token string) *mSessionRepoMockGetSessionByRefreshToken {
	if mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshToken != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("SessionRepoMock.GetSessionByRefreshToken mock is already set by Set")
	}

	if mmGetSessionByRefreshToken.defaultExpectation == nil {
		mmGetSessionByRefreshToken.defaultExpectation = &SessionRepoMockGetSessionByRefreshTokenExpectation{}
	}

	if mmGetSessionByRefreshToken.defaultExpectation.paramPtrs != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("SessionRepoMock.GetSessionByRefreshToken mock is already set by ExpectParams functions")
	}

	mmGetSessionByRefreshToken.defaultExpectation.params = &SessionRepoMockGetSessionByRefreshTokenParams{token}
	mmGetSessionByRefreshToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetSessionByRefreshToken.expectations {
		if minimock.Equal(e.params, mmGetSessionByRefreshToken.defaultExpectation.params) {
			mmGetSessionByRefreshToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetSessionByRefreshToken.defaultExpectation.params)
		}
	}

	return mmGetSessionByRefreshToken
}

// ExpectTokenParam1 sets up expected param token for SessionRepo.GetSessionByRefreshToken
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) ExpectTokenParam1(token string) *mSessionRepoMockGetSessionByRefreshToken {
	if mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshToken != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("SessionRepoMock.GetSessionByRefreshToken mock is already set by Set")
	}

	if mmGetSessionByRefreshToken.defaultExpectation == nil {
		mmGetSessionByRefreshToken.defaultExpectation = &SessionRepoMockGetSessionByRefreshTokenExpectation{}
	}

	if mmGetSessionByRefreshToken.defaultExpectation.params != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("SessionRepoMock.GetSessionByRefreshToken mock is already set by Expect")
	}

	if mmGetSessionByRefreshToken.defaultExpectation.paramPtrs == nil {
		mmGetSessionByRefreshToken.defaultExpectation.paramPtrs = &SessionRepoMockGetSessionByRefreshTokenParamPtrs{}
	}
	mmGetSessionByRefreshToken.defaultExpectation.paramPtrs.token = &token
	mmGetSessionByRefreshToken.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmGetSessionByRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.GetSessionByRefreshToken
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Inspect(f func(token string)) *mSessionRepoMockGetSessionByRefreshToken {
	if mmGetSessionByRefreshToken.mock.inspectFuncGetSessionByRefreshToken != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.GetSessionByRefreshToken")
	}

	mmGetSessionByRefreshToken.mock.inspectFuncGetSessionByRefreshToken = f

	return mmGetSessionByRefreshToken
}

// Return sets up results that will be returned by SessionRepo.GetSessionByRefreshToken
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Return(sp1 *models.Session, err error) *SessionRepoMock {
	if mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshToken != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("SessionRepoMock.GetSessionByRefreshToken mock is already set by Set")
	}

	if mmGetSessionByRefreshToken.defaultExpectation == nil {
		mmGetSessionByRefreshToken.defaultExpectation = &SessionRepoMockGetSessionByRefreshTokenExpectation{mock: mmGetSessionByRefreshToken.mock}
	}
	mmGetSessionByRefreshToken.defaultExpectation.results = &SessionRepoMockGetSessionByRefreshTokenResults{sp1, err}
	mmGetSessionByRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetSessionByRefreshToken.mock
}

// Set uses given function f to mock the SessionRepo.GetSessionByRefreshToken method
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Set(f func(token string) (sp1 *models.Session, err error)) *SessionRepoMock {
	if mmGetSessionByRefreshToken.defaultExpectation != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("Default expectation is already set for the SessionRepo.GetSessionByRefreshToken method")
	}

	if len(mmGetSessionByRefreshToken.expectations) > 0 {
		mmGetSessionByRefreshToken.mock.t.Fatalf("Some expectations are already set for the SessionRepo.GetSessionByRefreshToken method")
	}

	mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshToken = f
	mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmGetSessionByRefreshToken.mock
}

// When sets expectation for the SessionRepo.GetSessionByRefreshToken which will trigger the result defined by the following
// Then helper
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) When(token string) *SessionRepoMockGetSessionByRefreshTokenExpectation {
	if mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshToken != nil {
		mmGetSessionByRefreshToken.mock.t.Fatalf("SessionRepoMock.GetSessionByRefreshToken mock is already set by Set")
	}

	expectation := &SessionRepoMockGetSessionByRefreshTokenExpectation{
		mock:               mmGetSessionByRefreshToken.mock,
		params:             &SessionRepoMockGetSessionByRefreshTokenParams{token},
		expectationOrigins: SessionRepoMockGetSessionByRefreshTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetSessionByRefreshToken.expectations = append(mmGetSessionByRefreshToken.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.GetSessionByRefreshToken return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockGetSessionByRefreshTokenExpectation) Then(sp1 *models.Session, err error) *SessionRepoMock {
	e.results = &SessionRepoMockGetSessionByRefreshTokenResults{sp1, err}
	return e.mock
}

// Times sets number of times SessionRepo.GetSessionByRefreshToken should be invoked
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Times(n uint64) *mSessionRepoMockGetSessionByRefreshToken {
	if n == 0 {
		mmGetSessionByRefreshToken.mock.t.Fatalf("Times of SessionRepoMock.GetSessionByRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetSessionByRefreshToken.expectedInvocations, n)
	mmGetSessionByRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetSessionByRefreshToken
}

func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) invocationsDone() bool {
	if len(mmGetSessionByRefreshToken.expectations) == 0 && mmGetSessionByRefreshToken.defaultExpectation == nil && mmGetSessionByRefreshToken.mock.funcGetSessionByRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetSessionByRefreshToken.mock.afterGetSessionByRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetSessionByRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetSessionByRefreshToken implements mm_auth.SessionRepo
func (mmGetSessionByRefreshToken *SessionRepoMock) GetSessionByRefreshToken(token string) (sp1 *models.Session, err error) {
	mm_atomic.AddUint64(&mmGetSessionByRefreshToken.beforeGetSessionByRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmGetSessionByRefreshToken.afterGetSessionByRefreshTokenCounter, 1)

	mmGetSessionByRefreshToken.t.Helper()

	if mmGetSessionByRefreshToken.inspectFuncGetSessionByRefreshToken != nil {
		mmGetSessionByRefreshToken.inspectFuncGetSessionByRefreshToken(token)
	}

	mm_params := SessionRepoMockGetSessionByRefreshTokenParams{token}

	// Record call args
	mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.mutex.Lock()
	mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.callArgs = append(mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.callArgs, &mm_params)
	mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.mutex.Unlock()

	for _, e := range mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.err
		}
	}

	if mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation.params
		mm_want_ptrs := mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockGetSessionByRefreshTokenParams{token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmGetSessionByRefreshToken.t.Errorf("SessionRepoMock.GetSessionByRefreshToken got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetSessionByRefreshToken.t.Errorf("SessionRepoMock.GetSessionByRefreshToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetSessionByRefreshToken.GetSessionByRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmGetSessionByRefreshToken.t.Fatal("No results are set for the SessionRepoMock.GetSessionByRefreshToken")
		}
		return (*mm_results).sp1, (*mm_results).err
	}
	if mmGetSessionByRefreshToken.funcGetSessionByRefreshToken != nil {
		return mmGetSessionByRefreshToken.funcGetSessionByRefreshToken(token)
	}
	mmGetSessionByRefreshToken.t.Fatalf("Unexpected call to SessionRepoMock.GetSessionByRefreshToken. %v", token)
	return
}

// GetSessionByRefreshTokenAfterCounter returns a count of finished SessionRepoMock.GetSessionByRefreshToken invocations
func (mmGetSessionByRefreshToken *SessionRepoMock) GetSessionByRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetSessionByRefreshToken.afterGetSessionByRefreshTokenCounter)
}

// GetSessionByRefreshTokenBeforeCounter returns a count of SessionRepoMock.GetSessionByRefreshToken invocations
func (mmGetSessionByRefreshToken *SessionRepoMock) GetSessionByRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetSessionByRefreshToken.beforeGetSessionByRefreshTokenCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.GetSessionByRefreshToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetSessionByRefreshToken *mSessionRepoMockGetSessionByRefreshToken) Calls() []*SessionRepoMockGetSessionByRefreshTokenParams {
	mmGetSessionByRefreshToken.mutex.RLock()

	argCopy := make([]*SessionRepoMockGetSessionByRefreshTokenParams, len(mmGetSessionByRefreshToken.callArgs))
	copy(argCopy, mmGetSessionByRefreshToken.callArgs)

	mmGetSessionByRefreshToken.mutex.RUnlock()

	return argCopy
}

// MinimockGetSessionByRefreshTokenDone returns true if the count of the GetSessionByRefreshToken invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockGetSessionByRefreshTokenDone() bool {
	if m.GetSessionByRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetSessionByRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetSessionByRefreshTokenMock.invocationsDone()
}

// MinimockGetSessionByRefreshTokenInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockGetSessionByRefreshTokenInspect() {
	for _, e := range m.GetSessionByRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.GetSessionByRefreshToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetSessionByRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterGetSessionByRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetSessionByRefreshTokenMock.defaultExpectation != nil && afterGetSessionByRefreshTokenCounter < 1 {
		if m.GetSessionByRefreshTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.GetSessionByRefreshToken at\n%s", m.GetSessionByRefreshTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.GetSessionByRefreshToken at\n%s with params: %#v", m.GetSessionByRefreshTokenMock.defaultExpectation.expectationOrigins.origin, *m.GetSessionByRefreshTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetSessionByRefreshToken != nil && afterGetSessionByRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.GetSessionByRefreshToken at\n%s", m.funcGetSessionByRefreshTokenOrigin)
	}

	if !m.GetSessionByRefreshTokenMock.invocationsDone() && afterGetSessionByRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.GetSessionByRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetSessionByRefreshTokenMock.expectedInvocations), m.GetSessionByRefreshTokenMock.expectedInvocationsOrigin, afterGetSessionByRefreshTokenCounter)
	}
}

type mSessionRepoMockRevokeSession struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockRevokeSessionExpectation
	expectations       []*SessionRepoMockRevokeSessionExpectation

	callArgs []*SessionRepoMockRevokeSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockRevokeSessionExpectation specifies expectation struct of the SessionRepo.RevokeSession
type SessionRepoMockRevokeSessionExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockRevokeSessionParams
	paramPtrs          *SessionRepoMockRevokeSessionParamPtrs
	expectationOrigins SessionRepoMockRevokeSessionExpectationOrigins
	results            *SessionRepoMockRevokeSessionResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockRevokeSessionParams contains parameters of the SessionRepo.RevokeSession
type SessionRepoMockRevokeSessionParams struct {
	id int64
}

// SessionRepoMockRevokeSessionParamPtrs contains pointers to parameters of the SessionRepo.RevokeSession
type SessionRepoMockRevokeSessionParamPtrs struct {
	id *int64
}

// SessionRepoMockRevokeSessionResults contains results of the SessionRepo.RevokeSession
type SessionRepoMockRevokeSessionResults struct {
	err error
}

// SessionRepoMockRevokeSessionOrigins contains origins of expectations of the SessionRepo.RevokeSession
type SessionRepoMockRevokeSessionExpectationOrigins struct {
	origin   string
	originId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRevokeSession *mSessionRepoMockRevokeSession) Optional() *mSessionRepoMockRevokeSession {
	mmRevokeSession.optional = true
	return mmRevokeSession
}

// Expect sets up expected params for SessionRepo.RevokeSession
func (mmRevokeSession *mSessionRepoMockRevokeSession) Expect(id int64) *mSessionRepoMockRevokeSession {
	if mmRevokeSession.mock.funcRevokeSession != nil {
		mmRevokeSession.mock.t.Fatalf("SessionRepoMock.RevokeSession mock is already set by Set")
	}

	if mmRevokeSession.defaultExpectation == nil {
		mmRevokeSession.defaultExpectation = &SessionRepoMockRevokeSessionExpectation{}
	}

	if mmRevokeSession.defaultExpectation.paramPtrs != nil {
		mmRevokeSession.mock.t.Fatalf("SessionRepoMock.RevokeSession mock is already set by ExpectParams functions")
	}

	mmRevokeSession.defaultExpectation.params = &SessionRepoMockRevokeSessionParams{id}
	mmRevokeSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRevokeSession.expectations {
		if minimock.Equal(e.params, mmRevokeSession.defaultExpectation.params) {
			mmRevokeSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRevokeSession.defaultExpectation.params)
		}
	}

	return mmRevokeSession
}

// ExpectIdParam1 sets up expected param id for SessionRepo.RevokeSession
func (mmRevokeSession *mSessionRepoMockRevokeSession) ExpectIdParam1(id int64) *mSessionRepoMockRevokeSession {
	if mmRevokeSession.mock.funcRevokeSession != nil {
		mmRevokeSession.mock.t.Fatalf("SessionRepoMock.RevokeSession mock is already set by Set")
	}

	if mmRevokeSession.defaultExpectation == nil {
		mmRevokeSession.defaultExpectation = &SessionRepoMockRevokeSessionExpectation{}
	}

	if mmRevokeSession.defaultExpectation.params != nil {
		mmRevokeSession.mock.t.Fatalf("SessionRepoMock.RevokeSession mock is already set by Expect")
	}

	if mmRevokeSession.defaultExpectation.paramPtrs == nil {
		mmRevokeSession.defaultExpectation.paramPtrs = &SessionRepoMockRevokeSessionParamPtrs{}
	}
	mmRevokeSession.defaultExpectation.paramPtrs.id = &id
	mmRevokeSession.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmRevokeSession
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.RevokeSession
func (mmRevokeSession *mSessionRepoMockRevokeSession) Inspect(f func(id int64)) *mSessionRepoMockRevokeSession {
	if mmRevokeSession.mock.inspectFuncRevokeSession != nil {
		mmRevokeSession.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.RevokeSession")
	}

	mmRevokeSession.mock.inspectFuncRevokeSession = f

	return mmRevokeSession
}

// Return sets up results that will be returned by SessionRepo.RevokeSession
func (mmRevokeSession *mSessionRepoMockRevokeSession) Return(err error) *SessionRepoMock {
	if mmRevokeSession.mock.funcRevokeSession != nil {
		mmRevokeSession.mock.t.Fatalf("SessionRepoMock.RevokeSession mock is already set by Set")
	}

	if mmRevokeSession.defaultExpectation == nil {
		mmRevokeSession.defaultExpectation = &SessionRepoMockRevokeSessionExpectation{mock: mmRevokeSession.mock}
	}
	mmRevokeSession.defaultExpectation.results = &SessionRepoMockRevokeSessionResults{err}
	mmRevokeSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRevokeSession.mock
}

// Set uses given function f to mock the SessionRepo.RevokeSession method
func (mmRevokeSession *mSessionRepoMockRevokeSession) Set(f func(id int64) (err error)) *SessionRepoMock {
	if mmRevokeSession.defaultExpectation != nil {
		mmRevokeSession.mock.t.Fatalf("Default expectation is already set for the SessionRepo.RevokeSession method")
	}

	if len(mmRevokeSession.expectations) > 0 {
		mmRevokeSession.mock.t.Fatalf("Some expectations are already set for the SessionRepo.RevokeSession method")
	}

	mmRevokeSession.mock.funcRevokeSession = f
	mmRevokeSession.mock.funcRevokeSessionOrigin = minimock.CallerInfo(1)
	return mmRevokeSession.mock
}

// When sets expectation for the SessionRepo.RevokeSession which will trigger the result defined by the following
// Then helper
func (mmRevokeSession *mSessionRepoMockRevokeSession) When(id int64) *SessionRepoMockRevokeSessionExpectation {
	if mmRevokeSession.mock.funcRevokeSession != nil {
		mmRevokeSession.mock.t.Fatalf("SessionRepoMock.RevokeSession mock is already set by Set")
	}

	expectation := &SessionRepoMockRevokeSessionExpectation{
		mock:               mmRevokeSession.mock,
		params:             &SessionRepoMockRevokeSessionParams{id},
		expectationOrigins: SessionRepoMockRevokeSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRevokeSession.expectations = append(mmRevokeSession.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.RevokeSession return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockRevokeSessionExpectation) Then(err error) *SessionRepoMock {
	e.results = &SessionRepoMockRevokeSessionResults{err}
	return e.mock
}

// Times sets number of times SessionRepo.RevokeSession should be invoked
func (mmRevokeSession *mSessionRepoMockRevokeSession) Times(n uint64) *mSessionRepoMockRevokeSession {
	if n == 0 {
		mmRevokeSession.mock.t.Fatalf("Times of SessionRepoMock.RevokeSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRevokeSession.expectedInvocations, n)
	mmRevokeSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRevokeSession
}

func (mmRevokeSession *mSessionRepoMockRevokeSession) invocationsDone() bool {
	if len(mmRevokeSession.expectations) == 0 && mmRevokeSession.defaultExpectation == nil && mmRevokeSession.mock.funcRevokeSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRevokeSession.mock.afterRevokeSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRevokeSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RevokeSession implements mm_auth.SessionRepo
func (mmRevokeSession *SessionRepoMock) RevokeSession(id int64) (err error) {
	mm_atomic.AddUint64(&mmRevokeSession.beforeRevokeSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmRevokeSession.afterRevokeSessionCounter, 1)

	mmRevokeSession.t.Helper()

	if mmRevokeSession.inspectFuncRevokeSession != nil {
		mmRevokeSession.inspectFuncRevokeSession(id)
	}

	mm_params := SessionRepoMockRevokeSessionParams{id}

	// Record call args
	mmRevokeSession.RevokeSessionMock.mutex.Lock()
	mmRevokeSession.RevokeSessionMock.callArgs = append(mmRevokeSession.RevokeSessionMock.callArgs, &mm_params)
	mmRevokeSession.RevokeSessionMock.mutex.Unlock()

	for _, e := range mmRevokeSession.RevokeSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRevokeSession.RevokeSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRevokeSession.RevokeSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmRevokeSession.RevokeSessionMock.defaultExpectation.params
		mm_want_ptrs := mmRevokeSession.RevokeSessionMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockRevokeSessionParams{id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmRevokeSession.t.Errorf("SessionRepoMock.RevokeSession got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRevokeSession.RevokeSessionMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRevokeSession.t.Errorf("SessionRepoMock.RevokeSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRevokeSession.RevokeSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRevokeSession.RevokeSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmRevokeSession.t.Fatal("No results are set for the SessionRepoMock.RevokeSession")
		}
		return (*mm_results).err
	}
	if mmRevokeSession.funcRevokeSession != nil {
		return mmRevokeSession.funcRevokeSession(id)
	}
	mmRevokeSession.t.Fatalf("Unexpected call to SessionRepoMock.RevokeSession. %v", id)
	return
}

// RevokeSessionAfterCounter returns a count of finished SessionRepoMock.RevokeSession invocations
func (mmRevokeSession *SessionRepoMock) RevokeSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRevokeSession.afterRevokeSessionCounter)
}

// RevokeSessionBeforeCounter returns a count of SessionRepoMock.RevokeSession invocations
func (mmRevokeSession *SessionRepoMock) RevokeSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRevokeSession.beforeRevokeSessionCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.RevokeSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRevokeSession *mSessionRepoMockRevokeSession) Calls() []*SessionRepoMockRevokeSessionParams {
	mmRevokeSession.mutex.RLock()

	argCopy := make([]*SessionRepoMockRevokeSessionParams, len(mmRevokeSession.callArgs))
	copy(argCopy, mmRevokeSession.callArgs)

	mmRevokeSession.mutex.RUnlock()

	return argCopy
}

// MinimockRevokeSessionDone returns true if the count of the RevokeSession invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockRevokeSessionDone() bool {
	if m.RevokeSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RevokeSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RevokeSessionMock.invocationsDone()
}

// MinimockRevokeSessionInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockRevokeSessionInspect() {
	for _, e := range m.RevokeSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.RevokeSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRevokeSessionCounter := mm_atomic.LoadUint64(&m.afterRevokeSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RevokeSessionMock.defaultExpectation != nil && afterRevokeSessionCounter < 1 {
		if m.RevokeSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.RevokeSession at\n%s", m.RevokeSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.RevokeSession at\n%s with params: %#v", m.RevokeSessionMock.defaultExpectation.expectationOrigins.origin, *m.RevokeSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRevokeSession != nil && afterRevokeSessionCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.RevokeSession at\n%s", m.funcRevokeSessionOrigin)
	}

	if !m.RevokeSessionMock.invocationsDone() && afterRevokeSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.RevokeSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RevokeSessionMock.expectedInvocations), m.RevokeSessionMock.expectedInvocationsOrigin, afterRevokeSessionCounter)
	}
}

type mSessionRepoMockRevokeSessionsByUser struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockRevokeSessionsByUserExpectation
	expectations       []*SessionRepoMockRevokeSessionsByUserExpectation

	callArgs []*SessionRepoMockRevokeSessionsByUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockRevokeSessionsByUserExpectation specifies expectation struct of the SessionRepo.RevokeSessionsByUser
type SessionRepoMockRevokeSessionsByUserExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockRevokeSessionsByUserParams
	paramPtrs          *SessionRepoMockRevokeSessionsByUserParamPtrs
	expectationOrigins SessionRepoMockRevokeSessionsByUserExpectationOrigins
	results            *SessionRepoMockRevokeSessionsByUserResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockRevokeSessionsByUserParams contains parameters of the SessionRepo.RevokeSessionsByUser
type SessionRepoMockRevokeSessionsByUserParams struct {
	userID int64
}

// SessionRepoMockRevokeSessionsByUserParamPtrs contains pointers to parameters of the SessionRepo.RevokeSessionsByUser
type SessionRepoMockRevokeSessionsByUserParamPtrs struct {
	userID *int64
}

// SessionRepoMockRevokeSessionsByUserResults contains results of the SessionRepo.RevokeSessionsByUser
type SessionRepoMockRevokeSessionsByUserResults struct {
	err error
}

// SessionRepoMockRevokeSessionsByUserOrigins contains origins of expectations of the SessionRepo.RevokeSessionsByUser
type SessionRepoMockRevokeSessionsByUserExpectationOrigins struct {
	origin       string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Optional() *mSessionRepoMockRevokeSessionsByUser {
	mmRevokeSessionsByUser.optional = true
	return mmRevokeSessionsByUser
}

// Expect sets up expected params for SessionRepo.RevokeSessionsByUser
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Expect(userID int64) *mSessionRepoMockRevokeSessionsByUser {
	if mmRevokeSessionsByUser.mock.funcRevokeSessionsByUser != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("SessionRepoMock.RevokeSessionsByUser mock is already set by Set")
	}

	if mmRevokeSessionsByUser.defaultExpectation == nil {
		mmRevokeSessionsByUser.defaultExpectation = &SessionRepoMockRevokeSessionsByUserExpectation{}
	}

	if mmRevokeSessionsByUser.defaultExpectation.paramPtrs != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("SessionRepoMock.RevokeSessionsByUser mock is already set by ExpectParams functions")
	}

	mmRevokeSessionsByUser.defaultExpectation.params = &SessionRepoMockRevokeSessionsByUserParams{userID}
	mmRevokeSessionsByUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRevokeSessionsByUser.expectations {
		if minimock.Equal(e.params, mmRevokeSessionsByUser.defaultExpectation.params) {
			mmRevokeSessionsByUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRevokeSessionsByUser.defaultExpectation.params)
		}
	}

	return mmRevokeSessionsByUser
}

// ExpectUserIDParam1 sets up expected param userID for SessionRepo.RevokeSessionsByUser
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) ExpectUserIDParam1(userID int64) *mSessionRepoMockRevokeSessionsByUser {
	if mmRevokeSessionsByUser.mock.funcRevokeSessionsByUser != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("SessionRepoMock.RevokeSessionsByUser mock is already set by Set")
	}

	if mmRevokeSessionsByUser.defaultExpectation == nil {
		mmRevokeSessionsByUser.defaultExpectation = &SessionRepoMockRevokeSessionsByUserExpectation{}
	}

	if mmRevokeSessionsByUser.defaultExpectation.params != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("SessionRepoMock.RevokeSessionsByUser mock is already set by Expect")
	}

	if mmRevokeSessionsByUser.defaultExpectation.paramPtrs == nil {
		mmRevokeSessionsByUser.defaultExpectation.paramPtrs = &SessionRepoMockRevokeSessionsByUserParamPtrs{}
	}
	mmRevokeSessionsByUser.defaultExpectation.paramPtrs.userID = &userID
	mmRevokeSessionsByUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmRevokeSessionsByUser
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.RevokeSessionsByUser
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Inspect(f func(userID int64)) *mSessionRepoMockRevokeSessionsByUser {
	if mmRevokeSessionsByUser.mock.inspectFuncRevokeSessionsByUser != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.RevokeSessionsByUser")
	}

	mmRevokeSessionsByUser.mock.inspectFuncRevokeSessionsByUser = f

	return mmRevokeSessionsByUser
}

// Return sets up results that will be returned by SessionRepo.RevokeSessionsByUser
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Return(err error) *SessionRepoMock {
	if mmRevokeSessionsByUser.mock.funcRevokeSessionsByUser != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("SessionRepoMock.RevokeSessionsByUser mock is already set by Set")
	}

	if mmRevokeSessionsByUser.defaultExpectation == nil {
		mmRevokeSessionsByUser.defaultExpectation = &SessionRepoMockRevokeSessionsByUserExpectation{mock: mmRevokeSessionsByUser.mock}
	}
	mmRevokeSessionsByUser.defaultExpectation.results = &SessionRepoMockRevokeSessionsByUserResults{err}
	mmRevokeSessionsByUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRevokeSessionsByUser.mock
}

// Set uses given function f to mock the SessionRepo.RevokeSessionsByUser method
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Set(f func(userID int64) (err error)) *SessionRepoMock {
	if mmRevokeSessionsByUser.defaultExpectation != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("Default expectation is already set for the SessionRepo.RevokeSessionsByUser method")
	}

	if len(mmRevokeSessionsByUser.expectations) > 0 {
		mmRevokeSessionsByUser.mock.t.Fatalf("Some expectations are already set for the SessionRepo.RevokeSessionsByUser method")
	}

	mmRevokeSessionsByUser.mock.funcRevokeSessionsByUser = f
	mmRevokeSessionsByUser.mock.funcRevokeSessionsByUserOrigin = minimock.CallerInfo(1)
	return mmRevokeSessionsByUser.mock
}

// When sets expectation for the SessionRepo.RevokeSessionsByUser which will trigger the result defined by the following
// Then helper
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) When(userID int64) *SessionRepoMockRevokeSessionsByUserExpectation {
	if mmRevokeSessionsByUser.mock.funcRevokeSessionsByUser != nil {
		mmRevokeSessionsByUser.mock.t.Fatalf("SessionRepoMock.RevokeSessionsByUser mock is already set by Set")
	}

	expectation := &SessionRepoMockRevokeSessionsByUserExpectation{
		mock:               mmRevokeSessionsByUser.mock,
		params:             &SessionRepoMockRevokeSessionsByUserParams{userID},
		expectationOrigins: SessionRepoMockRevokeSessionsByUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRevokeSessionsByUser.expectations = append(mmRevokeSessionsByUser.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.RevokeSessionsByUser return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockRevokeSessionsByUserExpectation) Then(err error) *SessionRepoMock {
	e.results = &SessionRepoMockRevokeSessionsByUserResults{err}
	return e.mock
}

// Times sets number of times SessionRepo.RevokeSessionsByUser should be invoked
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Times(n uint64) *mSessionRepoMockRevokeSessionsByUser {
	if n == 0 {
		mmRevokeSessionsByUser.mock.t.Fatalf("Times of SessionRepoMock.RevokeSessionsByUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRevokeSessionsByUser.expectedInvocations, n)
	mmRevokeSessionsByUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRevokeSessionsByUser
}

func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) invocationsDone() bool {
	if len(mmRevokeSessionsByUser.expectations) == 0 && mmRevokeSessionsByUser.defaultExpectation == nil && mmRevokeSessionsByUser.mock.funcRevokeSessionsByUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRevokeSessionsByUser.mock.afterRevokeSessionsByUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRevokeSessionsByUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RevokeSessionsByUser implements mm_auth.SessionRepo
func (mmRevokeSessionsByUser *SessionRepoMock) RevokeSessionsByUser(userID int64) (err error) {
	mm_atomic.AddUint64(&mmRevokeSessionsByUser.beforeRevokeSessionsByUserCounter, 1)
	defer mm_atomic.AddUint64(&mmRevokeSessionsByUser.afterRevokeSessionsByUserCounter, 1)

	mmRevokeSessionsByUser.t.Helper()

	if mmRevokeSessionsByUser.inspectFuncRevokeSessionsByUser != nil {
		mmRevokeSessionsByUser.inspectFuncRevokeSessionsByUser(userID)
	}

	mm_params := SessionRepoMockRevokeSessionsByUserParams{userID}

	// Record call args
	mmRevokeSessionsByUser.RevokeSessionsByUserMock.mutex.Lock()
	mmRevokeSessionsByUser.RevokeSessionsByUserMock.callArgs = append(mmRevokeSessionsByUser.RevokeSessionsByUserMock.callArgs, &mm_params)
	mmRevokeSessionsByUser.RevokeSessionsByUserMock.mutex.Unlock()

	for _, e := range mmRevokeSessionsByUser.RevokeSessionsByUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation.Counter, 1)
		mm_want := mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation.params
		mm_want_ptrs := mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockRevokeSessionsByUserParams{userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmRevokeSessionsByUser.t.Errorf("SessionRepoMock.RevokeSessionsByUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRevokeSessionsByUser.t.Errorf("SessionRepoMock.RevokeSessionsByUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRevokeSessionsByUser.RevokeSessionsByUserMock.defaultExpectation.results
		if mm_results == nil {
			mmRevokeSessionsByUser.t.Fatal("No results are set for the SessionRepoMock.RevokeSessionsByUser")
		}
		return (*mm_results).err
	}
	if mmRevokeSessionsByUser.funcRevokeSessionsByUser != nil {
		return mmRevokeSessionsByUser.funcRevokeSessionsByUser(userID)
	}
	mmRevokeSessionsByUser.t.Fatalf("Unexpected call to SessionRepoMock.RevokeSessionsByUser. %v", userID)
	return
}

// RevokeSessionsByUserAfterCounter returns a count of finished SessionRepoMock.RevokeSessionsByUser invocations
func (mmRevokeSessionsByUser *SessionRepoMock) RevokeSessionsByUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRevokeSessionsByUser.afterRevokeSessionsByUserCounter)
}

// RevokeSessionsByUserBeforeCounter returns a count of SessionRepoMock.RevokeSessionsByUser invocations
func (mmRevokeSessionsByUser *SessionRepoMock) RevokeSessionsByUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRevokeSessionsByUser.beforeRevokeSessionsByUserCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.RevokeSessionsByUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRevokeSessionsByUser *mSessionRepoMockRevokeSessionsByUser) Calls() []*SessionRepoMockRevokeSessionsByUserParams {
	mmRevokeSessionsByUser.mutex.RLock()

	argCopy := make([]*SessionRepoMockRevokeSessionsByUserParams, len(mmRevokeSessionsByUser.callArgs))
	copy(argCopy, mmRevokeSessionsByUser.callArgs)

	mmRevokeSessionsByUser.mutex.RUnlock()

	return argCopy
}

// MinimockRevokeSessionsByUserDone returns true if the count of the RevokeSessionsByUser invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockRevokeSessionsByUserDone() bool {
	if m.RevokeSessionsByUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RevokeSessionsByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RevokeSessionsByUserMock.invocationsDone()
}

// MinimockRevokeSessionsByUserInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockRevokeSessionsByUserInspect() {
	for _, e := range m.RevokeSessionsByUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.RevokeSessionsByUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRevokeSessionsByUserCounter := mm_atomic.LoadUint64(&m.afterRevokeSessionsByUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RevokeSessionsByUserMock.defaultExpectation != nil && afterRevokeSessionsByUserCounter < 1 {
		if m.RevokeSessionsByUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.RevokeSessionsByUser at\n%s", m.RevokeSessionsByUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.RevokeSessionsByUser at\n%s with params: %#v", m.RevokeSessionsByUserMock.defaultExpectation.expectationOrigins.origin, *m.RevokeSessionsByUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRevokeSessionsByUser != nil && afterRevokeSessionsByUserCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.RevokeSessionsByUser at\n%s", m.funcRevokeSessionsByUserOrigin)
	}

	if !m.RevokeSessionsByUserMock.invocationsDone() && afterRevokeSessionsByUserCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.RevokeSessionsByUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RevokeSessionsByUserMock.expectedInvocations), m.RevokeSessionsByUserMock.expectedInvocationsOrigin, afterRevokeSessionsByUserCounter)
	}
}

type mSessionRepoMockUpdateLastSeenAt struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockUpdateLastSeenAtExpectation
	expectations       []*SessionRepoMockUpdateLastSeenAtExpectation

	callArgs []*SessionRepoMockUpdateLastSeenAtParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockUpdateLastSeenAtExpectation specifies expectation struct of the SessionRepo.UpdateLastSeenAt
type SessionRepoMockUpdateLastSeenAtExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockUpdateLastSeenAtParams
	paramPtrs          *SessionRepoMockUpdateLastSeenAtParamPtrs
	expectationOrigins SessionRepoMockUpdateLastSeenAtExpectationOrigins
	results            *SessionRepoMockUpdateLastSeenAtResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockUpdateLastSeenAtParams contains parameters of the SessionRepo.UpdateLastSeenAt
type SessionRepoMockUpdateLastSeenAtParams struct {
	id int64
}

// SessionRepoMockUpdateLastSeenAtParamPtrs contains pointers to parameters of the SessionRepo.UpdateLastSeenAt
type SessionRepoMockUpdateLastSeenAtParamPtrs struct {
	id *int64
}

// SessionRepoMockUpdateLastSeenAtResults contains results of the SessionRepo.UpdateLastSeenAt
type SessionRepoMockUpdateLastSeenAtResults struct {
	err error
}

// SessionRepoMockUpdateLastSeenAtOrigins contains origins of expectations of the SessionRepo.UpdateLastSeenAt
type SessionRepoMockUpdateLastSeenAtExpectationOrigins struct {
	origin   string
	originId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Optional() *mSessionRepoMockUpdateLastSeenAt {
	mmUpdateLastSeenAt.optional = true
	return mmUpdateLastSeenAt
}

// Expect sets up expected params for SessionRepo.UpdateLastSeenAt
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Expect(id int64) *mSessionRepoMockUpdateLastSeenAt {
	if mmUpdateLastSeenAt.mock.funcUpdateLastSeenAt != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("SessionRepoMock.UpdateLastSeenAt mock is already set by Set")
	}

	if mmUpdateLastSeenAt.defaultExpectation == nil {
		mmUpdateLastSeenAt.defaultExpectation = &SessionRepoMockUpdateLastSeenAtExpectation{}
	}

	if mmUpdateLastSeenAt.defaultExpectation.paramPtrs != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("SessionRepoMock.UpdateLastSeenAt mock is already set by ExpectParams functions")
	}

	mmUpdateLastSeenAt.defaultExpectation.params = &SessionRepoMockUpdateLastSeenAtParams{id}
	mmUpdateLastSeenAt.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmUpdateLastSeenAt.expectations {
		if minimock.Equal(e.params, mmUpdateLastSeenAt.defaultExpectation.params) {
			mmUpdateLastSeenAt.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmUpdateLastSeenAt.defaultExpectation.params)
		}
	}

	return mmUpdateLastSeenAt
}

// ExpectIdParam1 sets up expected param id for SessionRepo.UpdateLastSeenAt
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) ExpectIdParam1(id int64) *mSessionRepoMockUpdateLastSeenAt {
	if mmUpdateLastSeenAt.mock.funcUpdateLastSeenAt != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("SessionRepoMock.UpdateLastSeenAt mock is already set by Set")
	}

	if mmUpdateLastSeenAt.defaultExpectation == nil {
		mmUpdateLastSeenAt.defaultExpectation = &SessionRepoMockUpdateLastSeenAtExpectation{}
	}

	if mmUpdateLastSeenAt.defaultExpectation.params != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("SessionRepoMock.UpdateLastSeenAt mock is already set by Expect")
	}

	if mmUpdateLastSeenAt.defaultExpectation.paramPtrs == nil {
		mmUpdateLastSeenAt.defaultExpectation.paramPtrs = &SessionRepoMockUpdateLastSeenAtParamPtrs{}
	}
	mmUpdateLastSeenAt.defaultExpectation.paramPtrs.id = &id
	mmUpdateLastSeenAt.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmUpdateLastSeenAt
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.UpdateLastSeenAt
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Inspect(f func(id int64)) *mSessionRepoMockUpdateLastSeenAt {
	if mmUpdateLastSeenAt.mock.inspectFuncUpdateLastSeenAt != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.UpdateLastSeenAt")
	}

	mmUpdateLastSeenAt.mock.inspectFuncUpdateLastSeenAt = f

	return mmUpdateLastSeenAt
}

// Return sets up results that will be returned by SessionRepo.UpdateLastSeenAt
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Return(err error) *SessionRepoMock {
	if mmUpdateLastSeenAt.mock.funcUpdateLastSeenAt != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("SessionRepoMock.UpdateLastSeenAt mock is already set by Set")
	}

	if mmUpdateLastSeenAt.defaultExpectation == nil {
		mmUpdateLastSeenAt.defaultExpectation = &SessionRepoMockUpdateLastSeenAtExpectation{mock: mmUpdateLastSeenAt.mock}
	}
	mmUpdateLastSeenAt.defaultExpectation.results = &SessionRepoMockUpdateLastSeenAtResults{err}
	mmUpdateLastSeenAt.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmUpdateLastSeenAt.mock
}

// Set uses given function f to mock the SessionRepo.UpdateLastSeenAt method
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Set(f func(id int64) (err error)) *SessionRepoMock {
	if mmUpdateLastSeenAt.defaultExpectation != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("Default expectation is already set for the SessionRepo.UpdateLastSeenAt method")
	}

	if len(mmUpdateLastSeenAt.expectations) > 0 {
		mmUpdateLastSeenAt.mock.t.Fatalf("Some expectations are already set for the SessionRepo.UpdateLastSeenAt method")
	}

	mmUpdateLastSeenAt.mock.funcUpdateLastSeenAt = f
	mmUpdateLastSeenAt.mock.funcUpdateLastSeenAtOrigin = minimock.CallerInfo(1)
	return mmUpdateLastSeenAt.mock
}

// When sets expectation for the SessionRepo.UpdateLastSeenAt which will trigger the result defined by the following
// Then helper
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) When(id int64) *SessionRepoMockUpdateLastSeenAtExpectation {
	if mmUpdateLastSeenAt.mock.funcUpdateLastSeenAt != nil {
		mmUpdateLastSeenAt.mock.t.Fatalf("SessionRepoMock.UpdateLastSeenAt mock is already set by Set")
	}

	expectation := &SessionRepoMockUpdateLastSeenAtExpectation{
		mock:               mmUpdateLastSeenAt.mock,
		params:             &SessionRepoMockUpdateLastSeenAtParams{id},
		expectationOrigins: SessionRepoMockUpdateLastSeenAtExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmUpdateLastSeenAt.expectations = append(mmUpdateLastSeenAt.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.UpdateLastSeenAt return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockUpdateLastSeenAtExpectation) Then(err error) *SessionRepoMock {
	e.results = &SessionRepoMockUpdateLastSeenAtResults{err}
	return e.mock
}

// Times sets number of times SessionRepo.UpdateLastSeenAt should be invoked
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Times(n uint64) *mSessionRepoMockUpdateLastSeenAt {
	if n == 0 {
		mmUpdateLastSeenAt.mock.t.Fatalf("Times of SessionRepoMock.UpdateLastSeenAt mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmUpdateLastSeenAt.expectedInvocations, n)
	mmUpdateLastSeenAt.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmUpdateLastSeenAt
}

func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) invocationsDone() bool {
	if len(mmUpdateLastSeenAt.expectations) == 0 && mmUpdateLastSeenAt.defaultExpectation == nil && mmUpdateLastSeenAt.mock.funcUpdateLastSeenAt == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmUpdateLastSeenAt.mock.afterUpdateLastSeenAtCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmUpdateLastSeenAt.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// UpdateLastSeenAt implements mm_auth.SessionRepo
func (mmUpdateLastSeenAt *SessionRepoMock) UpdateLastSeenAt(id int64) (err error) {
	mm_atomic.AddUint64(&mmUpdateLastSeenAt.beforeUpdateLastSeenAtCounter, 1)
	defer mm_atomic.AddUint64(&mmUpdateLastSeenAt.afterUpdateLastSeenAtCounter, 1)

	mmUpdateLastSeenAt.t.Helper()

	if mmUpdateLastSeenAt.inspectFuncUpdateLastSeenAt != nil {
		mmUpdateLastSeenAt.inspectFuncUpdateLastSeenAt(id)
	}

	mm_params := SessionRepoMockUpdateLastSeenAtParams{id}

	// Record call args
	mmUpdateLastSeenAt.UpdateLastSeenAtMock.mutex.Lock()
	mmUpdateLastSeenAt.UpdateLastSeenAtMock.callArgs = append(mmUpdateLastSeenAt.UpdateLastSeenAtMock.callArgs, &mm_params)
	mmUpdateLastSeenAt.UpdateLastSeenAtMock.mutex.Unlock()

	for _, e := range mmUpdateLastSeenAt.UpdateLastSeenAtMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation.Counter, 1)
		mm_want := mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation.params
		mm_want_ptrs := mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockUpdateLastSeenAtParams{id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmUpdateLastSeenAt.t.Errorf("SessionRepoMock.UpdateLastSeenAt got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmUpdateLastSeenAt.t.Errorf("SessionRepoMock.UpdateLastSeenAt got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmUpdateLastSeenAt.UpdateLastSeenAtMock.defaultExpectation.results
		if mm_results == nil {
			mmUpdateLastSeenAt.t.Fatal("No results are set for the SessionRepoMock.UpdateLastSeenAt")
		}
		return (*mm_results).err
	}
	if mmUpdateLastSeenAt.funcUpdateLastSeenAt != nil {
		return mmUpdateLastSeenAt.funcUpdateLastSeenAt(id)
	}
	mmUpdateLastSeenAt.t.Fatalf("Unexpected call to SessionRepoMock.UpdateLastSeenAt. %v", id)
	return
}

// UpdateLastSeenAtAfterCounter returns a count of finished SessionRepoMock.UpdateLastSeenAt invocations
func (mmUpdateLastSeenAt *SessionRepoMock) UpdateLastSeenAtAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateLastSeenAt.afterUpdateLastSeenAtCounter)
}

// UpdateLastSeenAtBeforeCounter returns a count of SessionRepoMock.UpdateLastSeenAt invocations
func (mmUpdateLastSeenAt *SessionRepoMock) UpdateLastSeenAtBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmUpdateLastSeenAt.beforeUpdateLastSeenAtCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.UpdateLastSeenAt.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmUpdateLastSeenAt *mSessionRepoMockUpdateLastSeenAt) Calls() []*SessionRepoMockUpdateLastSeenAtParams {
	mmUpdateLastSeenAt.mutex.RLock()

	argCopy := make([]*SessionRepoMockUpdateLastSeenAtParams, len(mmUpdateLastSeenAt.callArgs))
	copy(argCopy, mmUpdateLastSeenAt.callArgs)

	mmUpdateLastSeenAt.mutex.RUnlock()

	return argCopy
}

// MinimockUpdateLastSeenAtDone returns true if the count of the UpdateLastSeenAt invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockUpdateLastSeenAtDone() bool {
	if m.UpdateLastSeenAtMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.UpdateLastSeenAtMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.UpdateLastSeenAtMock.invocationsDone()
}

// MinimockUpdateLastSeenAtInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockUpdateLastSeenAtInspect() {
	for _, e := range m.UpdateLastSeenAtMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.UpdateLastSeenAt at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterUpdateLastSeenAtCounter := mm_atomic.LoadUint64(&m.afterUpdateLastSeenAtCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.UpdateLastSeenAtMock.defaultExpectation != nil && afterUpdateLastSeenAtCounter < 1 {
		if m.UpdateLastSeenAtMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.UpdateLastSeenAt at\n%s", m.UpdateLastSeenAtMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.UpdateLastSeenAt at\n%s with params: %#v", m.UpdateLastSeenAtMock.defaultExpectation.expectationOrigins.origin, *m.UpdateLastSeenAtMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcUpdateLastSeenAt != nil && afterUpdateLastSeenAtCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.UpdateLastSeenAt at\n%s", m.funcUpdateLastSeenAtOrigin)
	}

	if !m.UpdateLastSeenAtMock.invocationsDone() && afterUpdateLastSeenAtCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.UpdateLastSeenAt at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.UpdateLastSeenAtMock.expectedInvocations), m.UpdateLastSeenAtMock.expectedInvocationsOrigin, afterUpdateLastSeenAtCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SessionRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateSessionInspect()

			m.MinimockGetSessionInspect()

			m.MinimockGetSessionByRefreshTokenInspect()

			m.MinimockRevokeSessionInspect()

			m.MinimockRevokeSessionsByUserInspect()

			m.MinimockUpdateLastSeenAtInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SessionRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SessionRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateSessionDone() &&
		m.MinimockGetSessionDone() &&
		m.MinimockGetSessionByRefreshTokenDone() &&
		m.MinimockRevokeSessionDone() &&
		m.MinimockRevokeSessionsByUserDone() &&
		m.MinimockUpdateLastSeenAtDone()
}
