// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TokenManagerMock implements mm_auth.TokenManager
type TokenManagerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcNewAccessToken          func(userID int64, sessionID int64) (s1 string, err error)
	funcNewAccessTokenOrigin    string
	inspectFuncNewAccessToken   func(userID int64, sessionID int64)
	afterNewAccessTokenCounter  uint64
	beforeNewAccessTokenCounter uint64
	NewAccessTokenMock          mTokenManagerMockNewAccessToken

	funcNewRefreshToken          func() (s1 string, err error)
	funcNewRefreshTokenOrigin    string
	inspectFuncNewRefreshToken   func()
	afterNewRefreshTokenCounter  uint64
	beforeNewRefreshTokenCounter uint64
	NewRefreshTokenMock          mTokenManagerMockNewRefreshToken

	funcValidateToken          func(token string) (i1 int64, i2 int64, err error)
	funcValidateTokenOrigin    string
	inspectFuncValidateToken   func(token string)
	afterValidateTokenCounter  uint64
	beforeValidateTokenCounter uint64
	ValidateTokenMock          mTokenManagerMockValidateToken
}

// NewTokenManagerMock returns a mock for mm_auth.TokenManager
func NewTokenManagerMock(t minimock.Tester) *TokenManagerMock {
	m := &TokenManagerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.NewAccessTokenMock = mTokenManagerMockNewAccessToken{mock: m}
	m.NewAccessTokenMock.callArgs = []*TokenManagerMockNewAccessTokenParams{}

	m.NewRefreshTokenMock = mTokenManagerMockNewRefreshToken{mock: m}

	m.ValidateTokenMock = mTokenManagerMockValidateToken{mock: m}
	m.ValidateTokenMock.callArgs = []*TokenManagerMockValidateTokenParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTokenManagerMockNewAccessToken struct {
	optional           bool
	mock               *TokenManagerMock
	defaultExpectation *TokenManagerMockNewAccessTokenExpectation
	expectations       []*TokenManagerMockNewAccessTokenExpectation

	callArgs []*TokenManagerMockNewAccessTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenManagerMockNewAccessTokenExpectation specifies expectation struct of the TokenManager.NewAccessToken
type TokenManagerMockNewAccessTokenExpectation struct {
	mock               *TokenManagerMock
	params             *TokenManagerMockNewAccessTokenParams
	paramPtrs          *TokenManagerMockNewAccessTokenParamPtrs
	expectationOrigins TokenManagerMockNewAccessTokenExpectationOrigins
	results            *TokenManagerMockNewAccessTokenResults
	returnOrigin       string
	Counter            uint64
}

// TokenManagerMockNewAccessTokenParams contains parameters of the TokenManager.NewAccessToken
type TokenManagerMockNewAccessTokenParams struct {
	userID    int64
	sessionID int64
}

// TokenManagerMockNewAccessTokenParamPtrs contains pointers to parameters of the TokenManager.NewAccessToken
type TokenManagerMockNewAccessTokenParamPtrs struct {
	userID    *int64
	sessionID *int64
}

// TokenManagerMockNewAccessTokenResults contains results of the TokenManager.NewAccessToken
type TokenManagerMockNewAccessTokenResults struct {
	s1  string
	err error
}

// TokenManagerMockNewAccessTokenOrigins contains origins of expectations of the TokenManager.NewAccessToken
type TokenManagerMockNewAccessTokenExpectationOrigins struct {
	origin          string
	originUserID    string
	originSessionID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Optional() *mTokenManagerMockNewAccessToken {
	mmNewAccessToken.optional = true
	return mmNewAccessToken
}

// Expect sets up expected params for TokenManager.NewAccessToken
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Expect(userID int64, sessionID int64) *mTokenManagerMockNewAccessToken {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenManagerMockNewAccessTokenExpectation{}
	}

	if mmNewAccessToken.defaultExpectation.paramPtrs != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by ExpectParams functions")
	}

	mmNewAccessToken.defaultExpectation.params = &TokenManagerMockNewAccessTokenParams{userID, sessionID}
	mmNewAccessToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmNewAccessToken.expectations {
		if minimock.Equal(e.params, mmNewAccessToken.defaultExpectation.params) {
			mmNewAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNewAccessToken.defaultExpectation.params)
		}
	}

	return mmNewAccessToken
}

// ExpectUserIDParam1 sets up expected param userID for TokenManager.NewAccessToken
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) ExpectUserIDParam1(userID int64) *mTokenManagerMockNewAccessToken {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenManagerMockNewAccessTokenExpectation{}
	}

	if mmNewAccessToken.defaultExpectation.params != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Expect")
	}

	if mmNewAccessToken.defaultExpectation.paramPtrs == nil {
		mmNewAccessToken.defaultExpectation.paramPtrs = &TokenManagerMockNewAccessTokenParamPtrs{}
	}
	mmNewAccessToken.defaultExpectation.paramPtrs.userID = &userID
	mmNewAccessToken.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmNewAccessToken
}

// ExpectSessionIDParam2 sets up expected param sessionID for TokenManager.NewAccessToken
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) ExpectSessionIDParam2(sessionID int64) *mTokenManagerMockNewAccessToken {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenManagerMockNewAccessTokenExpectation{}
	}

	if mmNewAccessToken.defaultExpectation.params != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Expect")
	}

	if mmNewAccessToken.defaultExpectation.paramPtrs == nil {
		mmNewAccessToken.defaultExpectation.paramPtrs = &TokenManagerMockNewAccessTokenParamPtrs{}
	}
	mmNewAccessToken.defaultExpectation.paramPtrs.sessionID = &sessionID
	mmNewAccessToken.defaultExpectation.expectationOrigins.originSessionID = minimock.CallerInfo(1)

	return mmNewAccessToken
}

// Inspect accepts an inspector function that has same arguments as the TokenManager.NewAccessToken
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Inspect(f func(userID int64, sessionID int64)) *mTokenManagerMockNewAccessToken {
	if mmNewAccessToken.mock.inspectFuncNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("Inspect function is already set for TokenManagerMock.NewAccessToken")
	}

	mmNewAccessToken.mock.inspectFuncNewAccessToken = f

	return mmNewAccessToken
}

// Return sets up results that will be returned by TokenManager.NewAccessToken
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Return(s1 string, err error) *TokenManagerMock {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenManagerMockNewAccessTokenExpectation{mock: mmNewAccessToken.mock}
	}
	mmNewAccessToken.defaultExpectation.results = &TokenManagerMockNewAccessTokenResults{s1, err}
	mmNewAccessToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewAccessToken.mock
}

// Set uses given function f to mock the TokenManager.NewAccessToken method
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Set(f func(userID int64, sessionID int64) (s1 string, err error)) *TokenManagerMock {
	if mmNewAccessToken.defaultExpectation != nil {
		mmNewAccessToken.mock.t.Fatalf("Default expectation is already set for the TokenManager.NewAccessToken method")
	}

	if len(mmNewAccessToken.expectations) > 0 {
		mmNewAccessToken.mock.t.Fatalf("Some expectations are already set for the TokenManager.NewAccessToken method")
	}

	mmNewAccessToken.mock.funcNewAccessToken = f
	mmNewAccessToken.mock.funcNewAccessTokenOrigin = minimock.CallerInfo(1)
	return mmNewAccessToken.mock
}

// When sets expectation for the TokenManager.NewAccessToken which will trigger the result defined by the following
// Then helper
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) When(userID int64, sessionID int64) *TokenManagerMockNewAccessTokenExpectation {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenManagerMock.NewAccessToken mock is already set by Set")
	}

	expectation := &TokenManagerMockNewAccessTokenExpectation{
		mock:               mmNewAccessToken.mock,
		params:             &TokenManagerMockNewAccessTokenParams{userID, sessionID},
		expectationOrigins: TokenManagerMockNewAccessTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmNewAccessToken.expectations = append(mmNewAccessToken.expectations, expectation)
	return expectation
}

// Then sets up TokenManager.NewAccessToken return parameters for the expectation previously defined by the When method
func (e *TokenManagerMockNewAccessTokenExpectation) Then(s1 string, err error) *TokenManagerMock {
	e.results = &TokenManagerMockNewAccessTokenResults{s1, err}
	return e.mock
}

// Times sets number of times TokenManager.NewAccessToken should be invoked
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Times(n uint64) *mTokenManagerMockNewAccessToken {
	if n == 0 {
		mmNewAccessToken.mock.t.Fatalf("Times of TokenManagerMock.NewAccessToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewAccessToken.expectedInvocations, n)
	mmNewAccessToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewAccessToken
}

func (mmNewAccessToken *mTokenManagerMockNewAccessToken) invocationsDone() bool {
	if len(mmNewAccessToken.expectations) == 0 && mmNewAccessToken.defaultExpectation == nil && mmNewAccessToken.mock.funcNewAccessToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewAccessToken.mock.afterNewAccessTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewAccessToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewAccessToken implements mm_auth.TokenManager
func (mmNewAccessToken *TokenManagerMock) NewAccessToken(userID int64, sessionID int64) (s1 string, err error) {
	mm_atomic.AddUint64(&mmNewAccessToken.beforeNewAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmNewAccessToken.afterNewAccessTokenCounter, 1)

	mmNewAccessToken.t.Helper()

	if mmNewAccessToken.inspectFuncNewAccessToken != nil {
		mmNewAccessToken.inspectFuncNewAccessToken(userID, sessionID)
	}

	mm_params := TokenManagerMockNewAccessTokenParams{userID, sessionID}

	// Record call args
	mmNewAccessToken.NewAccessTokenMock.mutex.Lock()
	mmNewAccessToken.NewAccessTokenMock.callArgs = append(mmNewAccessToken.NewAccessTokenMock.callArgs, &mm_params)
	mmNewAccessToken.NewAccessTokenMock.mutex.Unlock()

	for _, e := range mmNewAccessToken.NewAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmNewAccessToken.NewAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewAccessToken.NewAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmNewAccessToken.NewAccessTokenMock.defaultExpectation.params
		mm_want_ptrs := mmNewAccessToken.NewAccessTokenMock.defaultExpectation.paramPtrs

		mm_got := TokenManagerMockNewAccessTokenParams{userID, sessionID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmNewAccessToken.t.Errorf("TokenManagerMock.NewAccessToken got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewAccessToken.NewAccessTokenMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.sessionID != nil && !minimock.Equal(*mm_want_ptrs.sessionID, mm_got.sessionID) {
				mmNewAccessToken.t.Errorf("TokenManagerMock.NewAccessToken got unexpected parameter sessionID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewAccessToken.NewAccessTokenMock.defaultExpectation.expectationOrigins.originSessionID, *mm_want_ptrs.sessionID, mm_got.sessionID, minimock.Diff(*mm_want_ptrs.sessionID, mm_got.sessionID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNewAccessToken.t.Errorf("TokenManagerMock.NewAccessToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmNewAccessToken.NewAccessTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNewAccessToken.NewAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmNewAccessToken.t.Fatal("No results are set for the TokenManagerMock.NewAccessToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmNewAccessToken.funcNewAccessToken != nil {
		return mmNewAccessToken.funcNewAccessToken(userID, sessionID)
	}
	mmNewAccessToken.t.Fatalf("Unexpected call to TokenManagerMock.NewAccessToken. %v %v", userID, sessionID)
	return
}

// NewAccessTokenAfterCounter returns a count of finished TokenManagerMock.NewAccessToken invocations
func (mmNewAccessToken *TokenManagerMock) NewAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewAccessToken.afterNewAccessTokenCounter)
}

// NewAccessTokenBeforeCounter returns a count of TokenManagerMock.NewAccessToken invocations
func (mmNewAccessToken *TokenManagerMock) NewAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewAccessToken.beforeNewAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenManagerMock.NewAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNewAccessToken *mTokenManagerMockNewAccessToken) Calls() []*TokenManagerMockNewAccessTokenParams {
	mmNewAccessToken.mutex.RLock()

	argCopy := make([]*TokenManagerMockNewAccessTokenParams, len(mmNewAccessToken.callArgs))
	copy(argCopy, mmNewAccessToken.callArgs)

	mmNewAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockNewAccessTokenDone returns true if the count of the NewAccessToken invocations corresponds
// the number of defined expectations
func (m *TokenManagerMock) MinimockNewAccessTokenDone() bool {
	if m.NewAccessTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewAccessTokenMock.invocationsDone()
}

// MinimockNewAccessTokenInspect logs each unmet expectation
func (m *TokenManagerMock) MinimockNewAccessTokenInspect() {
	for _, e := range m.NewAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenManagerMock.NewAccessToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterNewAccessTokenCounter := mm_atomic.LoadUint64(&m.afterNewAccessTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewAccessTokenMock.defaultExpectation != nil && afterNewAccessTokenCounter < 1 {
		if m.NewAccessTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TokenManagerMock.NewAccessToken at\n%s", m.NewAccessTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TokenManagerMock.NewAccessToken at\n%s with params: %#v", m.NewAccessTokenMock.defaultExpectation.expectationOrigins.origin, *m.NewAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewAccessToken != nil && afterNewAccessTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenManagerMock.NewAccessToken at\n%s", m.funcNewAccessTokenOrigin)
	}

	if !m.NewAccessTokenMock.invocationsDone() && afterNewAccessTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenManagerMock.NewAccessToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewAccessTokenMock.expectedInvocations), m.NewAccessTokenMock.expectedInvocationsOrigin, afterNewAccessTokenCounter)
	}
}

type mTokenManagerMockNewRefreshToken struct {
	optional           bool
	mock               *TokenManagerMock
	defaultExpectation *TokenManagerMockNewRefreshTokenExpectation
	expectations       []*TokenManagerMockNewRefreshTokenExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenManagerMockNewRefreshTokenExpectation specifies expectation struct of the TokenManager.NewRefreshToken
type TokenManagerMockNewRefreshTokenExpectation struct {
	mock *TokenManagerMock

	results      *TokenManagerMockNewRefreshTokenResults
	returnOrigin string
	Counter      uint64
}

// TokenManagerMockNewRefreshTokenResults contains results of the TokenManager.NewRefreshToken
type TokenManagerMockNewRefreshTokenResults struct {
	s1  string
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) Optional() *mTokenManagerMockNewRefreshToken {
	mmNewRefreshToken.optional = true
	return mmNewRefreshToken
}

// Expect sets up expected params for TokenManager.NewRefreshToken
func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) Expect() *mTokenManagerMockNewRefreshToken {
	if mmNewRefreshToken.mock.funcNewRefreshToken != nil {
		mmNewRefreshToken.mock.t.Fatalf("TokenManagerMock.NewRefreshToken mock is already set by Set")
	}

	if mmNewRefreshToken.defaultExpectation == nil {
		mmNewRefreshToken.defaultExpectation = &TokenManagerMockNewRefreshTokenExpectation{}
	}

	return mmNewRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the TokenManager.NewRefreshToken
func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) Inspect(f func()) *mTokenManagerMockNewRefreshToken {
	if mmNewRefreshToken.mock.inspectFuncNewRefreshToken != nil {
		mmNewRefreshToken.mock.t.Fatalf("Inspect function is already set for TokenManagerMock.NewRefreshToken")
	}

	mmNewRefreshToken.mock.inspectFuncNewRefreshToken = f

	return mmNewRefreshToken
}

// Return sets up results that will be returned by TokenManager.NewRefreshToken
func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) Return(s1 string, err error) *TokenManagerMock {
	if mmNewRefreshToken.mock.funcNewRefreshToken != nil {
		mmNewRefreshToken.mock.t.Fatalf("TokenManagerMock.NewRefreshToken mock is already set by Set")
	}

	if mmNewRefreshToken.defaultExpectation == nil {
		mmNewRefreshToken.defaultExpectation = &TokenManagerMockNewRefreshTokenExpectation{mock: mmNewRefreshToken.mock}
	}
	mmNewRefreshToken.defaultExpectation.results = &TokenManagerMockNewRefreshTokenResults{s1, err}
	mmNewRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewRefreshToken.mock
}

// Set uses given function f to mock the TokenManager.NewRefreshToken method
func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) Set(f func() (s1 string, err error)) *TokenManagerMock {
	if mmNewRefreshToken.defaultExpectation != nil {
		mmNewRefreshToken.mock.t.Fatalf("Default expectation is already set for the TokenManager.NewRefreshToken method")
	}

	if len(mmNewRefreshToken.expectations) > 0 {
		mmNewRefreshToken.mock.t.Fatalf("Some expectations are already set for the TokenManager.NewRefreshToken method")
	}

	mmNewRefreshToken.mock.funcNewRefreshToken = f
	mmNewRefreshToken.mock.funcNewRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmNewRefreshToken.mock
}

// Times sets number of times TokenManager.NewRefreshToken should be invoked
func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) Times(n uint64) *mTokenManagerMockNewRefreshToken {
	if n == 0 {
		mmNewRefreshToken.mock.t.Fatalf("Times of TokenManagerMock.NewRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewRefreshToken.expectedInvocations, n)
	mmNewRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewRefreshToken
}

func (mmNewRefreshToken *mTokenManagerMockNewRefreshToken) invocationsDone() bool {
	if len(mmNewRefreshToken.expectations) == 0 && mmNewRefreshToken.defaultExpectation == nil && mmNewRefreshToken.mock.funcNewRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewRefreshToken.mock.afterNewRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewRefreshToken implements mm_auth.TokenManager
func (mmNewRefreshToken *TokenManagerMock) NewRefreshToken() (s1 string, err error) {
	mm_atomic.AddUint64(&mmNewRefreshToken.beforeNewRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmNewRefreshToken.afterNewRefreshTokenCounter, 1)

	mmNewRefreshToken.t.Helper()

	if mmNewRefreshToken.inspectFuncNewRefreshToken != nil {
		mmNewRefreshToken.inspectFuncNewRefreshToken()
	}

	if mmNewRefreshToken.NewRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewRefreshToken.NewRefreshTokenMock.defaultExpectation.Counter, 1)

		mm_results := mmNewRefreshToken.NewRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmNewRefreshToken.t.Fatal("No results are set for the TokenManagerMock.NewRefreshToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmNewRefreshToken.funcNewRefreshToken != nil {
		return mmNewRefreshToken.funcNewRefreshToken()
	}
	mmNewRefreshToken.t.Fatalf("Unexpected call to TokenManagerMock.NewRefreshToken.")
	return
}

// NewRefreshTokenAfterCounter returns a count of finished TokenManagerMock.NewRefreshToken invocations
func (mmNewRefreshToken *TokenManagerMock) NewRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewRefreshToken.afterNewRefreshTokenCounter)
}

// NewRefreshTokenBeforeCounter returns a count of TokenManagerMock.NewRefreshToken invocations
func (mmNewRefreshToken *TokenManagerMock) NewRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewRefreshToken.beforeNewRefreshTokenCounter)
}

// MinimockNewRefreshTokenDone returns true if the count of the NewRefreshToken invocations corresponds
// the number of defined expectations
func (m *TokenManagerMock) MinimockNewRefreshTokenDone() bool {
	if m.NewRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewRefreshTokenMock.invocationsDone()
}

// MinimockNewRefreshTokenInspect logs each unmet expectation
func (m *TokenManagerMock) MinimockNewRefreshTokenInspect() {
	for _, e := range m.NewRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to TokenManagerMock.NewRefreshToken")
		}
	}

	afterNewRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterNewRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewRefreshTokenMock.defaultExpectation != nil && afterNewRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenManagerMock.NewRefreshToken at\n%s", m.NewRefreshTokenMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewRefreshToken != nil && afterNewRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenManagerMock.NewRefreshToken at\n%s", m.funcNewRefreshTokenOrigin)
	}

	if !m.NewRefreshTokenMock.invocationsDone() && afterNewRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenManagerMock.NewRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewRefreshTokenMock.expectedInvocations), m.NewRefreshTokenMock.expectedInvocationsOrigin, afterNewRefreshTokenCounter)
	}
}

type mTokenManagerMockValidateToken struct {
	optional           bool
	mock               *TokenManagerMock
	defaultExpectation *TokenManagerMockValidateTokenExpectation
	expectations       []*TokenManagerMockValidateTokenExpectation

	callArgs []*TokenManagerMockValidateTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenManagerMockValidateTokenExpectation specifies expectation struct of the TokenManager.ValidateToken
type TokenManagerMockValidateTokenExpectation struct {
	mock               *TokenManagerMock
	params             *TokenManagerMockValidateTokenParams
	paramPtrs          *TokenManagerMockValidateTokenParamPtrs
	expectationOrigins TokenManagerMockValidateTokenExpectationOrigins
	results            *TokenManagerMockValidateTokenResults
	returnOrigin       string
	Counter            uint64
}

// TokenManagerMockValidateTokenParams contains parameters of the TokenManager.ValidateToken
type TokenManagerMockValidateTokenParams struct {
	token string
}

// TokenManagerMockValidateTokenParamPtrs contains pointers to parameters of the TokenManager.ValidateToken
type TokenManagerMockValidateTokenParamPtrs struct {
	token *string
}

// TokenManagerMockValidateTokenResults contains results of the TokenManager.ValidateToken
type TokenManagerMockValidateTokenResults struct {
	i1  int64
	i2  int64
	err error
}

// TokenManagerMockValidateTokenOrigins contains origins of expectations of the TokenManager.ValidateToken
type TokenManagerMockValidateTokenExpectationOrigins struct {
	origin      string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidateToken *mTokenManagerMockValidateToken) Optional() *mTokenManagerMockValidateToken {
	mmValidateToken.optional = true
	return mmValidateToken
}

// Expect sets up expected params for TokenManager.ValidateToken
func (mmValidateToken *mTokenManagerMockValidateToken) Expect(token string) *mTokenManagerMockValidateToken {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("TokenManagerMock.ValidateToken mock is already set by Set")
	}

	if mmValidateToken.defaultExpectation == nil {
		mmValidateToken.defaultExpectation = &TokenManagerMockValidateTokenExpectation{}
	}

	if mmValidateToken.defaultExpectation.paramPtrs != nil {
		mmValidateToken.mock.t.Fatalf("TokenManagerMock.ValidateToken mock is already set by ExpectParams functions")
	}

	mmValidateToken.defaultExpectation.params = &TokenManagerMockValidateTokenParams{token}
	mmValidateToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValidateToken.expectations {
		if minimock.Equal(e.params, mmValidateToken.defaultExpectation.params) {
			mmValidateToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidateToken.defaultExpectation.params)
		}
	}

	return mmValidateToken
}

// ExpectTokenParam1 sets up expected param token for TokenManager.ValidateToken
func (mmValidateToken *mTokenManagerMockValidateToken) ExpectTokenParam1(token string) *mTokenManagerMockValidateToken {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("TokenManagerMock.ValidateToken mock is already set by Set")
	}

	if mmValidateToken.defaultExpectation == nil {
		mmValidateToken.defaultExpectation = &TokenManagerMockValidateTokenExpectation{}
	}

	if mmValidateToken.defaultExpectation.params != nil {
		mmValidateToken.mock.t.Fatalf("TokenManagerMock.ValidateToken mock is already set by Expect")
	}

	if mmValidateToken.defaultExpectation.paramPtrs == nil {
		mmValidateToken.defaultExpectation.paramPtrs = &TokenManagerMockValidateTokenParamPtrs{}
	}
	mmValidateToken.defaultExpectation.paramPtrs.token = &token
	mmValidateToken.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmValidateToken
}

// Inspect accepts an inspector function that has same arguments as the TokenManager.ValidateToken
func (mmValidateToken *mTokenManagerMockValidateToken) Inspect(f func(token string)) *mTokenManagerMockValidateToken {
	if mmValidateToken.mock.inspectFuncValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("Inspect function is already set for TokenManagerMock.ValidateToken")
	}

	mmValidateToken.mock.inspectFuncValidateToken = f

	return mmValidateToken
}

// Return sets up results that will be returned by TokenManager.ValidateToken
func (mmValidateToken *mTokenManagerMockValidateToken) Return(i1 int64, i2 int64, err error) *TokenManagerMock {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("TokenManagerMock.ValidateToken mock is already set by Set")
	}

	if mmValidateToken.defaultExpectation == nil {
		mmValidateToken.defaultExpectation = &TokenManagerMockValidateTokenExpectation{mock: mmValidateToken.mock}
	}
	mmValidateToken.defaultExpectation.results = &TokenManagerMockValidateTokenResults{i1, i2, err}
	mmValidateToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValidateToken.mock
}

// Set uses given function f to mock the TokenManager.ValidateToken method
func (mmValidateToken *mTokenManagerMockValidateToken) Set(f func(token string) (i1 int64, i2 int64, err error)) *TokenManagerMock {
	if mmValidateToken.defaultExpectation != nil {
		mmValidateToken.mock.t.Fatalf("Default expectation is already set for the TokenManager.ValidateToken method")
	}

	if len(mmValidateToken.expectations) > 0 {
		mmValidateToken.mock.t.Fatalf("Some expectations are already set for the TokenManager.ValidateToken method")
	}

	mmValidateToken.mock.funcValidateToken = f
	mmValidateToken.mock.funcValidateTokenOrigin = minimock.CallerInfo(1)
	return mmValidateToken.mock
}

// When sets expectation for the TokenManager.ValidateToken which will trigger the result defined by the following
// Then helper
func (mmValidateToken *mTokenManagerMockValidateToken) When(token string) *TokenManagerMockValidateTokenExpectation {
	if mmValidateToken.mock.funcValidateToken != nil {
		mmValidateToken.mock.t.Fatalf("TokenManagerMock.ValidateToken mock is already set by Set")
	}

	expectation := &TokenManagerMockValidateTokenExpectation{
		mock:               mmValidateToken.mock,
		params:             &TokenManagerMockValidateTokenParams{token},
		expectationOrigins: TokenManagerMockValidateTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValidateToken.expectations = append(mmValidateToken.expectations, expectation)
	return expectation
}

// Then sets up TokenManager.ValidateToken return parameters for the expectation previously defined by the When method
func (e *TokenManagerMockValidateTokenExpectation) Then(i1 int64, i2 int64, err error) *TokenManagerMock {
	e.results = &TokenManagerMockValidateTokenResults{i1, i2, err}
	return e.mock
}

// Times sets number of times TokenManager.ValidateToken should be invoked
func (mmValidateToken *mTokenManagerMockValidateToken) Times(n uint64) *mTokenManagerMockValidateToken {
	if n == 0 {
		mmValidateToken.mock.t.Fatalf("Times of TokenManagerMock.ValidateToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidateToken.expectedInvocations, n)
	mmValidateToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValidateToken
}

func (mmValidateToken *mTokenManagerMockValidateToken) invocationsDone() bool {
	if len(mmValidateToken.expectations) == 0 && mmValidateToken.defaultExpectation == nil && mmValidateToken.mock.funcValidateToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidateToken.mock.afterValidateTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidateToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ValidateToken implements mm_auth.TokenManager
func (mmValidateToken *TokenManagerMock) ValidateToken(token string) (i1 int64, i2 int64, err error) {
	mm_atomic.AddUint64(&mmValidateToken.beforeValidateTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmValidateToken.afterValidateTokenCounter, 1)

	mmValidateToken.t.Helper()

	if mmValidateToken.inspectFuncValidateToken != nil {
		mmValidateToken.inspectFuncValidateToken(token)
	}

	mm_params := TokenManagerMockValidateTokenParams{token}

	// Record call args
	mmValidateToken.ValidateTokenMock.mutex.Lock()
	mmValidateToken.ValidateTokenMock.callArgs = append(mmValidateToken.ValidateTokenMock.callArgs, &mm_params)
	mmValidateToken.ValidateTokenMock.mutex.Unlock()

	for _, e := range mmValidateToken.ValidateTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.i2, e.results.err
		}
	}

	if mmValidateToken.ValidateTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidateToken.ValidateTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmValidateToken.ValidateTokenMock.defaultExpectation.params
		mm_want_ptrs := mmValidateToken.ValidateTokenMock.defaultExpectation.paramPtrs

		mm_got := TokenManagerMockValidateTokenParams{token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmValidateToken.t.Errorf("TokenManagerMock.ValidateToken got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateToken.ValidateTokenMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidateToken.t.Errorf("TokenManagerMock.ValidateToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValidateToken.ValidateTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidateToken.ValidateTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmValidateToken.t.Fatal("No results are set for the TokenManagerMock.ValidateToken")
		}
		return (*mm_results).i1, (*mm_results).i2, (*mm_results).err
	}
	if mmValidateToken.funcValidateToken != nil {
		return mmValidateToken.funcValidateToken(token)
	}
	mmValidateToken.t.Fatalf("Unexpected call to TokenManagerMock.ValidateToken. %v", token)
	return
}

// ValidateTokenAfterCounter returns a count of finished TokenManagerMock.ValidateToken invocations
func (mmValidateToken *TokenManagerMock) ValidateTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateToken.afterValidateTokenCounter)
}

// ValidateTokenBeforeCounter returns a count of TokenManagerMock.ValidateToken invocations
func (mmValidateToken *TokenManagerMock) ValidateTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateToken.beforeValidateTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenManagerMock.ValidateToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidateToken *mTokenManagerMockValidateToken) Calls() []*TokenManagerMockValidateTokenParams {
	mmValidateToken.mutex.RLock()

	argCopy := make([]*TokenManagerMockValidateTokenParams, len(mmValidateToken.callArgs))
	copy(argCopy, mmValidateToken.callArgs)

	mmValidateToken.mutex.RUnlock()

	return argCopy
}

// MinimockValidateTokenDone returns true if the count of the ValidateToken invocations corresponds
// the number of defined expectations
func (m *TokenManagerMock) MinimockValidateTokenDone() bool {
	if m.ValidateTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateTokenMock.invocationsDone()
}

// MinimockValidateTokenInspect logs each unmet expectation
func (m *TokenManagerMock) MinimockValidateTokenInspect() {
	for _, e := range m.ValidateTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenManagerMock.ValidateToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidateTokenCounter := mm_atomic.LoadUint64(&m.afterValidateTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateTokenMock.defaultExpectation != nil && afterValidateTokenCounter < 1 {
		if m.ValidateTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TokenManagerMock.ValidateToken at\n%s", m.ValidateTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TokenManagerMock.ValidateToken at\n%s with params: %#v", m.ValidateTokenMock.defaultExpectation.expectationOrigins.origin, *m.ValidateTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidateToken != nil && afterValidateTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenManagerMock.ValidateToken at\n%s", m.funcValidateTokenOrigin)
	}

	if !m.ValidateTokenMock.invocationsDone() && afterValidateTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenManagerMock.ValidateToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateTokenMock.expectedInvocations), m.ValidateTokenMock.expectedInvocationsOrigin, afterValidateTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TokenManagerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockNewAccessTokenInspect()

			m.MinimockNewRefreshTokenInspect()

			m.MinimockValidateTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TokenManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TokenManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockNewAccessTokenDone() &&
		m.MinimockNewRefreshTokenDone() &&
		m.MinimockValidateTokenDone()
}
