// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// KeyProviderMock implements mm_crypto.KeyProvider
type KeyProviderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcKeyForDecrypt          func(version int64) (ba1 []byte, err error)
	funcKeyForDecryptOrigin    string
	inspectFuncKeyForDecrypt   func(version int64)
	afterKeyForDecryptCounter  uint64
	beforeKeyForDecryptCounter uint64
	KeyForDecryptMock          mKeyProviderMockKeyForDecrypt

	funcKeyForEncrypt          func(version int64) (ba1 []byte, err error)
	funcKeyForEncryptOrigin    string
	inspectFuncKeyForEncrypt   func(version int64)
	afterKeyForEncryptCounter  uint64
	beforeKeyForEncryptCounter uint64
	KeyForEncryptMock          mKeyProviderMockKeyForEncrypt
}

// NewKeyProviderMock returns a mock for mm_crypto.KeyProvider
func NewKeyProviderMock(t minimock.Tester) *KeyProviderMock {
	m := &KeyProviderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.KeyForDecryptMock = mKeyProviderMockKeyForDecrypt{mock: m}
	m.KeyForDecryptMock.callArgs = []*KeyProviderMockKeyForDecryptParams{}

	m.KeyForEncryptMock = mKeyProviderMockKeyForEncrypt{mock: m}
	m.KeyForEncryptMock.callArgs = []*KeyProviderMockKeyForEncryptParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mKeyProviderMockKeyForDecrypt struct {
	optional           bool
	mock               *KeyProviderMock
	defaultExpectation *KeyProviderMockKeyForDecryptExpectation
	expectations       []*KeyProviderMockKeyForDecryptExpectation

	callArgs []*KeyProviderMockKeyForDecryptParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// KeyProviderMockKeyForDecryptExpectation specifies expectation struct of the KeyProvider.KeyForDecrypt
type KeyProviderMockKeyForDecryptExpectation struct {
	mock               *KeyProviderMock
	params             *KeyProviderMockKeyForDecryptParams
	paramPtrs          *KeyProviderMockKeyForDecryptParamPtrs
	expectationOrigins KeyProviderMockKeyForDecryptExpectationOrigins
	results            *KeyProviderMockKeyForDecryptResults
	returnOrigin       string
	Counter            uint64
}

// KeyProviderMockKeyForDecryptParams contains parameters of the KeyProvider.KeyForDecrypt
type KeyProviderMockKeyForDecryptParams struct {
	version int64
}

// KeyProviderMockKeyForDecryptParamPtrs contains pointers to parameters of the KeyProvider.KeyForDecrypt
type KeyProviderMockKeyForDecryptParamPtrs struct {
	version *int64
}

// KeyProviderMockKeyForDecryptResults contains results of the KeyProvider.KeyForDecrypt
type KeyProviderMockKeyForDecryptResults struct {
	ba1 []byte
	err error
}

// KeyProviderMockKeyForDecryptOrigins contains origins of expectations of the KeyProvider.KeyForDecrypt
type KeyProviderMockKeyForDecryptExpectationOrigins struct {
	origin        string
	originVersion string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Optional() *mKeyProviderMockKeyForDecrypt {
	mmKeyForDecrypt.optional = true
	return mmKeyForDecrypt
}

// Expect sets up expected params for KeyProvider.KeyForDecrypt
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Expect(version int64) *mKeyProviderMockKeyForDecrypt {
	if mmKeyForDecrypt.mock.funcKeyForDecrypt != nil {
		mmKeyForDecrypt.mock.t.Fatalf("KeyProviderMock.KeyForDecrypt mock is already set by Set")
	}

	if mmKeyForDecrypt.defaultExpectation == nil {
		mmKeyForDecrypt.defaultExpectation = &KeyProviderMockKeyForDecryptExpectation{}
	}

	if mmKeyForDecrypt.defaultExpectation.paramPtrs != nil {
		mmKeyForDecrypt.mock.t.Fatalf("KeyProviderMock.KeyForDecrypt mock is already set by ExpectParams functions")
	}

	mmKeyForDecrypt.defaultExpectation.params = &KeyProviderMockKeyForDecryptParams{version}
	mmKeyForDecrypt.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmKeyForDecrypt.expectations {
		if minimock.Equal(e.params, mmKeyForDecrypt.defaultExpectation.params) {
			mmKeyForDecrypt.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmKeyForDecrypt.defaultExpectation.params)
		}
	}

	return mmKeyForDecrypt
}

// ExpectVersionParam1 sets up expected param version for KeyProvider.KeyForDecrypt
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) ExpectVersionParam1(version int64) *mKeyProviderMockKeyForDecrypt {
	if mmKeyForDecrypt.mock.funcKeyForDecrypt != nil {
		mmKeyForDecrypt.mock.t.Fatalf("KeyProviderMock.KeyForDecrypt mock is already set by Set")
	}

	if mmKeyForDecrypt.defaultExpectation == nil {
		mmKeyForDecrypt.defaultExpectation = &KeyProviderMockKeyForDecryptExpectation{}
	}

	if mmKeyForDecrypt.defaultExpectation.params != nil {
		mmKeyForDecrypt.mock.t.Fatalf("KeyProviderMock.KeyForDecrypt mock is already set by Expect")
	}

	if mmKeyForDecrypt.defaultExpectation.paramPtrs == nil {
		mmKeyForDecrypt.defaultExpectation.paramPtrs = &KeyProviderMockKeyForDecryptParamPtrs{}
	}
	mmKeyForDecrypt.defaultExpectation.paramPtrs.version = &version
	mmKeyForDecrypt.defaultExpectation.expectationOrigins.originVersion = minimock.CallerInfo(1)

	return mmKeyForDecrypt
}

// Inspect accepts an inspector function that has same arguments as the KeyProvider.KeyForDecrypt
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Inspect(f func(version int64)) *mKeyProviderMockKeyForDecrypt {
	if mmKeyForDecrypt.mock.inspectFuncKeyForDecrypt != nil {
		mmKeyForDecrypt.mock.t.Fatalf("Inspect function is already set for KeyProviderMock.KeyForDecrypt")
	}

	mmKeyForDecrypt.mock.inspectFuncKeyForDecrypt = f

	return mmKeyForDecrypt
}

// Return sets up results that will be returned by KeyProvider.KeyForDecrypt
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Return(ba1 []byte, err error) *KeyProviderMock {
	if mmKeyForDecrypt.mock.funcKeyForDecrypt != nil {
		mmKeyForDecrypt.mock.t.Fatalf("KeyProviderMock.KeyForDecrypt mock is already set by Set")
	}

	if mmKeyForDecrypt.defaultExpectation == nil {
		mmKeyForDecrypt.defaultExpectation = &KeyProviderMockKeyForDecryptExpectation{mock: mmKeyForDecrypt.mock}
	}
	mmKeyForDecrypt.defaultExpectation.results = &KeyProviderMockKeyForDecryptResults{ba1, err}
	mmKeyForDecrypt.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmKeyForDecrypt.mock
}

// Set uses given function f to mock the KeyProvider.KeyForDecrypt method
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Set(f func(version int64) (ba1 []byte, err error)) *KeyProviderMock {
	if mmKeyForDecrypt.defaultExpectation != nil {
		mmKeyForDecrypt.mock.t.Fatalf("Default expectation is already set for the KeyProvider.KeyForDecrypt method")
	}

	if len(mmKeyForDecrypt.expectations) > 0 {
		mmKeyForDecrypt.mock.t.Fatalf("Some expectations are already set for the KeyProvider.KeyForDecrypt method")
	}

	mmKeyForDecrypt.mock.funcKeyForDecrypt = f
	mmKeyForDecrypt.mock.funcKeyForDecryptOrigin = minimock.CallerInfo(1)
	return mmKeyForDecrypt.mock
}

// When sets expectation for the KeyProvider.KeyForDecrypt which will trigger the result defined by the following
// Then helper
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) When(version int64) *KeyProviderMockKeyForDecryptExpectation {
	if mmKeyForDecrypt.mock.funcKeyForDecrypt != nil {
		mmKeyForDecrypt.mock.t.Fatalf("KeyProviderMock.KeyForDecrypt mock is already set by Set")
	}

	expectation := &KeyProviderMockKeyForDecryptExpectation{
		mock:               mmKeyForDecrypt.mock,
		params:             &KeyProviderMockKeyForDecryptParams{version},
		expectationOrigins: KeyProviderMockKeyForDecryptExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmKeyForDecrypt.expectations = append(mmKeyForDecrypt.expectations, expectation)
	return expectation
}

// Then sets up KeyProvider.KeyForDecrypt return parameters for the expectation previously defined by the When method
func (e *KeyProviderMockKeyForDecryptExpectation) Then(ba1 []byte, err error) *KeyProviderMock {
	e.results = &KeyProviderMockKeyForDecryptResults{ba1, err}
	return e.mock
}

// Times sets number of times KeyProvider.KeyForDecrypt should be invoked
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Times(n uint64) *mKeyProviderMockKeyForDecrypt {
	if n == 0 {
		mmKeyForDecrypt.mock.t.Fatalf("Times of KeyProviderMock.KeyForDecrypt mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmKeyForDecrypt.expectedInvocations, n)
	mmKeyForDecrypt.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmKeyForDecrypt
}

func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) invocationsDone() bool {
	if len(mmKeyForDecrypt.expectations) == 0 && mmKeyForDecrypt.defaultExpectation == nil && mmKeyForDecrypt.mock.funcKeyForDecrypt == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmKeyForDecrypt.mock.afterKeyForDecryptCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmKeyForDecrypt.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// KeyForDecrypt implements mm_crypto.KeyProvider
func (mmKeyForDecrypt *KeyProviderMock) KeyForDecrypt(version int64) (ba1 []byte, err error) {
	mm_atomic.AddUint64(&mmKeyForDecrypt.beforeKeyForDecryptCounter, 1)
	defer mm_atomic.AddUint64(&mmKeyForDecrypt.afterKeyForDecryptCounter, 1)

	mmKeyForDecrypt.t.Helper()

	if mmKeyForDecrypt.inspectFuncKeyForDecrypt != nil {
		mmKeyForDecrypt.inspectFuncKeyForDecrypt(version)
	}

	mm_params := KeyProviderMockKeyForDecryptParams{version}

	// Record call args
	mmKeyForDecrypt.KeyForDecryptMock.mutex.Lock()
	mmKeyForDecrypt.KeyForDecryptMock.callArgs = append(mmKeyForDecrypt.KeyForDecryptMock.callArgs, &mm_params)
	mmKeyForDecrypt.KeyForDecryptMock.mutex.Unlock()

	for _, e := range mmKeyForDecrypt.KeyForDecryptMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation.Counter, 1)
		mm_want := mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation.params
		mm_want_ptrs := mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation.paramPtrs

		mm_got := KeyProviderMockKeyForDecryptParams{version}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.version != nil && !minimock.Equal(*mm_want_ptrs.version, mm_got.version) {
				mmKeyForDecrypt.t.Errorf("KeyProviderMock.KeyForDecrypt got unexpected parameter version, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation.expectationOrigins.originVersion, *mm_want_ptrs.version, mm_got.version, minimock.Diff(*mm_want_ptrs.version, mm_got.version))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmKeyForDecrypt.t.Errorf("KeyProviderMock.KeyForDecrypt got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmKeyForDecrypt.KeyForDecryptMock.defaultExpectation.results
		if mm_results == nil {
			mmKeyForDecrypt.t.Fatal("No results are set for the KeyProviderMock.KeyForDecrypt")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmKeyForDecrypt.funcKeyForDecrypt != nil {
		return mmKeyForDecrypt.funcKeyForDecrypt(version)
	}
	mmKeyForDecrypt.t.Fatalf("Unexpected call to KeyProviderMock.KeyForDecrypt. %v", version)
	return
}

// KeyForDecryptAfterCounter returns a count of finished KeyProviderMock.KeyForDecrypt invocations
func (mmKeyForDecrypt *KeyProviderMock) KeyForDecryptAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmKeyForDecrypt.afterKeyForDecryptCounter)
}

// KeyForDecryptBeforeCounter returns a count of KeyProviderMock.KeyForDecrypt invocations
func (mmKeyForDecrypt *KeyProviderMock) KeyForDecryptBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmKeyForDecrypt.beforeKeyForDecryptCounter)
}

// Calls returns a list of arguments used in each call to KeyProviderMock.KeyForDecrypt.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmKeyForDecrypt *mKeyProviderMockKeyForDecrypt) Calls() []*KeyProviderMockKeyForDecryptParams {
	mmKeyForDecrypt.mutex.RLock()

	argCopy := make([]*KeyProviderMockKeyForDecryptParams, len(mmKeyForDecrypt.callArgs))
	copy(argCopy, mmKeyForDecrypt.callArgs)

	mmKeyForDecrypt.mutex.RUnlock()

	return argCopy
}

// MinimockKeyForDecryptDone returns true if the count of the KeyForDecrypt invocations corresponds
// the number of defined expectations
func (m *KeyProviderMock) MinimockKeyForDecryptDone() bool {
	if m.KeyForDecryptMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.KeyForDecryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.KeyForDecryptMock.invocationsDone()
}

// MinimockKeyForDecryptInspect logs each unmet expectation
func (m *KeyProviderMock) MinimockKeyForDecryptInspect() {
	for _, e := range m.KeyForDecryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to KeyProviderMock.KeyForDecrypt at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterKeyForDecryptCounter := mm_atomic.LoadUint64(&m.afterKeyForDecryptCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.KeyForDecryptMock.defaultExpectation != nil && afterKeyForDecryptCounter < 1 {
		if m.KeyForDecryptMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to KeyProviderMock.KeyForDecrypt at\n%s", m.KeyForDecryptMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to KeyProviderMock.KeyForDecrypt at\n%s with params: %#v", m.KeyForDecryptMock.defaultExpectation.expectationOrigins.origin, *m.KeyForDecryptMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcKeyForDecrypt != nil && afterKeyForDecryptCounter < 1 {
		m.t.Errorf("Expected call to KeyProviderMock.KeyForDecrypt at\n%s", m.funcKeyForDecryptOrigin)
	}

	if !m.KeyForDecryptMock.invocationsDone() && afterKeyForDecryptCounter > 0 {
		m.t.Errorf("Expected %d calls to KeyProviderMock.KeyForDecrypt at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.KeyForDecryptMock.expectedInvocations), m.KeyForDecryptMock.expectedInvocationsOrigin, afterKeyForDecryptCounter)
	}
}

type mKeyProviderMockKeyForEncrypt struct {
	optional           bool
	mock               *KeyProviderMock
	defaultExpectation *KeyProviderMockKeyForEncryptExpectation
	expectations       []*KeyProviderMockKeyForEncryptExpectation

	callArgs []*KeyProviderMockKeyForEncryptParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// KeyProviderMockKeyForEncryptExpectation specifies expectation struct of the KeyProvider.KeyForEncrypt
type KeyProviderMockKeyForEncryptExpectation struct {
	mock               *KeyProviderMock
	params             *KeyProviderMockKeyForEncryptParams
	paramPtrs          *KeyProviderMockKeyForEncryptParamPtrs
	expectationOrigins KeyProviderMockKeyForEncryptExpectationOrigins
	results            *KeyProviderMockKeyForEncryptResults
	returnOrigin       string
	Counter            uint64
}

// KeyProviderMockKeyForEncryptParams contains parameters of the KeyProvider.KeyForEncrypt
type KeyProviderMockKeyForEncryptParams struct {
	version int64
}

// KeyProviderMockKeyForEncryptParamPtrs contains pointers to parameters of the KeyProvider.KeyForEncrypt
type KeyProviderMockKeyForEncryptParamPtrs struct {
	version *int64
}

// KeyProviderMockKeyForEncryptResults contains results of the KeyProvider.KeyForEncrypt
type KeyProviderMockKeyForEncryptResults struct {
	ba1 []byte
	err error
}

// KeyProviderMockKeyForEncryptOrigins contains origins of expectations of the KeyProvider.KeyForEncrypt
type KeyProviderMockKeyForEncryptExpectationOrigins struct {
	origin        string
	originVersion string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Optional() *mKeyProviderMockKeyForEncrypt {
	mmKeyForEncrypt.optional = true
	return mmKeyForEncrypt
}

// Expect sets up expected params for KeyProvider.KeyForEncrypt
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Expect(version int64) *mKeyProviderMockKeyForEncrypt {
	if mmKeyForEncrypt.mock.funcKeyForEncrypt != nil {
		mmKeyForEncrypt.mock.t.Fatalf("KeyProviderMock.KeyForEncrypt mock is already set by Set")
	}

	if mmKeyForEncrypt.defaultExpectation == nil {
		mmKeyForEncrypt.defaultExpectation = &KeyProviderMockKeyForEncryptExpectation{}
	}

	if mmKeyForEncrypt.defaultExpectation.paramPtrs != nil {
		mmKeyForEncrypt.mock.t.Fatalf("KeyProviderMock.KeyForEncrypt mock is already set by ExpectParams functions")
	}

	mmKeyForEncrypt.defaultExpectation.params = &KeyProviderMockKeyForEncryptParams{version}
	mmKeyForEncrypt.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmKeyForEncrypt.expectations {
		if minimock.Equal(e.params, mmKeyForEncrypt.defaultExpectation.params) {
			mmKeyForEncrypt.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmKeyForEncrypt.defaultExpectation.params)
		}
	}

	return mmKeyForEncrypt
}

// ExpectVersionParam1 sets up expected param version for KeyProvider.KeyForEncrypt
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) ExpectVersionParam1(version int64) *mKeyProviderMockKeyForEncrypt {
	if mmKeyForEncrypt.mock.funcKeyForEncrypt != nil {
		mmKeyForEncrypt.mock.t.Fatalf("KeyProviderMock.KeyForEncrypt mock is already set by Set")
	}

	if mmKeyForEncrypt.defaultExpectation == nil {
		mmKeyForEncrypt.defaultExpectation = &KeyProviderMockKeyForEncryptExpectation{}
	}

	if mmKeyForEncrypt.defaultExpectation.params != nil {
		mmKeyForEncrypt.mock.t.Fatalf("KeyProviderMock.KeyForEncrypt mock is already set by Expect")
	}

	if mmKeyForEncrypt.defaultExpectation.paramPtrs == nil {
		mmKeyForEncrypt.defaultExpectation.paramPtrs = &KeyProviderMockKeyForEncryptParamPtrs{}
	}
	mmKeyForEncrypt.defaultExpectation.paramPtrs.version = &version
	mmKeyForEncrypt.defaultExpectation.expectationOrigins.originVersion = minimock.CallerInfo(1)

	return mmKeyForEncrypt
}

// Inspect accepts an inspector function that has same arguments as the KeyProvider.KeyForEncrypt
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Inspect(f func(version int64)) *mKeyProviderMockKeyForEncrypt {
	if mmKeyForEncrypt.mock.inspectFuncKeyForEncrypt != nil {
		mmKeyForEncrypt.mock.t.Fatalf("Inspect function is already set for KeyProviderMock.KeyForEncrypt")
	}

	mmKeyForEncrypt.mock.inspectFuncKeyForEncrypt = f

	return mmKeyForEncrypt
}

// Return sets up results that will be returned by KeyProvider.KeyForEncrypt
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Return(ba1 []byte, err error) *KeyProviderMock {
	if mmKeyForEncrypt.mock.funcKeyForEncrypt != nil {
		mmKeyForEncrypt.mock.t.Fatalf("KeyProviderMock.KeyForEncrypt mock is already set by Set")
	}

	if mmKeyForEncrypt.defaultExpectation == nil {
		mmKeyForEncrypt.defaultExpectation = &KeyProviderMockKeyForEncryptExpectation{mock: mmKeyForEncrypt.mock}
	}
	mmKeyForEncrypt.defaultExpectation.results = &KeyProviderMockKeyForEncryptResults{ba1, err}
	mmKeyForEncrypt.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmKeyForEncrypt.mock
}

// Set uses given function f to mock the KeyProvider.KeyForEncrypt method
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Set(f func(version int64) (ba1 []byte, err error)) *KeyProviderMock {
	if mmKeyForEncrypt.defaultExpectation != nil {
		mmKeyForEncrypt.mock.t.Fatalf("Default expectation is already set for the KeyProvider.KeyForEncrypt method")
	}

	if len(mmKeyForEncrypt.expectations) > 0 {
		mmKeyForEncrypt.mock.t.Fatalf("Some expectations are already set for the KeyProvider.KeyForEncrypt method")
	}

	mmKeyForEncrypt.mock.funcKeyForEncrypt = f
	mmKeyForEncrypt.mock.funcKeyForEncryptOrigin = minimock.CallerInfo(1)
	return mmKeyForEncrypt.mock
}

// When sets expectation for the KeyProvider.KeyForEncrypt which will trigger the result defined by the following
// Then helper
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) When(version int64) *KeyProviderMockKeyForEncryptExpectation {
	if mmKeyForEncrypt.mock.funcKeyForEncrypt != nil {
		mmKeyForEncrypt.mock.t.Fatalf("KeyProviderMock.KeyForEncrypt mock is already set by Set")
	}

	expectation := &KeyProviderMockKeyForEncryptExpectation{
		mock:               mmKeyForEncrypt.mock,
		params:             &KeyProviderMockKeyForEncryptParams{version},
		expectationOrigins: KeyProviderMockKeyForEncryptExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmKeyForEncrypt.expectations = append(mmKeyForEncrypt.expectations, expectation)
	return expectation
}

// Then sets up KeyProvider.KeyForEncrypt return parameters for the expectation previously defined by the When method
func (e *KeyProviderMockKeyForEncryptExpectation) Then(ba1 []byte, err error) *KeyProviderMock {
	e.results = &KeyProviderMockKeyForEncryptResults{ba1, err}
	return e.mock
}

// Times sets number of times KeyProvider.KeyForEncrypt should be invoked
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Times(n uint64) *mKeyProviderMockKeyForEncrypt {
	if n == 0 {
		mmKeyForEncrypt.mock.t.Fatalf("Times of KeyProviderMock.KeyForEncrypt mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmKeyForEncrypt.expectedInvocations, n)
	mmKeyForEncrypt.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmKeyForEncrypt
}

func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) invocationsDone() bool {
	if len(mmKeyForEncrypt.expectations) == 0 && mmKeyForEncrypt.defaultExpectation == nil && mmKeyForEncrypt.mock.funcKeyForEncrypt == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmKeyForEncrypt.mock.afterKeyForEncryptCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmKeyForEncrypt.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// KeyForEncrypt implements mm_crypto.KeyProvider
func (mmKeyForEncrypt *KeyProviderMock) KeyForEncrypt(version int64) (ba1 []byte, err error) {
	mm_atomic.AddUint64(&mmKeyForEncrypt.beforeKeyForEncryptCounter, 1)
	defer mm_atomic.AddUint64(&mmKeyForEncrypt.afterKeyForEncryptCounter, 1)

	mmKeyForEncrypt.t.Helper()

	if mmKeyForEncrypt.inspectFuncKeyForEncrypt != nil {
		mmKeyForEncrypt.inspectFuncKeyForEncrypt(version)
	}

	mm_params := KeyProviderMockKeyForEncryptParams{version}

	// Record call args
	mmKeyForEncrypt.KeyForEncryptMock.mutex.Lock()
	mmKeyForEncrypt.KeyForEncryptMock.callArgs = append(mmKeyForEncrypt.KeyForEncryptMock.callArgs, &mm_params)
	mmKeyForEncrypt.KeyForEncryptMock.mutex.Unlock()

	for _, e := range mmKeyForEncrypt.KeyForEncryptMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ba1, e.results.err
		}
	}

	if mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation.Counter, 1)
		mm_want := mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation.params
		mm_want_ptrs := mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation.paramPtrs

		mm_got := KeyProviderMockKeyForEncryptParams{version}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.version != nil && !minimock.Equal(*mm_want_ptrs.version, mm_got.version) {
				mmKeyForEncrypt.t.Errorf("KeyProviderMock.KeyForEncrypt got unexpected parameter version, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation.expectationOrigins.originVersion, *mm_want_ptrs.version, mm_got.version, minimock.Diff(*mm_want_ptrs.version, mm_got.version))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmKeyForEncrypt.t.Errorf("KeyProviderMock.KeyForEncrypt got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmKeyForEncrypt.KeyForEncryptMock.defaultExpectation.results
		if mm_results == nil {
			mmKeyForEncrypt.t.Fatal("No results are set for the KeyProviderMock.KeyForEncrypt")
		}
		return (*mm_results).ba1, (*mm_results).err
	}
	if mmKeyForEncrypt.funcKeyForEncrypt != nil {
		return mmKeyForEncrypt.funcKeyForEncrypt(version)
	}
	mmKeyForEncrypt.t.Fatalf("Unexpected call to KeyProviderMock.KeyForEncrypt. %v", version)
	return
}

// KeyForEncryptAfterCounter returns a count of finished KeyProviderMock.KeyForEncrypt invocations
func (mmKeyForEncrypt *KeyProviderMock) KeyForEncryptAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmKeyForEncrypt.afterKeyForEncryptCounter)
}

// KeyForEncryptBeforeCounter returns a count of KeyProviderMock.KeyForEncrypt invocations
func (mmKeyForEncrypt *KeyProviderMock) KeyForEncryptBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmKeyForEncrypt.beforeKeyForEncryptCounter)
}

// Calls returns a list of arguments used in each call to KeyProviderMock.KeyForEncrypt.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmKeyForEncrypt *mKeyProviderMockKeyForEncrypt) Calls() []*KeyProviderMockKeyForEncryptParams {
	mmKeyForEncrypt.mutex.RLock()

	argCopy := make([]*KeyProviderMockKeyForEncryptParams, len(mmKeyForEncrypt.callArgs))
	copy(argCopy, mmKeyForEncrypt.callArgs)

	mmKeyForEncrypt.mutex.RUnlock()

	return argCopy
}

// MinimockKeyForEncryptDone returns true if the count of the KeyForEncrypt invocations corresponds
// the number of defined expectations
func (m *KeyProviderMock) MinimockKeyForEncryptDone() bool {
	if m.KeyForEncryptMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.KeyForEncryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.KeyForEncryptMock.invocationsDone()
}

// MinimockKeyForEncryptInspect logs each unmet expectation
func (m *KeyProviderMock) MinimockKeyForEncryptInspect() {
	for _, e := range m.KeyForEncryptMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to KeyProviderMock.KeyForEncrypt at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterKeyForEncryptCounter := mm_atomic.LoadUint64(&m.afterKeyForEncryptCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.KeyForEncryptMock.defaultExpectation != nil && afterKeyForEncryptCounter < 1 {
		if m.KeyForEncryptMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to KeyProviderMock.KeyForEncrypt at\n%s", m.KeyForEncryptMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to KeyProviderMock.KeyForEncrypt at\n%s with params: %#v", m.KeyForEncryptMock.defaultExpectation.expectationOrigins.origin, *m.KeyForEncryptMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcKeyForEncrypt != nil && afterKeyForEncryptCounter < 1 {
		m.t.Errorf("Expected call to KeyProviderMock.KeyForEncrypt at\n%s", m.funcKeyForEncryptOrigin)
	}

	if !m.KeyForEncryptMock.invocationsDone() && afterKeyForEncryptCounter > 0 {
		m.t.Errorf("Expected %d calls to KeyProviderMock.KeyForEncrypt at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.KeyForEncryptMock.expectedInvocations), m.KeyForEncryptMock.expectedInvocationsOrigin, afterKeyForEncryptCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *KeyProviderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockKeyForDecryptInspect()

			m.MinimockKeyForEncryptInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *KeyProviderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *KeyProviderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockKeyForDecryptDone() &&
		m.MinimockKeyForEncryptDone()
}
