// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// SessionRepoMock implements mm_users.SessionRepo
type SessionRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateSession          func(session *models.Session) (err error)
	funcCreateSessionOrigin    string
	inspectFuncCreateSession   func(session *models.Session)
	afterCreateSessionCounter  uint64
	beforeCreateSessionCounter uint64
	CreateSessionMock          mSessionRepoMockCreateSession
}

// NewSessionRepoMock returns a mock for mm_users.SessionRepo
func NewSessionRepoMock(t minimock.Tester) *SessionRepoMock {
	m := &SessionRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateSessionMock = mSessionRepoMockCreateSession{mock: m}
	m.CreateSessionMock.callArgs = []*SessionRepoMockCreateSessionParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mSessionRepoMockCreateSession struct {
	optional           bool
	mock               *SessionRepoMock
	defaultExpectation *SessionRepoMockCreateSessionExpectation
	expectations       []*SessionRepoMockCreateSessionExpectation

	callArgs []*SessionRepoMockCreateSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// SessionRepoMockCreateSessionExpectation specifies expectation struct of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionExpectation struct {
	mock               *SessionRepoMock
	params             *SessionRepoMockCreateSessionParams
	paramPtrs          *SessionRepoMockCreateSessionParamPtrs
	expectationOrigins SessionRepoMockCreateSessionExpectationOrigins
	results            *SessionRepoMockCreateSessionResults
	returnOrigin       string
	Counter            uint64
}

// SessionRepoMockCreateSessionParams contains parameters of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionParams struct {
	session *models.Session
}

// SessionRepoMockCreateSessionParamPtrs contains pointers to parameters of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionParamPtrs struct {
	session **models.Session
}

// SessionRepoMockCreateSessionResults contains results of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionResults struct {
	err error
}

// SessionRepoMockCreateSessionOrigins contains origins of expectations of the SessionRepo.CreateSession
type SessionRepoMockCreateSessionExpectationOrigins struct {
	origin        string
	originSession string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateSession *mSessionRepoMockCreateSession) Optional() *mSessionRepoMockCreateSession {
	mmCreateSession.optional = true
	return mmCreateSession
}

// Expect sets up expected params for SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) Expect(session *models.Session) *mSessionRepoMockCreateSession {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	if mmCreateSession.defaultExpectation == nil {
		mmCreateSession.defaultExpectation = &SessionRepoMockCreateSessionExpectation{}
	}

	if mmCreateSession.defaultExpectation.paramPtrs != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by ExpectParams functions")
	}

	mmCreateSession.defaultExpectation.params = &SessionRepoMockCreateSessionParams{session}
	mmCreateSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateSession.expectations {
		if minimock.Equal(e.params, mmCreateSession.defaultExpectation.params) {
			mmCreateSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateSession.defaultExpectation.params)
		}
	}

	return mmCreateSession
}

// ExpectSessionParam1 sets up expected param session for SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) ExpectSessionParam1(session *models.Session) *mSessionRepoMockCreateSession {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	if mmCreateSession.defaultExpectation == nil {
		mmCreateSession.defaultExpectation = &SessionRepoMockCreateSessionExpectation{}
	}

	if mmCreateSession.defaultExpectation.params != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Expect")
	}

	if mmCreateSession.defaultExpectation.paramPtrs == nil {
		mmCreateSession.defaultExpectation.paramPtrs = &SessionRepoMockCreateSessionParamPtrs{}
	}
	mmCreateSession.defaultExpectation.paramPtrs.session = &session
	mmCreateSession.defaultExpectation.expectationOrigins.originSession = minimock.CallerInfo(1)

	return mmCreateSession
}

// Inspect accepts an inspector function that has same arguments as the SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) Inspect(f func(session *models.Session)) *mSessionRepoMockCreateSession {
	if mmCreateSession.mock.inspectFuncCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("Inspect function is already set for SessionRepoMock.CreateSession")
	}

	mmCreateSession.mock.inspectFuncCreateSession = f

	return mmCreateSession
}

// Return sets up results that will be returned by SessionRepo.CreateSession
func (mmCreateSession *mSessionRepoMockCreateSession) Return(err error) *SessionRepoMock {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	if mmCreateSession.defaultExpectation == nil {
		mmCreateSession.defaultExpectation = &SessionRepoMockCreateSessionExpectation{mock: mmCreateSession.mock}
	}
	mmCreateSession.defaultExpectation.results = &SessionRepoMockCreateSessionResults{err}
	mmCreateSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateSession.mock
}

// Set uses given function f to mock the SessionRepo.CreateSession method
func (mmCreateSession *mSessionRepoMockCreateSession) Set(f func(session *models.Session) (err error)) *SessionRepoMock {
	if mmCreateSession.defaultExpectation != nil {
		mmCreateSession.mock.t.Fatalf("Default expectation is already set for the SessionRepo.CreateSession method")
	}

	if len(mmCreateSession.expectations) > 0 {
		mmCreateSession.mock.t.Fatalf("Some expectations are already set for the SessionRepo.CreateSession method")
	}

	mmCreateSession.mock.funcCreateSession = f
	mmCreateSession.mock.funcCreateSessionOrigin = minimock.CallerInfo(1)
	return mmCreateSession.mock
}

// When sets expectation for the SessionRepo.CreateSession which will trigger the result defined by the following
// Then helper
func (mmCreateSession *mSessionRepoMockCreateSession) When(session *models.Session) *SessionRepoMockCreateSessionExpectation {
	if mmCreateSession.mock.funcCreateSession != nil {
		mmCreateSession.mock.t.Fatalf("SessionRepoMock.CreateSession mock is already set by Set")
	}

	expectation := &SessionRepoMockCreateSessionExpectation{
		mock:               mmCreateSession.mock,
		params:             &SessionRepoMockCreateSessionParams{session},
		expectationOrigins: SessionRepoMockCreateSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateSession.expectations = append(mmCreateSession.expectations, expectation)
	return expectation
}

// Then sets up SessionRepo.CreateSession return parameters for the expectation previously defined by the When method
func (e *SessionRepoMockCreateSessionExpectation) Then(err error) *SessionRepoMock {
	e.results = &SessionRepoMockCreateSessionResults{err}
	return e.mock
}

// Times sets number of times SessionRepo.CreateSession should be invoked
func (mmCreateSession *mSessionRepoMockCreateSession) Times(n uint64) *mSessionRepoMockCreateSession {
	if n == 0 {
		mmCreateSession.mock.t.Fatalf("Times of SessionRepoMock.CreateSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateSession.expectedInvocations, n)
	mmCreateSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateSession
}

func (mmCreateSession *mSessionRepoMockCreateSession) invocationsDone() bool {
	if len(mmCreateSession.expectations) == 0 && mmCreateSession.defaultExpectation == nil && mmCreateSession.mock.funcCreateSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateSession.mock.afterCreateSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateSession implements mm_users.SessionRepo
func (mmCreateSession *SessionRepoMock) CreateSession(session *models.Session) (err error) {
	mm_atomic.AddUint64(&mmCreateSession.beforeCreateSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateSession.afterCreateSessionCounter, 1)

	mmCreateSession.t.Helper()

	if mmCreateSession.inspectFuncCreateSession != nil {
		mmCreateSession.inspectFuncCreateSession(session)
	}

	mm_params := SessionRepoMockCreateSessionParams{session}

	// Record call args
	mmCreateSession.CreateSessionMock.mutex.Lock()
	mmCreateSession.CreateSessionMock.callArgs = append(mmCreateSession.CreateSessionMock.callArgs, &mm_params)
	mmCreateSession.CreateSessionMock.mutex.Unlock()

	for _, e := range mmCreateSession.CreateSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateSession.CreateSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateSession.CreateSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateSession.CreateSessionMock.defaultExpectation.params
		mm_want_ptrs := mmCreateSession.CreateSessionMock.defaultExpectation.paramPtrs

		mm_got := SessionRepoMockCreateSessionParams{session}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.session != nil && !minimock.Equal(*mm_want_ptrs.session, mm_got.session) {
				mmCreateSession.t.Errorf("SessionRepoMock.CreateSession got unexpected parameter session, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateSession.CreateSessionMock.defaultExpectation.expectationOrigins.originSession, *mm_want_ptrs.session, mm_got.session, minimock.Diff(*mm_want_ptrs.session, mm_got.session))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateSession.t.Errorf("SessionRepoMock.CreateSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateSession.CreateSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateSession.CreateSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateSession.t.Fatal("No results are set for the SessionRepoMock.CreateSession")
		}
		return (*mm_results).err
	}
	if mmCreateSession.funcCreateSession != nil {
		return mmCreateSession.funcCreateSession(session)
	}
	mmCreateSession.t.Fatalf("Unexpected call to SessionRepoMock.CreateSession. %v", session)
	return
}

// CreateSessionAfterCounter returns a count of finished SessionRepoMock.CreateSession invocations
func (mmCreateSession *SessionRepoMock) CreateSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateSession.afterCreateSessionCounter)
}

// CreateSessionBeforeCounter returns a count of SessionRepoMock.CreateSession invocations
func (mmCreateSession *SessionRepoMock) CreateSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateSession.beforeCreateSessionCounter)
}

// Calls returns a list of arguments used in each call to SessionRepoMock.CreateSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateSession *mSessionRepoMockCreateSession) Calls() []*SessionRepoMockCreateSessionParams {
	mmCreateSession.mutex.RLock()

	argCopy := make([]*SessionRepoMockCreateSessionParams, len(mmCreateSession.callArgs))
	copy(argCopy, mmCreateSession.callArgs)

	mmCreateSession.mutex.RUnlock()

	return argCopy
}

// MinimockCreateSessionDone returns true if the count of the CreateSession invocations corresponds
// the number of defined expectations
func (m *SessionRepoMock) MinimockCreateSessionDone() bool {
	if m.CreateSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateSessionMock.invocationsDone()
}

// MinimockCreateSessionInspect logs each unmet expectation
func (m *SessionRepoMock) MinimockCreateSessionInspect() {
	for _, e := range m.CreateSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateSessionCounter := mm_atomic.LoadUint64(&m.afterCreateSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateSessionMock.defaultExpectation != nil && afterCreateSessionCounter < 1 {
		if m.CreateSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s", m.CreateSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s with params: %#v", m.CreateSessionMock.defaultExpectation.expectationOrigins.origin, *m.CreateSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateSession != nil && afterCreateSessionCounter < 1 {
		m.t.Errorf("Expected call to SessionRepoMock.CreateSession at\n%s", m.funcCreateSessionOrigin)
	}

	if !m.CreateSessionMock.invocationsDone() && afterCreateSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to SessionRepoMock.CreateSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateSessionMock.expectedInvocations), m.CreateSessionMock.expectedInvocationsOrigin, afterCreateSessionCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *SessionRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateSessionInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *SessionRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *SessionRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateSessionDone()
}
