// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TokenGeneratorMock implements mm_users.TokenGenerator
type TokenGeneratorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcNewAccessToken          func(userID int64) (s1 string, err error)
	funcNewAccessTokenOrigin    string
	inspectFuncNewAccessToken   func(userID int64)
	afterNewAccessTokenCounter  uint64
	beforeNewAccessTokenCounter uint64
	NewAccessTokenMock          mTokenGeneratorMockNewAccessToken

	funcNewRefreshToken          func() (s1 string, err error)
	funcNewRefreshTokenOrigin    string
	inspectFuncNewRefreshToken   func()
	afterNewRefreshTokenCounter  uint64
	beforeNewRefreshTokenCounter uint64
	NewRefreshTokenMock          mTokenGeneratorMockNewRefreshToken
}

// NewTokenGeneratorMock returns a mock for mm_users.TokenGenerator
func NewTokenGeneratorMock(t minimock.Tester) *TokenGeneratorMock {
	m := &TokenGeneratorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.NewAccessTokenMock = mTokenGeneratorMockNewAccessToken{mock: m}
	m.NewAccessTokenMock.callArgs = []*TokenGeneratorMockNewAccessTokenParams{}

	m.NewRefreshTokenMock = mTokenGeneratorMockNewRefreshToken{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTokenGeneratorMockNewAccessToken struct {
	optional           bool
	mock               *TokenGeneratorMock
	defaultExpectation *TokenGeneratorMockNewAccessTokenExpectation
	expectations       []*TokenGeneratorMockNewAccessTokenExpectation

	callArgs []*TokenGeneratorMockNewAccessTokenParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenGeneratorMockNewAccessTokenExpectation specifies expectation struct of the TokenGenerator.NewAccessToken
type TokenGeneratorMockNewAccessTokenExpectation struct {
	mock               *TokenGeneratorMock
	params             *TokenGeneratorMockNewAccessTokenParams
	paramPtrs          *TokenGeneratorMockNewAccessTokenParamPtrs
	expectationOrigins TokenGeneratorMockNewAccessTokenExpectationOrigins
	results            *TokenGeneratorMockNewAccessTokenResults
	returnOrigin       string
	Counter            uint64
}

// TokenGeneratorMockNewAccessTokenParams contains parameters of the TokenGenerator.NewAccessToken
type TokenGeneratorMockNewAccessTokenParams struct {
	userID int64
}

// TokenGeneratorMockNewAccessTokenParamPtrs contains pointers to parameters of the TokenGenerator.NewAccessToken
type TokenGeneratorMockNewAccessTokenParamPtrs struct {
	userID *int64
}

// TokenGeneratorMockNewAccessTokenResults contains results of the TokenGenerator.NewAccessToken
type TokenGeneratorMockNewAccessTokenResults struct {
	s1  string
	err error
}

// TokenGeneratorMockNewAccessTokenOrigins contains origins of expectations of the TokenGenerator.NewAccessToken
type TokenGeneratorMockNewAccessTokenExpectationOrigins struct {
	origin       string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Optional() *mTokenGeneratorMockNewAccessToken {
	mmNewAccessToken.optional = true
	return mmNewAccessToken
}

// Expect sets up expected params for TokenGenerator.NewAccessToken
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Expect(userID int64) *mTokenGeneratorMockNewAccessToken {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenGeneratorMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenGeneratorMockNewAccessTokenExpectation{}
	}

	if mmNewAccessToken.defaultExpectation.paramPtrs != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenGeneratorMock.NewAccessToken mock is already set by ExpectParams functions")
	}

	mmNewAccessToken.defaultExpectation.params = &TokenGeneratorMockNewAccessTokenParams{userID}
	mmNewAccessToken.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmNewAccessToken.expectations {
		if minimock.Equal(e.params, mmNewAccessToken.defaultExpectation.params) {
			mmNewAccessToken.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmNewAccessToken.defaultExpectation.params)
		}
	}

	return mmNewAccessToken
}

// ExpectUserIDParam1 sets up expected param userID for TokenGenerator.NewAccessToken
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) ExpectUserIDParam1(userID int64) *mTokenGeneratorMockNewAccessToken {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenGeneratorMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenGeneratorMockNewAccessTokenExpectation{}
	}

	if mmNewAccessToken.defaultExpectation.params != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenGeneratorMock.NewAccessToken mock is already set by Expect")
	}

	if mmNewAccessToken.defaultExpectation.paramPtrs == nil {
		mmNewAccessToken.defaultExpectation.paramPtrs = &TokenGeneratorMockNewAccessTokenParamPtrs{}
	}
	mmNewAccessToken.defaultExpectation.paramPtrs.userID = &userID
	mmNewAccessToken.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmNewAccessToken
}

// Inspect accepts an inspector function that has same arguments as the TokenGenerator.NewAccessToken
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Inspect(f func(userID int64)) *mTokenGeneratorMockNewAccessToken {
	if mmNewAccessToken.mock.inspectFuncNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("Inspect function is already set for TokenGeneratorMock.NewAccessToken")
	}

	mmNewAccessToken.mock.inspectFuncNewAccessToken = f

	return mmNewAccessToken
}

// Return sets up results that will be returned by TokenGenerator.NewAccessToken
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Return(s1 string, err error) *TokenGeneratorMock {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenGeneratorMock.NewAccessToken mock is already set by Set")
	}

	if mmNewAccessToken.defaultExpectation == nil {
		mmNewAccessToken.defaultExpectation = &TokenGeneratorMockNewAccessTokenExpectation{mock: mmNewAccessToken.mock}
	}
	mmNewAccessToken.defaultExpectation.results = &TokenGeneratorMockNewAccessTokenResults{s1, err}
	mmNewAccessToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewAccessToken.mock
}

// Set uses given function f to mock the TokenGenerator.NewAccessToken method
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Set(f func(userID int64) (s1 string, err error)) *TokenGeneratorMock {
	if mmNewAccessToken.defaultExpectation != nil {
		mmNewAccessToken.mock.t.Fatalf("Default expectation is already set for the TokenGenerator.NewAccessToken method")
	}

	if len(mmNewAccessToken.expectations) > 0 {
		mmNewAccessToken.mock.t.Fatalf("Some expectations are already set for the TokenGenerator.NewAccessToken method")
	}

	mmNewAccessToken.mock.funcNewAccessToken = f
	mmNewAccessToken.mock.funcNewAccessTokenOrigin = minimock.CallerInfo(1)
	return mmNewAccessToken.mock
}

// When sets expectation for the TokenGenerator.NewAccessToken which will trigger the result defined by the following
// Then helper
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) When(userID int64) *TokenGeneratorMockNewAccessTokenExpectation {
	if mmNewAccessToken.mock.funcNewAccessToken != nil {
		mmNewAccessToken.mock.t.Fatalf("TokenGeneratorMock.NewAccessToken mock is already set by Set")
	}

	expectation := &TokenGeneratorMockNewAccessTokenExpectation{
		mock:               mmNewAccessToken.mock,
		params:             &TokenGeneratorMockNewAccessTokenParams{userID},
		expectationOrigins: TokenGeneratorMockNewAccessTokenExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmNewAccessToken.expectations = append(mmNewAccessToken.expectations, expectation)
	return expectation
}

// Then sets up TokenGenerator.NewAccessToken return parameters for the expectation previously defined by the When method
func (e *TokenGeneratorMockNewAccessTokenExpectation) Then(s1 string, err error) *TokenGeneratorMock {
	e.results = &TokenGeneratorMockNewAccessTokenResults{s1, err}
	return e.mock
}

// Times sets number of times TokenGenerator.NewAccessToken should be invoked
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Times(n uint64) *mTokenGeneratorMockNewAccessToken {
	if n == 0 {
		mmNewAccessToken.mock.t.Fatalf("Times of TokenGeneratorMock.NewAccessToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewAccessToken.expectedInvocations, n)
	mmNewAccessToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewAccessToken
}

func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) invocationsDone() bool {
	if len(mmNewAccessToken.expectations) == 0 && mmNewAccessToken.defaultExpectation == nil && mmNewAccessToken.mock.funcNewAccessToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewAccessToken.mock.afterNewAccessTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewAccessToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewAccessToken implements mm_users.TokenGenerator
func (mmNewAccessToken *TokenGeneratorMock) NewAccessToken(userID int64) (s1 string, err error) {
	mm_atomic.AddUint64(&mmNewAccessToken.beforeNewAccessTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmNewAccessToken.afterNewAccessTokenCounter, 1)

	mmNewAccessToken.t.Helper()

	if mmNewAccessToken.inspectFuncNewAccessToken != nil {
		mmNewAccessToken.inspectFuncNewAccessToken(userID)
	}

	mm_params := TokenGeneratorMockNewAccessTokenParams{userID}

	// Record call args
	mmNewAccessToken.NewAccessTokenMock.mutex.Lock()
	mmNewAccessToken.NewAccessTokenMock.callArgs = append(mmNewAccessToken.NewAccessTokenMock.callArgs, &mm_params)
	mmNewAccessToken.NewAccessTokenMock.mutex.Unlock()

	for _, e := range mmNewAccessToken.NewAccessTokenMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmNewAccessToken.NewAccessTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewAccessToken.NewAccessTokenMock.defaultExpectation.Counter, 1)
		mm_want := mmNewAccessToken.NewAccessTokenMock.defaultExpectation.params
		mm_want_ptrs := mmNewAccessToken.NewAccessTokenMock.defaultExpectation.paramPtrs

		mm_got := TokenGeneratorMockNewAccessTokenParams{userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmNewAccessToken.t.Errorf("TokenGeneratorMock.NewAccessToken got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmNewAccessToken.NewAccessTokenMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmNewAccessToken.t.Errorf("TokenGeneratorMock.NewAccessToken got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmNewAccessToken.NewAccessTokenMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmNewAccessToken.NewAccessTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmNewAccessToken.t.Fatal("No results are set for the TokenGeneratorMock.NewAccessToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmNewAccessToken.funcNewAccessToken != nil {
		return mmNewAccessToken.funcNewAccessToken(userID)
	}
	mmNewAccessToken.t.Fatalf("Unexpected call to TokenGeneratorMock.NewAccessToken. %v", userID)
	return
}

// NewAccessTokenAfterCounter returns a count of finished TokenGeneratorMock.NewAccessToken invocations
func (mmNewAccessToken *TokenGeneratorMock) NewAccessTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewAccessToken.afterNewAccessTokenCounter)
}

// NewAccessTokenBeforeCounter returns a count of TokenGeneratorMock.NewAccessToken invocations
func (mmNewAccessToken *TokenGeneratorMock) NewAccessTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewAccessToken.beforeNewAccessTokenCounter)
}

// Calls returns a list of arguments used in each call to TokenGeneratorMock.NewAccessToken.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmNewAccessToken *mTokenGeneratorMockNewAccessToken) Calls() []*TokenGeneratorMockNewAccessTokenParams {
	mmNewAccessToken.mutex.RLock()

	argCopy := make([]*TokenGeneratorMockNewAccessTokenParams, len(mmNewAccessToken.callArgs))
	copy(argCopy, mmNewAccessToken.callArgs)

	mmNewAccessToken.mutex.RUnlock()

	return argCopy
}

// MinimockNewAccessTokenDone returns true if the count of the NewAccessToken invocations corresponds
// the number of defined expectations
func (m *TokenGeneratorMock) MinimockNewAccessTokenDone() bool {
	if m.NewAccessTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewAccessTokenMock.invocationsDone()
}

// MinimockNewAccessTokenInspect logs each unmet expectation
func (m *TokenGeneratorMock) MinimockNewAccessTokenInspect() {
	for _, e := range m.NewAccessTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenGeneratorMock.NewAccessToken at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterNewAccessTokenCounter := mm_atomic.LoadUint64(&m.afterNewAccessTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewAccessTokenMock.defaultExpectation != nil && afterNewAccessTokenCounter < 1 {
		if m.NewAccessTokenMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TokenGeneratorMock.NewAccessToken at\n%s", m.NewAccessTokenMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TokenGeneratorMock.NewAccessToken at\n%s with params: %#v", m.NewAccessTokenMock.defaultExpectation.expectationOrigins.origin, *m.NewAccessTokenMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewAccessToken != nil && afterNewAccessTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenGeneratorMock.NewAccessToken at\n%s", m.funcNewAccessTokenOrigin)
	}

	if !m.NewAccessTokenMock.invocationsDone() && afterNewAccessTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenGeneratorMock.NewAccessToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewAccessTokenMock.expectedInvocations), m.NewAccessTokenMock.expectedInvocationsOrigin, afterNewAccessTokenCounter)
	}
}

type mTokenGeneratorMockNewRefreshToken struct {
	optional           bool
	mock               *TokenGeneratorMock
	defaultExpectation *TokenGeneratorMockNewRefreshTokenExpectation
	expectations       []*TokenGeneratorMockNewRefreshTokenExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenGeneratorMockNewRefreshTokenExpectation specifies expectation struct of the TokenGenerator.NewRefreshToken
type TokenGeneratorMockNewRefreshTokenExpectation struct {
	mock *TokenGeneratorMock

	results      *TokenGeneratorMockNewRefreshTokenResults
	returnOrigin string
	Counter      uint64
}

// TokenGeneratorMockNewRefreshTokenResults contains results of the TokenGenerator.NewRefreshToken
type TokenGeneratorMockNewRefreshTokenResults struct {
	s1  string
	err error
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) Optional() *mTokenGeneratorMockNewRefreshToken {
	mmNewRefreshToken.optional = true
	return mmNewRefreshToken
}

// Expect sets up expected params for TokenGenerator.NewRefreshToken
func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) Expect() *mTokenGeneratorMockNewRefreshToken {
	if mmNewRefreshToken.mock.funcNewRefreshToken != nil {
		mmNewRefreshToken.mock.t.Fatalf("TokenGeneratorMock.NewRefreshToken mock is already set by Set")
	}

	if mmNewRefreshToken.defaultExpectation == nil {
		mmNewRefreshToken.defaultExpectation = &TokenGeneratorMockNewRefreshTokenExpectation{}
	}

	return mmNewRefreshToken
}

// Inspect accepts an inspector function that has same arguments as the TokenGenerator.NewRefreshToken
func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) Inspect(f func()) *mTokenGeneratorMockNewRefreshToken {
	if mmNewRefreshToken.mock.inspectFuncNewRefreshToken != nil {
		mmNewRefreshToken.mock.t.Fatalf("Inspect function is already set for TokenGeneratorMock.NewRefreshToken")
	}

	mmNewRefreshToken.mock.inspectFuncNewRefreshToken = f

	return mmNewRefreshToken
}

// Return sets up results that will be returned by TokenGenerator.NewRefreshToken
func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) Return(s1 string, err error) *TokenGeneratorMock {
	if mmNewRefreshToken.mock.funcNewRefreshToken != nil {
		mmNewRefreshToken.mock.t.Fatalf("TokenGeneratorMock.NewRefreshToken mock is already set by Set")
	}

	if mmNewRefreshToken.defaultExpectation == nil {
		mmNewRefreshToken.defaultExpectation = &TokenGeneratorMockNewRefreshTokenExpectation{mock: mmNewRefreshToken.mock}
	}
	mmNewRefreshToken.defaultExpectation.results = &TokenGeneratorMockNewRefreshTokenResults{s1, err}
	mmNewRefreshToken.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmNewRefreshToken.mock
}

// Set uses given function f to mock the TokenGenerator.NewRefreshToken method
func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) Set(f func() (s1 string, err error)) *TokenGeneratorMock {
	if mmNewRefreshToken.defaultExpectation != nil {
		mmNewRefreshToken.mock.t.Fatalf("Default expectation is already set for the TokenGenerator.NewRefreshToken method")
	}

	if len(mmNewRefreshToken.expectations) > 0 {
		mmNewRefreshToken.mock.t.Fatalf("Some expectations are already set for the TokenGenerator.NewRefreshToken method")
	}

	mmNewRefreshToken.mock.funcNewRefreshToken = f
	mmNewRefreshToken.mock.funcNewRefreshTokenOrigin = minimock.CallerInfo(1)
	return mmNewRefreshToken.mock
}

// Times sets number of times TokenGenerator.NewRefreshToken should be invoked
func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) Times(n uint64) *mTokenGeneratorMockNewRefreshToken {
	if n == 0 {
		mmNewRefreshToken.mock.t.Fatalf("Times of TokenGeneratorMock.NewRefreshToken mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmNewRefreshToken.expectedInvocations, n)
	mmNewRefreshToken.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmNewRefreshToken
}

func (mmNewRefreshToken *mTokenGeneratorMockNewRefreshToken) invocationsDone() bool {
	if len(mmNewRefreshToken.expectations) == 0 && mmNewRefreshToken.defaultExpectation == nil && mmNewRefreshToken.mock.funcNewRefreshToken == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmNewRefreshToken.mock.afterNewRefreshTokenCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmNewRefreshToken.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// NewRefreshToken implements mm_users.TokenGenerator
func (mmNewRefreshToken *TokenGeneratorMock) NewRefreshToken() (s1 string, err error) {
	mm_atomic.AddUint64(&mmNewRefreshToken.beforeNewRefreshTokenCounter, 1)
	defer mm_atomic.AddUint64(&mmNewRefreshToken.afterNewRefreshTokenCounter, 1)

	mmNewRefreshToken.t.Helper()

	if mmNewRefreshToken.inspectFuncNewRefreshToken != nil {
		mmNewRefreshToken.inspectFuncNewRefreshToken()
	}

	if mmNewRefreshToken.NewRefreshTokenMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmNewRefreshToken.NewRefreshTokenMock.defaultExpectation.Counter, 1)

		mm_results := mmNewRefreshToken.NewRefreshTokenMock.defaultExpectation.results
		if mm_results == nil {
			mmNewRefreshToken.t.Fatal("No results are set for the TokenGeneratorMock.NewRefreshToken")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmNewRefreshToken.funcNewRefreshToken != nil {
		return mmNewRefreshToken.funcNewRefreshToken()
	}
	mmNewRefreshToken.t.Fatalf("Unexpected call to TokenGeneratorMock.NewRefreshToken.")
	return
}

// NewRefreshTokenAfterCounter returns a count of finished TokenGeneratorMock.NewRefreshToken invocations
func (mmNewRefreshToken *TokenGeneratorMock) NewRefreshTokenAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewRefreshToken.afterNewRefreshTokenCounter)
}

// NewRefreshTokenBeforeCounter returns a count of TokenGeneratorMock.NewRefreshToken invocations
func (mmNewRefreshToken *TokenGeneratorMock) NewRefreshTokenBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmNewRefreshToken.beforeNewRefreshTokenCounter)
}

// MinimockNewRefreshTokenDone returns true if the count of the NewRefreshToken invocations corresponds
// the number of defined expectations
func (m *TokenGeneratorMock) MinimockNewRefreshTokenDone() bool {
	if m.NewRefreshTokenMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NewRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NewRefreshTokenMock.invocationsDone()
}

// MinimockNewRefreshTokenInspect logs each unmet expectation
func (m *TokenGeneratorMock) MinimockNewRefreshTokenInspect() {
	for _, e := range m.NewRefreshTokenMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to TokenGeneratorMock.NewRefreshToken")
		}
	}

	afterNewRefreshTokenCounter := mm_atomic.LoadUint64(&m.afterNewRefreshTokenCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NewRefreshTokenMock.defaultExpectation != nil && afterNewRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenGeneratorMock.NewRefreshToken at\n%s", m.NewRefreshTokenMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcNewRefreshToken != nil && afterNewRefreshTokenCounter < 1 {
		m.t.Errorf("Expected call to TokenGeneratorMock.NewRefreshToken at\n%s", m.funcNewRefreshTokenOrigin)
	}

	if !m.NewRefreshTokenMock.invocationsDone() && afterNewRefreshTokenCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenGeneratorMock.NewRefreshToken at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NewRefreshTokenMock.expectedInvocations), m.NewRefreshTokenMock.expectedInvocationsOrigin, afterNewRefreshTokenCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TokenGeneratorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockNewAccessTokenInspect()

			m.MinimockNewRefreshTokenInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TokenGeneratorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TokenGeneratorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockNewAccessTokenDone() &&
		m.MinimockNewRefreshTokenDone()
}
