// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// RecordServiceMock implements mm_records_by_id_binary_v1_get.RecordService
type RecordServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetRecord          func(id int64) (rp1 *models.Record, err error)
	funcGetRecordOrigin    string
	inspectFuncGetRecord   func(id int64)
	afterGetRecordCounter  uint64
	beforeGetRecordCounter uint64
	GetRecordMock          mRecordServiceMockGetRecord
}

// NewRecordServiceMock returns a mock for mm_records_by_id_binary_v1_get.RecordService
func NewRecordServiceMock(t minimock.Tester) *RecordServiceMock {
	m := &RecordServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetRecordMock = mRecordServiceMockGetRecord{mock: m}
	m.GetRecordMock.callArgs = []*RecordServiceMockGetRecordParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRecordServiceMockGetRecord struct {
	optional           bool
	mock               *RecordServiceMock
	defaultExpectation *RecordServiceMockGetRecordExpectation
	expectations       []*RecordServiceMockGetRecordExpectation

	callArgs []*RecordServiceMockGetRecordParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RecordServiceMockGetRecordExpectation specifies expectation struct of the RecordService.GetRecord
type RecordServiceMockGetRecordExpectation struct {
	mock               *RecordServiceMock
	params             *RecordServiceMockGetRecordParams
	paramPtrs          *RecordServiceMockGetRecordParamPtrs
	expectationOrigins RecordServiceMockGetRecordExpectationOrigins
	results            *RecordServiceMockGetRecordResults
	returnOrigin       string
	Counter            uint64
}

// RecordServiceMockGetRecordParams contains parameters of the RecordService.GetRecord
type RecordServiceMockGetRecordParams struct {
	id int64
}

// RecordServiceMockGetRecordParamPtrs contains pointers to parameters of the RecordService.GetRecord
type RecordServiceMockGetRecordParamPtrs struct {
	id *int64
}

// RecordServiceMockGetRecordResults contains results of the RecordService.GetRecord
type RecordServiceMockGetRecordResults struct {
	rp1 *models.Record
	err error
}

// RecordServiceMockGetRecordOrigins contains origins of expectations of the RecordService.GetRecord
type RecordServiceMockGetRecordExpectationOrigins struct {
	origin   string
	originId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetRecord *mRecordServiceMockGetRecord) Optional() *mRecordServiceMockGetRecord {
	mmGetRecord.optional = true
	return mmGetRecord
}

// Expect sets up expected params for RecordService.GetRecord
func (mmGetRecord *mRecordServiceMockGetRecord) Expect(id int64) *mRecordServiceMockGetRecord {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("RecordServiceMock.GetRecord mock is already set by Set")
	}

	if mmGetRecord.defaultExpectation == nil {
		mmGetRecord.defaultExpectation = &RecordServiceMockGetRecordExpectation{}
	}

	if mmGetRecord.defaultExpectation.paramPtrs != nil {
		mmGetRecord.mock.t.Fatalf("RecordServiceMock.GetRecord mock is already set by ExpectParams functions")
	}

	mmGetRecord.defaultExpectation.params = &RecordServiceMockGetRecordParams{id}
	mmGetRecord.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetRecord.expectations {
		if minimock.Equal(e.params, mmGetRecord.defaultExpectation.params) {
			mmGetRecord.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetRecord.defaultExpectation.params)
		}
	}

	return mmGetRecord
}

// ExpectIdParam1 sets up expected param id for RecordService.GetRecord
func (mmGetRecord *mRecordServiceMockGetRecord) ExpectIdParam1(id int64) *mRecordServiceMockGetRecord {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("RecordServiceMock.GetRecord mock is already set by Set")
	}

	if mmGetRecord.defaultExpectation == nil {
		mmGetRecord.defaultExpectation = &RecordServiceMockGetRecordExpectation{}
	}

	if mmGetRecord.defaultExpectation.params != nil {
		mmGetRecord.mock.t.Fatalf("RecordServiceMock.GetRecord mock is already set by Expect")
	}

	if mmGetRecord.defaultExpectation.paramPtrs == nil {
		mmGetRecord.defaultExpectation.paramPtrs = &RecordServiceMockGetRecordParamPtrs{}
	}
	mmGetRecord.defaultExpectation.paramPtrs.id = &id
	mmGetRecord.defaultExpectation.expectationOrigins.originId = minimock.CallerInfo(1)

	return mmGetRecord
}

// Inspect accepts an inspector function that has same arguments as the RecordService.GetRecord
func (mmGetRecord *mRecordServiceMockGetRecord) Inspect(f func(id int64)) *mRecordServiceMockGetRecord {
	if mmGetRecord.mock.inspectFuncGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("Inspect function is already set for RecordServiceMock.GetRecord")
	}

	mmGetRecord.mock.inspectFuncGetRecord = f

	return mmGetRecord
}

// Return sets up results that will be returned by RecordService.GetRecord
func (mmGetRecord *mRecordServiceMockGetRecord) Return(rp1 *models.Record, err error) *RecordServiceMock {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("RecordServiceMock.GetRecord mock is already set by Set")
	}

	if mmGetRecord.defaultExpectation == nil {
		mmGetRecord.defaultExpectation = &RecordServiceMockGetRecordExpectation{mock: mmGetRecord.mock}
	}
	mmGetRecord.defaultExpectation.results = &RecordServiceMockGetRecordResults{rp1, err}
	mmGetRecord.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetRecord.mock
}

// Set uses given function f to mock the RecordService.GetRecord method
func (mmGetRecord *mRecordServiceMockGetRecord) Set(f func(id int64) (rp1 *models.Record, err error)) *RecordServiceMock {
	if mmGetRecord.defaultExpectation != nil {
		mmGetRecord.mock.t.Fatalf("Default expectation is already set for the RecordService.GetRecord method")
	}

	if len(mmGetRecord.expectations) > 0 {
		mmGetRecord.mock.t.Fatalf("Some expectations are already set for the RecordService.GetRecord method")
	}

	mmGetRecord.mock.funcGetRecord = f
	mmGetRecord.mock.funcGetRecordOrigin = minimock.CallerInfo(1)
	return mmGetRecord.mock
}

// When sets expectation for the RecordService.GetRecord which will trigger the result defined by the following
// Then helper
func (mmGetRecord *mRecordServiceMockGetRecord) When(id int64) *RecordServiceMockGetRecordExpectation {
	if mmGetRecord.mock.funcGetRecord != nil {
		mmGetRecord.mock.t.Fatalf("RecordServiceMock.GetRecord mock is already set by Set")
	}

	expectation := &RecordServiceMockGetRecordExpectation{
		mock:               mmGetRecord.mock,
		params:             &RecordServiceMockGetRecordParams{id},
		expectationOrigins: RecordServiceMockGetRecordExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetRecord.expectations = append(mmGetRecord.expectations, expectation)
	return expectation
}

// Then sets up RecordService.GetRecord return parameters for the expectation previously defined by the When method
func (e *RecordServiceMockGetRecordExpectation) Then(rp1 *models.Record, err error) *RecordServiceMock {
	e.results = &RecordServiceMockGetRecordResults{rp1, err}
	return e.mock
}

// Times sets number of times RecordService.GetRecord should be invoked
func (mmGetRecord *mRecordServiceMockGetRecord) Times(n uint64) *mRecordServiceMockGetRecord {
	if n == 0 {
		mmGetRecord.mock.t.Fatalf("Times of RecordServiceMock.GetRecord mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetRecord.expectedInvocations, n)
	mmGetRecord.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetRecord
}

func (mmGetRecord *mRecordServiceMockGetRecord) invocationsDone() bool {
	if len(mmGetRecord.expectations) == 0 && mmGetRecord.defaultExpectation == nil && mmGetRecord.mock.funcGetRecord == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetRecord.mock.afterGetRecordCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetRecord.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetRecord implements mm_records_by_id_binary_v1_get.RecordService
func (mmGetRecord *RecordServiceMock) GetRecord(id int64) (rp1 *models.Record, err error) {
	mm_atomic.AddUint64(&mmGetRecord.beforeGetRecordCounter, 1)
	defer mm_atomic.AddUint64(&mmGetRecord.afterGetRecordCounter, 1)

	mmGetRecord.t.Helper()

	if mmGetRecord.inspectFuncGetRecord != nil {
		mmGetRecord.inspectFuncGetRecord(id)
	}

	mm_params := RecordServiceMockGetRecordParams{id}

	// Record call args
	mmGetRecord.GetRecordMock.mutex.Lock()
	mmGetRecord.GetRecordMock.callArgs = append(mmGetRecord.GetRecordMock.callArgs, &mm_params)
	mmGetRecord.GetRecordMock.mutex.Unlock()

	for _, e := range mmGetRecord.GetRecordMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmGetRecord.GetRecordMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetRecord.GetRecordMock.defaultExpectation.Counter, 1)
		mm_want := mmGetRecord.GetRecordMock.defaultExpectation.params
		mm_want_ptrs := mmGetRecord.GetRecordMock.defaultExpectation.paramPtrs

		mm_got := RecordServiceMockGetRecordParams{id}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.id != nil && !minimock.Equal(*mm_want_ptrs.id, mm_got.id) {
				mmGetRecord.t.Errorf("RecordServiceMock.GetRecord got unexpected parameter id, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetRecord.GetRecordMock.defaultExpectation.expectationOrigins.originId, *mm_want_ptrs.id, mm_got.id, minimock.Diff(*mm_want_ptrs.id, mm_got.id))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetRecord.t.Errorf("RecordServiceMock.GetRecord got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetRecord.GetRecordMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetRecord.GetRecordMock.defaultExpectation.results
		if mm_results == nil {
			mmGetRecord.t.Fatal("No results are set for the RecordServiceMock.GetRecord")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmGetRecord.funcGetRecord != nil {
		return mmGetRecord.funcGetRecord(id)
	}
	mmGetRecord.t.Fatalf("Unexpected call to RecordServiceMock.GetRecord. %v", id)
	return
}

// GetRecordAfterCounter returns a count of finished RecordServiceMock.GetRecord invocations
func (mmGetRecord *RecordServiceMock) GetRecordAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRecord.afterGetRecordCounter)
}

// GetRecordBeforeCounter returns a count of RecordServiceMock.GetRecord invocations
func (mmGetRecord *RecordServiceMock) GetRecordBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetRecord.beforeGetRecordCounter)
}

// Calls returns a list of arguments used in each call to RecordServiceMock.GetRecord.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetRecord *mRecordServiceMockGetRecord) Calls() []*RecordServiceMockGetRecordParams {
	mmGetRecord.mutex.RLock()

	argCopy := make([]*RecordServiceMockGetRecordParams, len(mmGetRecord.callArgs))
	copy(argCopy, mmGetRecord.callArgs)

	mmGetRecord.mutex.RUnlock()

	return argCopy
}

// MinimockGetRecordDone returns true if the count of the GetRecord invocations corresponds
// the number of defined expectations
func (m *RecordServiceMock) MinimockGetRecordDone() bool {
	if m.GetRecordMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetRecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetRecordMock.invocationsDone()
}

// MinimockGetRecordInspect logs each unmet expectation
func (m *RecordServiceMock) MinimockGetRecordInspect() {
	for _, e := range m.GetRecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RecordServiceMock.GetRecord at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetRecordCounter := mm_atomic.LoadUint64(&m.afterGetRecordCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetRecordMock.defaultExpectation != nil && afterGetRecordCounter < 1 {
		if m.GetRecordMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RecordServiceMock.GetRecord at\n%s", m.GetRecordMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RecordServiceMock.GetRecord at\n%s with params: %#v", m.GetRecordMock.defaultExpectation.expectationOrigins.origin, *m.GetRecordMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetRecord != nil && afterGetRecordCounter < 1 {
		m.t.Errorf("Expected call to RecordServiceMock.GetRecord at\n%s", m.funcGetRecordOrigin)
	}

	if !m.GetRecordMock.invocationsDone() && afterGetRecordCounter > 0 {
		m.t.Errorf("Expected %d calls to RecordServiceMock.GetRecord at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetRecordMock.expectedInvocations), m.GetRecordMock.expectedInvocationsOrigin, afterGetRecordCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RecordServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetRecordInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RecordServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RecordServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetRecordDone()
}
