// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// UploadServiceMock implements mm_records_by_id_binary_v1_get.UploadService
type UploadServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcConfirmChunk          func(downloadID int64, chunkIndex int64) (confirmed int64, total int64, status models.DownloadStatus, err error)
	funcConfirmChunkOrigin    string
	inspectFuncConfirmChunk   func(downloadID int64, chunkIndex int64)
	afterConfirmChunkCounter  uint64
	beforeConfirmChunkCounter uint64
	ConfirmChunkMock          mUploadServiceMockConfirmChunk

	funcCreateDownloadSession          func(userID int64, recordID int64) (dp1 *models.DownloadSession, err error)
	funcCreateDownloadSessionOrigin    string
	inspectFuncCreateDownloadSession   func(userID int64, recordID int64)
	afterCreateDownloadSessionCounter  uint64
	beforeCreateDownloadSessionCounter uint64
	CreateDownloadSessionMock          mUploadServiceMockCreateDownloadSession

	funcDownloadChunkByID          func(downloadID int64, chunkIndex int64) (cp1 *models.Chunk, err error)
	funcDownloadChunkByIDOrigin    string
	inspectFuncDownloadChunkByID   func(downloadID int64, chunkIndex int64)
	afterDownloadChunkByIDCounter  uint64
	beforeDownloadChunkByIDCounter uint64
	DownloadChunkByIDMock          mUploadServiceMockDownloadChunkByID
}

// NewUploadServiceMock returns a mock for mm_records_by_id_binary_v1_get.UploadService
func NewUploadServiceMock(t minimock.Tester) *UploadServiceMock {
	m := &UploadServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ConfirmChunkMock = mUploadServiceMockConfirmChunk{mock: m}
	m.ConfirmChunkMock.callArgs = []*UploadServiceMockConfirmChunkParams{}

	m.CreateDownloadSessionMock = mUploadServiceMockCreateDownloadSession{mock: m}
	m.CreateDownloadSessionMock.callArgs = []*UploadServiceMockCreateDownloadSessionParams{}

	m.DownloadChunkByIDMock = mUploadServiceMockDownloadChunkByID{mock: m}
	m.DownloadChunkByIDMock.callArgs = []*UploadServiceMockDownloadChunkByIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUploadServiceMockConfirmChunk struct {
	optional           bool
	mock               *UploadServiceMock
	defaultExpectation *UploadServiceMockConfirmChunkExpectation
	expectations       []*UploadServiceMockConfirmChunkExpectation

	callArgs []*UploadServiceMockConfirmChunkParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UploadServiceMockConfirmChunkExpectation specifies expectation struct of the UploadService.ConfirmChunk
type UploadServiceMockConfirmChunkExpectation struct {
	mock               *UploadServiceMock
	params             *UploadServiceMockConfirmChunkParams
	paramPtrs          *UploadServiceMockConfirmChunkParamPtrs
	expectationOrigins UploadServiceMockConfirmChunkExpectationOrigins
	results            *UploadServiceMockConfirmChunkResults
	returnOrigin       string
	Counter            uint64
}

// UploadServiceMockConfirmChunkParams contains parameters of the UploadService.ConfirmChunk
type UploadServiceMockConfirmChunkParams struct {
	downloadID int64
	chunkIndex int64
}

// UploadServiceMockConfirmChunkParamPtrs contains pointers to parameters of the UploadService.ConfirmChunk
type UploadServiceMockConfirmChunkParamPtrs struct {
	downloadID *int64
	chunkIndex *int64
}

// UploadServiceMockConfirmChunkResults contains results of the UploadService.ConfirmChunk
type UploadServiceMockConfirmChunkResults struct {
	confirmed int64
	total     int64
	status    models.DownloadStatus
	err       error
}

// UploadServiceMockConfirmChunkOrigins contains origins of expectations of the UploadService.ConfirmChunk
type UploadServiceMockConfirmChunkExpectationOrigins struct {
	origin           string
	originDownloadID string
	originChunkIndex string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Optional() *mUploadServiceMockConfirmChunk {
	mmConfirmChunk.optional = true
	return mmConfirmChunk
}

// Expect sets up expected params for UploadService.ConfirmChunk
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Expect(downloadID int64, chunkIndex int64) *mUploadServiceMockConfirmChunk {
	if mmConfirmChunk.mock.funcConfirmChunk != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Set")
	}

	if mmConfirmChunk.defaultExpectation == nil {
		mmConfirmChunk.defaultExpectation = &UploadServiceMockConfirmChunkExpectation{}
	}

	if mmConfirmChunk.defaultExpectation.paramPtrs != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by ExpectParams functions")
	}

	mmConfirmChunk.defaultExpectation.params = &UploadServiceMockConfirmChunkParams{downloadID, chunkIndex}
	mmConfirmChunk.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmConfirmChunk.expectations {
		if minimock.Equal(e.params, mmConfirmChunk.defaultExpectation.params) {
			mmConfirmChunk.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmConfirmChunk.defaultExpectation.params)
		}
	}

	return mmConfirmChunk
}

// ExpectDownloadIDParam1 sets up expected param downloadID for UploadService.ConfirmChunk
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) ExpectDownloadIDParam1(downloadID int64) *mUploadServiceMockConfirmChunk {
	if mmConfirmChunk.mock.funcConfirmChunk != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Set")
	}

	if mmConfirmChunk.defaultExpectation == nil {
		mmConfirmChunk.defaultExpectation = &UploadServiceMockConfirmChunkExpectation{}
	}

	if mmConfirmChunk.defaultExpectation.params != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Expect")
	}

	if mmConfirmChunk.defaultExpectation.paramPtrs == nil {
		mmConfirmChunk.defaultExpectation.paramPtrs = &UploadServiceMockConfirmChunkParamPtrs{}
	}
	mmConfirmChunk.defaultExpectation.paramPtrs.downloadID = &downloadID
	mmConfirmChunk.defaultExpectation.expectationOrigins.originDownloadID = minimock.CallerInfo(1)

	return mmConfirmChunk
}

// ExpectChunkIndexParam2 sets up expected param chunkIndex for UploadService.ConfirmChunk
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) ExpectChunkIndexParam2(chunkIndex int64) *mUploadServiceMockConfirmChunk {
	if mmConfirmChunk.mock.funcConfirmChunk != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Set")
	}

	if mmConfirmChunk.defaultExpectation == nil {
		mmConfirmChunk.defaultExpectation = &UploadServiceMockConfirmChunkExpectation{}
	}

	if mmConfirmChunk.defaultExpectation.params != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Expect")
	}

	if mmConfirmChunk.defaultExpectation.paramPtrs == nil {
		mmConfirmChunk.defaultExpectation.paramPtrs = &UploadServiceMockConfirmChunkParamPtrs{}
	}
	mmConfirmChunk.defaultExpectation.paramPtrs.chunkIndex = &chunkIndex
	mmConfirmChunk.defaultExpectation.expectationOrigins.originChunkIndex = minimock.CallerInfo(1)

	return mmConfirmChunk
}

// Inspect accepts an inspector function that has same arguments as the UploadService.ConfirmChunk
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Inspect(f func(downloadID int64, chunkIndex int64)) *mUploadServiceMockConfirmChunk {
	if mmConfirmChunk.mock.inspectFuncConfirmChunk != nil {
		mmConfirmChunk.mock.t.Fatalf("Inspect function is already set for UploadServiceMock.ConfirmChunk")
	}

	mmConfirmChunk.mock.inspectFuncConfirmChunk = f

	return mmConfirmChunk
}

// Return sets up results that will be returned by UploadService.ConfirmChunk
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Return(confirmed int64, total int64, status models.DownloadStatus, err error) *UploadServiceMock {
	if mmConfirmChunk.mock.funcConfirmChunk != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Set")
	}

	if mmConfirmChunk.defaultExpectation == nil {
		mmConfirmChunk.defaultExpectation = &UploadServiceMockConfirmChunkExpectation{mock: mmConfirmChunk.mock}
	}
	mmConfirmChunk.defaultExpectation.results = &UploadServiceMockConfirmChunkResults{confirmed, total, status, err}
	mmConfirmChunk.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmConfirmChunk.mock
}

// Set uses given function f to mock the UploadService.ConfirmChunk method
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Set(f func(downloadID int64, chunkIndex int64) (confirmed int64, total int64, status models.DownloadStatus, err error)) *UploadServiceMock {
	if mmConfirmChunk.defaultExpectation != nil {
		mmConfirmChunk.mock.t.Fatalf("Default expectation is already set for the UploadService.ConfirmChunk method")
	}

	if len(mmConfirmChunk.expectations) > 0 {
		mmConfirmChunk.mock.t.Fatalf("Some expectations are already set for the UploadService.ConfirmChunk method")
	}

	mmConfirmChunk.mock.funcConfirmChunk = f
	mmConfirmChunk.mock.funcConfirmChunkOrigin = minimock.CallerInfo(1)
	return mmConfirmChunk.mock
}

// When sets expectation for the UploadService.ConfirmChunk which will trigger the result defined by the following
// Then helper
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) When(downloadID int64, chunkIndex int64) *UploadServiceMockConfirmChunkExpectation {
	if mmConfirmChunk.mock.funcConfirmChunk != nil {
		mmConfirmChunk.mock.t.Fatalf("UploadServiceMock.ConfirmChunk mock is already set by Set")
	}

	expectation := &UploadServiceMockConfirmChunkExpectation{
		mock:               mmConfirmChunk.mock,
		params:             &UploadServiceMockConfirmChunkParams{downloadID, chunkIndex},
		expectationOrigins: UploadServiceMockConfirmChunkExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmConfirmChunk.expectations = append(mmConfirmChunk.expectations, expectation)
	return expectation
}

// Then sets up UploadService.ConfirmChunk return parameters for the expectation previously defined by the When method
func (e *UploadServiceMockConfirmChunkExpectation) Then(confirmed int64, total int64, status models.DownloadStatus, err error) *UploadServiceMock {
	e.results = &UploadServiceMockConfirmChunkResults{confirmed, total, status, err}
	return e.mock
}

// Times sets number of times UploadService.ConfirmChunk should be invoked
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Times(n uint64) *mUploadServiceMockConfirmChunk {
	if n == 0 {
		mmConfirmChunk.mock.t.Fatalf("Times of UploadServiceMock.ConfirmChunk mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmConfirmChunk.expectedInvocations, n)
	mmConfirmChunk.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmConfirmChunk
}

func (mmConfirmChunk *mUploadServiceMockConfirmChunk) invocationsDone() bool {
	if len(mmConfirmChunk.expectations) == 0 && mmConfirmChunk.defaultExpectation == nil && mmConfirmChunk.mock.funcConfirmChunk == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmConfirmChunk.mock.afterConfirmChunkCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmConfirmChunk.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ConfirmChunk implements mm_records_by_id_binary_v1_get.UploadService
func (mmConfirmChunk *UploadServiceMock) ConfirmChunk(downloadID int64, chunkIndex int64) (confirmed int64, total int64, status models.DownloadStatus, err error) {
	mm_atomic.AddUint64(&mmConfirmChunk.beforeConfirmChunkCounter, 1)
	defer mm_atomic.AddUint64(&mmConfirmChunk.afterConfirmChunkCounter, 1)

	mmConfirmChunk.t.Helper()

	if mmConfirmChunk.inspectFuncConfirmChunk != nil {
		mmConfirmChunk.inspectFuncConfirmChunk(downloadID, chunkIndex)
	}

	mm_params := UploadServiceMockConfirmChunkParams{downloadID, chunkIndex}

	// Record call args
	mmConfirmChunk.ConfirmChunkMock.mutex.Lock()
	mmConfirmChunk.ConfirmChunkMock.callArgs = append(mmConfirmChunk.ConfirmChunkMock.callArgs, &mm_params)
	mmConfirmChunk.ConfirmChunkMock.mutex.Unlock()

	for _, e := range mmConfirmChunk.ConfirmChunkMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.confirmed, e.results.total, e.results.status, e.results.err
		}
	}

	if mmConfirmChunk.ConfirmChunkMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmConfirmChunk.ConfirmChunkMock.defaultExpectation.Counter, 1)
		mm_want := mmConfirmChunk.ConfirmChunkMock.defaultExpectation.params
		mm_want_ptrs := mmConfirmChunk.ConfirmChunkMock.defaultExpectation.paramPtrs

		mm_got := UploadServiceMockConfirmChunkParams{downloadID, chunkIndex}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.downloadID != nil && !minimock.Equal(*mm_want_ptrs.downloadID, mm_got.downloadID) {
				mmConfirmChunk.t.Errorf("UploadServiceMock.ConfirmChunk got unexpected parameter downloadID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmConfirmChunk.ConfirmChunkMock.defaultExpectation.expectationOrigins.originDownloadID, *mm_want_ptrs.downloadID, mm_got.downloadID, minimock.Diff(*mm_want_ptrs.downloadID, mm_got.downloadID))
			}

			if mm_want_ptrs.chunkIndex != nil && !minimock.Equal(*mm_want_ptrs.chunkIndex, mm_got.chunkIndex) {
				mmConfirmChunk.t.Errorf("UploadServiceMock.ConfirmChunk got unexpected parameter chunkIndex, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmConfirmChunk.ConfirmChunkMock.defaultExpectation.expectationOrigins.originChunkIndex, *mm_want_ptrs.chunkIndex, mm_got.chunkIndex, minimock.Diff(*mm_want_ptrs.chunkIndex, mm_got.chunkIndex))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmConfirmChunk.t.Errorf("UploadServiceMock.ConfirmChunk got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmConfirmChunk.ConfirmChunkMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmConfirmChunk.ConfirmChunkMock.defaultExpectation.results
		if mm_results == nil {
			mmConfirmChunk.t.Fatal("No results are set for the UploadServiceMock.ConfirmChunk")
		}
		return (*mm_results).confirmed, (*mm_results).total, (*mm_results).status, (*mm_results).err
	}
	if mmConfirmChunk.funcConfirmChunk != nil {
		return mmConfirmChunk.funcConfirmChunk(downloadID, chunkIndex)
	}
	mmConfirmChunk.t.Fatalf("Unexpected call to UploadServiceMock.ConfirmChunk. %v %v", downloadID, chunkIndex)
	return
}

// ConfirmChunkAfterCounter returns a count of finished UploadServiceMock.ConfirmChunk invocations
func (mmConfirmChunk *UploadServiceMock) ConfirmChunkAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmConfirmChunk.afterConfirmChunkCounter)
}

// ConfirmChunkBeforeCounter returns a count of UploadServiceMock.ConfirmChunk invocations
func (mmConfirmChunk *UploadServiceMock) ConfirmChunkBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmConfirmChunk.beforeConfirmChunkCounter)
}

// Calls returns a list of arguments used in each call to UploadServiceMock.ConfirmChunk.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmConfirmChunk *mUploadServiceMockConfirmChunk) Calls() []*UploadServiceMockConfirmChunkParams {
	mmConfirmChunk.mutex.RLock()

	argCopy := make([]*UploadServiceMockConfirmChunkParams, len(mmConfirmChunk.callArgs))
	copy(argCopy, mmConfirmChunk.callArgs)

	mmConfirmChunk.mutex.RUnlock()

	return argCopy
}

// MinimockConfirmChunkDone returns true if the count of the ConfirmChunk invocations corresponds
// the number of defined expectations
func (m *UploadServiceMock) MinimockConfirmChunkDone() bool {
	if m.ConfirmChunkMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ConfirmChunkMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ConfirmChunkMock.invocationsDone()
}

// MinimockConfirmChunkInspect logs each unmet expectation
func (m *UploadServiceMock) MinimockConfirmChunkInspect() {
	for _, e := range m.ConfirmChunkMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UploadServiceMock.ConfirmChunk at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterConfirmChunkCounter := mm_atomic.LoadUint64(&m.afterConfirmChunkCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ConfirmChunkMock.defaultExpectation != nil && afterConfirmChunkCounter < 1 {
		if m.ConfirmChunkMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UploadServiceMock.ConfirmChunk at\n%s", m.ConfirmChunkMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UploadServiceMock.ConfirmChunk at\n%s with params: %#v", m.ConfirmChunkMock.defaultExpectation.expectationOrigins.origin, *m.ConfirmChunkMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcConfirmChunk != nil && afterConfirmChunkCounter < 1 {
		m.t.Errorf("Expected call to UploadServiceMock.ConfirmChunk at\n%s", m.funcConfirmChunkOrigin)
	}

	if !m.ConfirmChunkMock.invocationsDone() && afterConfirmChunkCounter > 0 {
		m.t.Errorf("Expected %d calls to UploadServiceMock.ConfirmChunk at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ConfirmChunkMock.expectedInvocations), m.ConfirmChunkMock.expectedInvocationsOrigin, afterConfirmChunkCounter)
	}
}

type mUploadServiceMockCreateDownloadSession struct {
	optional           bool
	mock               *UploadServiceMock
	defaultExpectation *UploadServiceMockCreateDownloadSessionExpectation
	expectations       []*UploadServiceMockCreateDownloadSessionExpectation

	callArgs []*UploadServiceMockCreateDownloadSessionParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UploadServiceMockCreateDownloadSessionExpectation specifies expectation struct of the UploadService.CreateDownloadSession
type UploadServiceMockCreateDownloadSessionExpectation struct {
	mock               *UploadServiceMock
	params             *UploadServiceMockCreateDownloadSessionParams
	paramPtrs          *UploadServiceMockCreateDownloadSessionParamPtrs
	expectationOrigins UploadServiceMockCreateDownloadSessionExpectationOrigins
	results            *UploadServiceMockCreateDownloadSessionResults
	returnOrigin       string
	Counter            uint64
}

// UploadServiceMockCreateDownloadSessionParams contains parameters of the UploadService.CreateDownloadSession
type UploadServiceMockCreateDownloadSessionParams struct {
	userID   int64
	recordID int64
}

// UploadServiceMockCreateDownloadSessionParamPtrs contains pointers to parameters of the UploadService.CreateDownloadSession
type UploadServiceMockCreateDownloadSessionParamPtrs struct {
	userID   *int64
	recordID *int64
}

// UploadServiceMockCreateDownloadSessionResults contains results of the UploadService.CreateDownloadSession
type UploadServiceMockCreateDownloadSessionResults struct {
	dp1 *models.DownloadSession
	err error
}

// UploadServiceMockCreateDownloadSessionOrigins contains origins of expectations of the UploadService.CreateDownloadSession
type UploadServiceMockCreateDownloadSessionExpectationOrigins struct {
	origin         string
	originUserID   string
	originRecordID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Optional() *mUploadServiceMockCreateDownloadSession {
	mmCreateDownloadSession.optional = true
	return mmCreateDownloadSession
}

// Expect sets up expected params for UploadService.CreateDownloadSession
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Expect(userID int64, recordID int64) *mUploadServiceMockCreateDownloadSession {
	if mmCreateDownloadSession.mock.funcCreateDownloadSession != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Set")
	}

	if mmCreateDownloadSession.defaultExpectation == nil {
		mmCreateDownloadSession.defaultExpectation = &UploadServiceMockCreateDownloadSessionExpectation{}
	}

	if mmCreateDownloadSession.defaultExpectation.paramPtrs != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by ExpectParams functions")
	}

	mmCreateDownloadSession.defaultExpectation.params = &UploadServiceMockCreateDownloadSessionParams{userID, recordID}
	mmCreateDownloadSession.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateDownloadSession.expectations {
		if minimock.Equal(e.params, mmCreateDownloadSession.defaultExpectation.params) {
			mmCreateDownloadSession.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateDownloadSession.defaultExpectation.params)
		}
	}

	return mmCreateDownloadSession
}

// ExpectUserIDParam1 sets up expected param userID for UploadService.CreateDownloadSession
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) ExpectUserIDParam1(userID int64) *mUploadServiceMockCreateDownloadSession {
	if mmCreateDownloadSession.mock.funcCreateDownloadSession != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Set")
	}

	if mmCreateDownloadSession.defaultExpectation == nil {
		mmCreateDownloadSession.defaultExpectation = &UploadServiceMockCreateDownloadSessionExpectation{}
	}

	if mmCreateDownloadSession.defaultExpectation.params != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Expect")
	}

	if mmCreateDownloadSession.defaultExpectation.paramPtrs == nil {
		mmCreateDownloadSession.defaultExpectation.paramPtrs = &UploadServiceMockCreateDownloadSessionParamPtrs{}
	}
	mmCreateDownloadSession.defaultExpectation.paramPtrs.userID = &userID
	mmCreateDownloadSession.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmCreateDownloadSession
}

// ExpectRecordIDParam2 sets up expected param recordID for UploadService.CreateDownloadSession
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) ExpectRecordIDParam2(recordID int64) *mUploadServiceMockCreateDownloadSession {
	if mmCreateDownloadSession.mock.funcCreateDownloadSession != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Set")
	}

	if mmCreateDownloadSession.defaultExpectation == nil {
		mmCreateDownloadSession.defaultExpectation = &UploadServiceMockCreateDownloadSessionExpectation{}
	}

	if mmCreateDownloadSession.defaultExpectation.params != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Expect")
	}

	if mmCreateDownloadSession.defaultExpectation.paramPtrs == nil {
		mmCreateDownloadSession.defaultExpectation.paramPtrs = &UploadServiceMockCreateDownloadSessionParamPtrs{}
	}
	mmCreateDownloadSession.defaultExpectation.paramPtrs.recordID = &recordID
	mmCreateDownloadSession.defaultExpectation.expectationOrigins.originRecordID = minimock.CallerInfo(1)

	return mmCreateDownloadSession
}

// Inspect accepts an inspector function that has same arguments as the UploadService.CreateDownloadSession
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Inspect(f func(userID int64, recordID int64)) *mUploadServiceMockCreateDownloadSession {
	if mmCreateDownloadSession.mock.inspectFuncCreateDownloadSession != nil {
		mmCreateDownloadSession.mock.t.Fatalf("Inspect function is already set for UploadServiceMock.CreateDownloadSession")
	}

	mmCreateDownloadSession.mock.inspectFuncCreateDownloadSession = f

	return mmCreateDownloadSession
}

// Return sets up results that will be returned by UploadService.CreateDownloadSession
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Return(dp1 *models.DownloadSession, err error) *UploadServiceMock {
	if mmCreateDownloadSession.mock.funcCreateDownloadSession != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Set")
	}

	if mmCreateDownloadSession.defaultExpectation == nil {
		mmCreateDownloadSession.defaultExpectation = &UploadServiceMockCreateDownloadSessionExpectation{mock: mmCreateDownloadSession.mock}
	}
	mmCreateDownloadSession.defaultExpectation.results = &UploadServiceMockCreateDownloadSessionResults{dp1, err}
	mmCreateDownloadSession.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateDownloadSession.mock
}

// Set uses given function f to mock the UploadService.CreateDownloadSession method
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Set(f func(userID int64, recordID int64) (dp1 *models.DownloadSession, err error)) *UploadServiceMock {
	if mmCreateDownloadSession.defaultExpectation != nil {
		mmCreateDownloadSession.mock.t.Fatalf("Default expectation is already set for the UploadService.CreateDownloadSession method")
	}

	if len(mmCreateDownloadSession.expectations) > 0 {
		mmCreateDownloadSession.mock.t.Fatalf("Some expectations are already set for the UploadService.CreateDownloadSession method")
	}

	mmCreateDownloadSession.mock.funcCreateDownloadSession = f
	mmCreateDownloadSession.mock.funcCreateDownloadSessionOrigin = minimock.CallerInfo(1)
	return mmCreateDownloadSession.mock
}

// When sets expectation for the UploadService.CreateDownloadSession which will trigger the result defined by the following
// Then helper
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) When(userID int64, recordID int64) *UploadServiceMockCreateDownloadSessionExpectation {
	if mmCreateDownloadSession.mock.funcCreateDownloadSession != nil {
		mmCreateDownloadSession.mock.t.Fatalf("UploadServiceMock.CreateDownloadSession mock is already set by Set")
	}

	expectation := &UploadServiceMockCreateDownloadSessionExpectation{
		mock:               mmCreateDownloadSession.mock,
		params:             &UploadServiceMockCreateDownloadSessionParams{userID, recordID},
		expectationOrigins: UploadServiceMockCreateDownloadSessionExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateDownloadSession.expectations = append(mmCreateDownloadSession.expectations, expectation)
	return expectation
}

// Then sets up UploadService.CreateDownloadSession return parameters for the expectation previously defined by the When method
func (e *UploadServiceMockCreateDownloadSessionExpectation) Then(dp1 *models.DownloadSession, err error) *UploadServiceMock {
	e.results = &UploadServiceMockCreateDownloadSessionResults{dp1, err}
	return e.mock
}

// Times sets number of times UploadService.CreateDownloadSession should be invoked
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Times(n uint64) *mUploadServiceMockCreateDownloadSession {
	if n == 0 {
		mmCreateDownloadSession.mock.t.Fatalf("Times of UploadServiceMock.CreateDownloadSession mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateDownloadSession.expectedInvocations, n)
	mmCreateDownloadSession.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateDownloadSession
}

func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) invocationsDone() bool {
	if len(mmCreateDownloadSession.expectations) == 0 && mmCreateDownloadSession.defaultExpectation == nil && mmCreateDownloadSession.mock.funcCreateDownloadSession == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateDownloadSession.mock.afterCreateDownloadSessionCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateDownloadSession.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateDownloadSession implements mm_records_by_id_binary_v1_get.UploadService
func (mmCreateDownloadSession *UploadServiceMock) CreateDownloadSession(userID int64, recordID int64) (dp1 *models.DownloadSession, err error) {
	mm_atomic.AddUint64(&mmCreateDownloadSession.beforeCreateDownloadSessionCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateDownloadSession.afterCreateDownloadSessionCounter, 1)

	mmCreateDownloadSession.t.Helper()

	if mmCreateDownloadSession.inspectFuncCreateDownloadSession != nil {
		mmCreateDownloadSession.inspectFuncCreateDownloadSession(userID, recordID)
	}

	mm_params := UploadServiceMockCreateDownloadSessionParams{userID, recordID}

	// Record call args
	mmCreateDownloadSession.CreateDownloadSessionMock.mutex.Lock()
	mmCreateDownloadSession.CreateDownloadSessionMock.callArgs = append(mmCreateDownloadSession.CreateDownloadSessionMock.callArgs, &mm_params)
	mmCreateDownloadSession.CreateDownloadSessionMock.mutex.Unlock()

	for _, e := range mmCreateDownloadSession.CreateDownloadSessionMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.dp1, e.results.err
		}
	}

	if mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.params
		mm_want_ptrs := mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.paramPtrs

		mm_got := UploadServiceMockCreateDownloadSessionParams{userID, recordID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmCreateDownloadSession.t.Errorf("UploadServiceMock.CreateDownloadSession got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.recordID != nil && !minimock.Equal(*mm_want_ptrs.recordID, mm_got.recordID) {
				mmCreateDownloadSession.t.Errorf("UploadServiceMock.CreateDownloadSession got unexpected parameter recordID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.expectationOrigins.originRecordID, *mm_want_ptrs.recordID, mm_got.recordID, minimock.Diff(*mm_want_ptrs.recordID, mm_got.recordID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateDownloadSession.t.Errorf("UploadServiceMock.CreateDownloadSession got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateDownloadSession.CreateDownloadSessionMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateDownloadSession.t.Fatal("No results are set for the UploadServiceMock.CreateDownloadSession")
		}
		return (*mm_results).dp1, (*mm_results).err
	}
	if mmCreateDownloadSession.funcCreateDownloadSession != nil {
		return mmCreateDownloadSession.funcCreateDownloadSession(userID, recordID)
	}
	mmCreateDownloadSession.t.Fatalf("Unexpected call to UploadServiceMock.CreateDownloadSession. %v %v", userID, recordID)
	return
}

// CreateDownloadSessionAfterCounter returns a count of finished UploadServiceMock.CreateDownloadSession invocations
func (mmCreateDownloadSession *UploadServiceMock) CreateDownloadSessionAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateDownloadSession.afterCreateDownloadSessionCounter)
}

// CreateDownloadSessionBeforeCounter returns a count of UploadServiceMock.CreateDownloadSession invocations
func (mmCreateDownloadSession *UploadServiceMock) CreateDownloadSessionBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateDownloadSession.beforeCreateDownloadSessionCounter)
}

// Calls returns a list of arguments used in each call to UploadServiceMock.CreateDownloadSession.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateDownloadSession *mUploadServiceMockCreateDownloadSession) Calls() []*UploadServiceMockCreateDownloadSessionParams {
	mmCreateDownloadSession.mutex.RLock()

	argCopy := make([]*UploadServiceMockCreateDownloadSessionParams, len(mmCreateDownloadSession.callArgs))
	copy(argCopy, mmCreateDownloadSession.callArgs)

	mmCreateDownloadSession.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDownloadSessionDone returns true if the count of the CreateDownloadSession invocations corresponds
// the number of defined expectations
func (m *UploadServiceMock) MinimockCreateDownloadSessionDone() bool {
	if m.CreateDownloadSessionMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateDownloadSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateDownloadSessionMock.invocationsDone()
}

// MinimockCreateDownloadSessionInspect logs each unmet expectation
func (m *UploadServiceMock) MinimockCreateDownloadSessionInspect() {
	for _, e := range m.CreateDownloadSessionMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UploadServiceMock.CreateDownloadSession at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateDownloadSessionCounter := mm_atomic.LoadUint64(&m.afterCreateDownloadSessionCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateDownloadSessionMock.defaultExpectation != nil && afterCreateDownloadSessionCounter < 1 {
		if m.CreateDownloadSessionMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UploadServiceMock.CreateDownloadSession at\n%s", m.CreateDownloadSessionMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UploadServiceMock.CreateDownloadSession at\n%s with params: %#v", m.CreateDownloadSessionMock.defaultExpectation.expectationOrigins.origin, *m.CreateDownloadSessionMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateDownloadSession != nil && afterCreateDownloadSessionCounter < 1 {
		m.t.Errorf("Expected call to UploadServiceMock.CreateDownloadSession at\n%s", m.funcCreateDownloadSessionOrigin)
	}

	if !m.CreateDownloadSessionMock.invocationsDone() && afterCreateDownloadSessionCounter > 0 {
		m.t.Errorf("Expected %d calls to UploadServiceMock.CreateDownloadSession at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateDownloadSessionMock.expectedInvocations), m.CreateDownloadSessionMock.expectedInvocationsOrigin, afterCreateDownloadSessionCounter)
	}
}

type mUploadServiceMockDownloadChunkByID struct {
	optional           bool
	mock               *UploadServiceMock
	defaultExpectation *UploadServiceMockDownloadChunkByIDExpectation
	expectations       []*UploadServiceMockDownloadChunkByIDExpectation

	callArgs []*UploadServiceMockDownloadChunkByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UploadServiceMockDownloadChunkByIDExpectation specifies expectation struct of the UploadService.DownloadChunkByID
type UploadServiceMockDownloadChunkByIDExpectation struct {
	mock               *UploadServiceMock
	params             *UploadServiceMockDownloadChunkByIDParams
	paramPtrs          *UploadServiceMockDownloadChunkByIDParamPtrs
	expectationOrigins UploadServiceMockDownloadChunkByIDExpectationOrigins
	results            *UploadServiceMockDownloadChunkByIDResults
	returnOrigin       string
	Counter            uint64
}

// UploadServiceMockDownloadChunkByIDParams contains parameters of the UploadService.DownloadChunkByID
type UploadServiceMockDownloadChunkByIDParams struct {
	downloadID int64
	chunkIndex int64
}

// UploadServiceMockDownloadChunkByIDParamPtrs contains pointers to parameters of the UploadService.DownloadChunkByID
type UploadServiceMockDownloadChunkByIDParamPtrs struct {
	downloadID *int64
	chunkIndex *int64
}

// UploadServiceMockDownloadChunkByIDResults contains results of the UploadService.DownloadChunkByID
type UploadServiceMockDownloadChunkByIDResults struct {
	cp1 *models.Chunk
	err error
}

// UploadServiceMockDownloadChunkByIDOrigins contains origins of expectations of the UploadService.DownloadChunkByID
type UploadServiceMockDownloadChunkByIDExpectationOrigins struct {
	origin           string
	originDownloadID string
	originChunkIndex string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Optional() *mUploadServiceMockDownloadChunkByID {
	mmDownloadChunkByID.optional = true
	return mmDownloadChunkByID
}

// Expect sets up expected params for UploadService.DownloadChunkByID
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Expect(downloadID int64, chunkIndex int64) *mUploadServiceMockDownloadChunkByID {
	if mmDownloadChunkByID.mock.funcDownloadChunkByID != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Set")
	}

	if mmDownloadChunkByID.defaultExpectation == nil {
		mmDownloadChunkByID.defaultExpectation = &UploadServiceMockDownloadChunkByIDExpectation{}
	}

	if mmDownloadChunkByID.defaultExpectation.paramPtrs != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by ExpectParams functions")
	}

	mmDownloadChunkByID.defaultExpectation.params = &UploadServiceMockDownloadChunkByIDParams{downloadID, chunkIndex}
	mmDownloadChunkByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDownloadChunkByID.expectations {
		if minimock.Equal(e.params, mmDownloadChunkByID.defaultExpectation.params) {
			mmDownloadChunkByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDownloadChunkByID.defaultExpectation.params)
		}
	}

	return mmDownloadChunkByID
}

// ExpectDownloadIDParam1 sets up expected param downloadID for UploadService.DownloadChunkByID
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) ExpectDownloadIDParam1(downloadID int64) *mUploadServiceMockDownloadChunkByID {
	if mmDownloadChunkByID.mock.funcDownloadChunkByID != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Set")
	}

	if mmDownloadChunkByID.defaultExpectation == nil {
		mmDownloadChunkByID.defaultExpectation = &UploadServiceMockDownloadChunkByIDExpectation{}
	}

	if mmDownloadChunkByID.defaultExpectation.params != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Expect")
	}

	if mmDownloadChunkByID.defaultExpectation.paramPtrs == nil {
		mmDownloadChunkByID.defaultExpectation.paramPtrs = &UploadServiceMockDownloadChunkByIDParamPtrs{}
	}
	mmDownloadChunkByID.defaultExpectation.paramPtrs.downloadID = &downloadID
	mmDownloadChunkByID.defaultExpectation.expectationOrigins.originDownloadID = minimock.CallerInfo(1)

	return mmDownloadChunkByID
}

// ExpectChunkIndexParam2 sets up expected param chunkIndex for UploadService.DownloadChunkByID
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) ExpectChunkIndexParam2(chunkIndex int64) *mUploadServiceMockDownloadChunkByID {
	if mmDownloadChunkByID.mock.funcDownloadChunkByID != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Set")
	}

	if mmDownloadChunkByID.defaultExpectation == nil {
		mmDownloadChunkByID.defaultExpectation = &UploadServiceMockDownloadChunkByIDExpectation{}
	}

	if mmDownloadChunkByID.defaultExpectation.params != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Expect")
	}

	if mmDownloadChunkByID.defaultExpectation.paramPtrs == nil {
		mmDownloadChunkByID.defaultExpectation.paramPtrs = &UploadServiceMockDownloadChunkByIDParamPtrs{}
	}
	mmDownloadChunkByID.defaultExpectation.paramPtrs.chunkIndex = &chunkIndex
	mmDownloadChunkByID.defaultExpectation.expectationOrigins.originChunkIndex = minimock.CallerInfo(1)

	return mmDownloadChunkByID
}

// Inspect accepts an inspector function that has same arguments as the UploadService.DownloadChunkByID
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Inspect(f func(downloadID int64, chunkIndex int64)) *mUploadServiceMockDownloadChunkByID {
	if mmDownloadChunkByID.mock.inspectFuncDownloadChunkByID != nil {
		mmDownloadChunkByID.mock.t.Fatalf("Inspect function is already set for UploadServiceMock.DownloadChunkByID")
	}

	mmDownloadChunkByID.mock.inspectFuncDownloadChunkByID = f

	return mmDownloadChunkByID
}

// Return sets up results that will be returned by UploadService.DownloadChunkByID
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Return(cp1 *models.Chunk, err error) *UploadServiceMock {
	if mmDownloadChunkByID.mock.funcDownloadChunkByID != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Set")
	}

	if mmDownloadChunkByID.defaultExpectation == nil {
		mmDownloadChunkByID.defaultExpectation = &UploadServiceMockDownloadChunkByIDExpectation{mock: mmDownloadChunkByID.mock}
	}
	mmDownloadChunkByID.defaultExpectation.results = &UploadServiceMockDownloadChunkByIDResults{cp1, err}
	mmDownloadChunkByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDownloadChunkByID.mock
}

// Set uses given function f to mock the UploadService.DownloadChunkByID method
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Set(f func(downloadID int64, chunkIndex int64) (cp1 *models.Chunk, err error)) *UploadServiceMock {
	if mmDownloadChunkByID.defaultExpectation != nil {
		mmDownloadChunkByID.mock.t.Fatalf("Default expectation is already set for the UploadService.DownloadChunkByID method")
	}

	if len(mmDownloadChunkByID.expectations) > 0 {
		mmDownloadChunkByID.mock.t.Fatalf("Some expectations are already set for the UploadService.DownloadChunkByID method")
	}

	mmDownloadChunkByID.mock.funcDownloadChunkByID = f
	mmDownloadChunkByID.mock.funcDownloadChunkByIDOrigin = minimock.CallerInfo(1)
	return mmDownloadChunkByID.mock
}

// When sets expectation for the UploadService.DownloadChunkByID which will trigger the result defined by the following
// Then helper
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) When(downloadID int64, chunkIndex int64) *UploadServiceMockDownloadChunkByIDExpectation {
	if mmDownloadChunkByID.mock.funcDownloadChunkByID != nil {
		mmDownloadChunkByID.mock.t.Fatalf("UploadServiceMock.DownloadChunkByID mock is already set by Set")
	}

	expectation := &UploadServiceMockDownloadChunkByIDExpectation{
		mock:               mmDownloadChunkByID.mock,
		params:             &UploadServiceMockDownloadChunkByIDParams{downloadID, chunkIndex},
		expectationOrigins: UploadServiceMockDownloadChunkByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDownloadChunkByID.expectations = append(mmDownloadChunkByID.expectations, expectation)
	return expectation
}

// Then sets up UploadService.DownloadChunkByID return parameters for the expectation previously defined by the When method
func (e *UploadServiceMockDownloadChunkByIDExpectation) Then(cp1 *models.Chunk, err error) *UploadServiceMock {
	e.results = &UploadServiceMockDownloadChunkByIDResults{cp1, err}
	return e.mock
}

// Times sets number of times UploadService.DownloadChunkByID should be invoked
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Times(n uint64) *mUploadServiceMockDownloadChunkByID {
	if n == 0 {
		mmDownloadChunkByID.mock.t.Fatalf("Times of UploadServiceMock.DownloadChunkByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDownloadChunkByID.expectedInvocations, n)
	mmDownloadChunkByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDownloadChunkByID
}

func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) invocationsDone() bool {
	if len(mmDownloadChunkByID.expectations) == 0 && mmDownloadChunkByID.defaultExpectation == nil && mmDownloadChunkByID.mock.funcDownloadChunkByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDownloadChunkByID.mock.afterDownloadChunkByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDownloadChunkByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DownloadChunkByID implements mm_records_by_id_binary_v1_get.UploadService
func (mmDownloadChunkByID *UploadServiceMock) DownloadChunkByID(downloadID int64, chunkIndex int64) (cp1 *models.Chunk, err error) {
	mm_atomic.AddUint64(&mmDownloadChunkByID.beforeDownloadChunkByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmDownloadChunkByID.afterDownloadChunkByIDCounter, 1)

	mmDownloadChunkByID.t.Helper()

	if mmDownloadChunkByID.inspectFuncDownloadChunkByID != nil {
		mmDownloadChunkByID.inspectFuncDownloadChunkByID(downloadID, chunkIndex)
	}

	mm_params := UploadServiceMockDownloadChunkByIDParams{downloadID, chunkIndex}

	// Record call args
	mmDownloadChunkByID.DownloadChunkByIDMock.mutex.Lock()
	mmDownloadChunkByID.DownloadChunkByIDMock.callArgs = append(mmDownloadChunkByID.DownloadChunkByIDMock.callArgs, &mm_params)
	mmDownloadChunkByID.DownloadChunkByIDMock.mutex.Unlock()

	for _, e := range mmDownloadChunkByID.DownloadChunkByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.params
		mm_want_ptrs := mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.paramPtrs

		mm_got := UploadServiceMockDownloadChunkByIDParams{downloadID, chunkIndex}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.downloadID != nil && !minimock.Equal(*mm_want_ptrs.downloadID, mm_got.downloadID) {
				mmDownloadChunkByID.t.Errorf("UploadServiceMock.DownloadChunkByID got unexpected parameter downloadID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.expectationOrigins.originDownloadID, *mm_want_ptrs.downloadID, mm_got.downloadID, minimock.Diff(*mm_want_ptrs.downloadID, mm_got.downloadID))
			}

			if mm_want_ptrs.chunkIndex != nil && !minimock.Equal(*mm_want_ptrs.chunkIndex, mm_got.chunkIndex) {
				mmDownloadChunkByID.t.Errorf("UploadServiceMock.DownloadChunkByID got unexpected parameter chunkIndex, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.expectationOrigins.originChunkIndex, *mm_want_ptrs.chunkIndex, mm_got.chunkIndex, minimock.Diff(*mm_want_ptrs.chunkIndex, mm_got.chunkIndex))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDownloadChunkByID.t.Errorf("UploadServiceMock.DownloadChunkByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDownloadChunkByID.DownloadChunkByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmDownloadChunkByID.t.Fatal("No results are set for the UploadServiceMock.DownloadChunkByID")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmDownloadChunkByID.funcDownloadChunkByID != nil {
		return mmDownloadChunkByID.funcDownloadChunkByID(downloadID, chunkIndex)
	}
	mmDownloadChunkByID.t.Fatalf("Unexpected call to UploadServiceMock.DownloadChunkByID. %v %v", downloadID, chunkIndex)
	return
}

// DownloadChunkByIDAfterCounter returns a count of finished UploadServiceMock.DownloadChunkByID invocations
func (mmDownloadChunkByID *UploadServiceMock) DownloadChunkByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDownloadChunkByID.afterDownloadChunkByIDCounter)
}

// DownloadChunkByIDBeforeCounter returns a count of UploadServiceMock.DownloadChunkByID invocations
func (mmDownloadChunkByID *UploadServiceMock) DownloadChunkByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDownloadChunkByID.beforeDownloadChunkByIDCounter)
}

// Calls returns a list of arguments used in each call to UploadServiceMock.DownloadChunkByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDownloadChunkByID *mUploadServiceMockDownloadChunkByID) Calls() []*UploadServiceMockDownloadChunkByIDParams {
	mmDownloadChunkByID.mutex.RLock()

	argCopy := make([]*UploadServiceMockDownloadChunkByIDParams, len(mmDownloadChunkByID.callArgs))
	copy(argCopy, mmDownloadChunkByID.callArgs)

	mmDownloadChunkByID.mutex.RUnlock()

	return argCopy
}

// MinimockDownloadChunkByIDDone returns true if the count of the DownloadChunkByID invocations corresponds
// the number of defined expectations
func (m *UploadServiceMock) MinimockDownloadChunkByIDDone() bool {
	if m.DownloadChunkByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DownloadChunkByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DownloadChunkByIDMock.invocationsDone()
}

// MinimockDownloadChunkByIDInspect logs each unmet expectation
func (m *UploadServiceMock) MinimockDownloadChunkByIDInspect() {
	for _, e := range m.DownloadChunkByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UploadServiceMock.DownloadChunkByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDownloadChunkByIDCounter := mm_atomic.LoadUint64(&m.afterDownloadChunkByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DownloadChunkByIDMock.defaultExpectation != nil && afterDownloadChunkByIDCounter < 1 {
		if m.DownloadChunkByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UploadServiceMock.DownloadChunkByID at\n%s", m.DownloadChunkByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UploadServiceMock.DownloadChunkByID at\n%s with params: %#v", m.DownloadChunkByIDMock.defaultExpectation.expectationOrigins.origin, *m.DownloadChunkByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDownloadChunkByID != nil && afterDownloadChunkByIDCounter < 1 {
		m.t.Errorf("Expected call to UploadServiceMock.DownloadChunkByID at\n%s", m.funcDownloadChunkByIDOrigin)
	}

	if !m.DownloadChunkByIDMock.invocationsDone() && afterDownloadChunkByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UploadServiceMock.DownloadChunkByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DownloadChunkByIDMock.expectedInvocations), m.DownloadChunkByIDMock.expectedInvocationsOrigin, afterDownloadChunkByIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UploadServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockConfirmChunkInspect()

			m.MinimockCreateDownloadSessionInspect()

			m.MinimockDownloadChunkByIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UploadServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UploadServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockConfirmChunkDone() &&
		m.MinimockCreateDownloadSessionDone() &&
		m.MinimockDownloadChunkByIDDone()
}
