// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// RecordServiceMock implements mm_recordsv1post.RecordService
type RecordServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateRecord          func(record *models.Record) (err error)
	funcCreateRecordOrigin    string
	inspectFuncCreateRecord   func(record *models.Record)
	afterCreateRecordCounter  uint64
	beforeCreateRecordCounter uint64
	CreateRecordMock          mRecordServiceMockCreateRecord
}

// NewRecordServiceMock returns a mock for mm_recordsv1post.RecordService
func NewRecordServiceMock(t minimock.Tester) *RecordServiceMock {
	m := &RecordServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateRecordMock = mRecordServiceMockCreateRecord{mock: m}
	m.CreateRecordMock.callArgs = []*RecordServiceMockCreateRecordParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRecordServiceMockCreateRecord struct {
	optional           bool
	mock               *RecordServiceMock
	defaultExpectation *RecordServiceMockCreateRecordExpectation
	expectations       []*RecordServiceMockCreateRecordExpectation

	callArgs []*RecordServiceMockCreateRecordParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RecordServiceMockCreateRecordExpectation specifies expectation struct of the RecordService.CreateRecord
type RecordServiceMockCreateRecordExpectation struct {
	mock               *RecordServiceMock
	params             *RecordServiceMockCreateRecordParams
	paramPtrs          *RecordServiceMockCreateRecordParamPtrs
	expectationOrigins RecordServiceMockCreateRecordExpectationOrigins
	results            *RecordServiceMockCreateRecordResults
	returnOrigin       string
	Counter            uint64
}

// RecordServiceMockCreateRecordParams contains parameters of the RecordService.CreateRecord
type RecordServiceMockCreateRecordParams struct {
	record *models.Record
}

// RecordServiceMockCreateRecordParamPtrs contains pointers to parameters of the RecordService.CreateRecord
type RecordServiceMockCreateRecordParamPtrs struct {
	record **models.Record
}

// RecordServiceMockCreateRecordResults contains results of the RecordService.CreateRecord
type RecordServiceMockCreateRecordResults struct {
	err error
}

// RecordServiceMockCreateRecordOrigins contains origins of expectations of the RecordService.CreateRecord
type RecordServiceMockCreateRecordExpectationOrigins struct {
	origin       string
	originRecord string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateRecord *mRecordServiceMockCreateRecord) Optional() *mRecordServiceMockCreateRecord {
	mmCreateRecord.optional = true
	return mmCreateRecord
}

// Expect sets up expected params for RecordService.CreateRecord
func (mmCreateRecord *mRecordServiceMockCreateRecord) Expect(record *models.Record) *mRecordServiceMockCreateRecord {
	if mmCreateRecord.mock.funcCreateRecord != nil {
		mmCreateRecord.mock.t.Fatalf("RecordServiceMock.CreateRecord mock is already set by Set")
	}

	if mmCreateRecord.defaultExpectation == nil {
		mmCreateRecord.defaultExpectation = &RecordServiceMockCreateRecordExpectation{}
	}

	if mmCreateRecord.defaultExpectation.paramPtrs != nil {
		mmCreateRecord.mock.t.Fatalf("RecordServiceMock.CreateRecord mock is already set by ExpectParams functions")
	}

	mmCreateRecord.defaultExpectation.params = &RecordServiceMockCreateRecordParams{record}
	mmCreateRecord.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateRecord.expectations {
		if minimock.Equal(e.params, mmCreateRecord.defaultExpectation.params) {
			mmCreateRecord.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateRecord.defaultExpectation.params)
		}
	}

	return mmCreateRecord
}

// ExpectRecordParam1 sets up expected param record for RecordService.CreateRecord
func (mmCreateRecord *mRecordServiceMockCreateRecord) ExpectRecordParam1(record *models.Record) *mRecordServiceMockCreateRecord {
	if mmCreateRecord.mock.funcCreateRecord != nil {
		mmCreateRecord.mock.t.Fatalf("RecordServiceMock.CreateRecord mock is already set by Set")
	}

	if mmCreateRecord.defaultExpectation == nil {
		mmCreateRecord.defaultExpectation = &RecordServiceMockCreateRecordExpectation{}
	}

	if mmCreateRecord.defaultExpectation.params != nil {
		mmCreateRecord.mock.t.Fatalf("RecordServiceMock.CreateRecord mock is already set by Expect")
	}

	if mmCreateRecord.defaultExpectation.paramPtrs == nil {
		mmCreateRecord.defaultExpectation.paramPtrs = &RecordServiceMockCreateRecordParamPtrs{}
	}
	mmCreateRecord.defaultExpectation.paramPtrs.record = &record
	mmCreateRecord.defaultExpectation.expectationOrigins.originRecord = minimock.CallerInfo(1)

	return mmCreateRecord
}

// Inspect accepts an inspector function that has same arguments as the RecordService.CreateRecord
func (mmCreateRecord *mRecordServiceMockCreateRecord) Inspect(f func(record *models.Record)) *mRecordServiceMockCreateRecord {
	if mmCreateRecord.mock.inspectFuncCreateRecord != nil {
		mmCreateRecord.mock.t.Fatalf("Inspect function is already set for RecordServiceMock.CreateRecord")
	}

	mmCreateRecord.mock.inspectFuncCreateRecord = f

	return mmCreateRecord
}

// Return sets up results that will be returned by RecordService.CreateRecord
func (mmCreateRecord *mRecordServiceMockCreateRecord) Return(err error) *RecordServiceMock {
	if mmCreateRecord.mock.funcCreateRecord != nil {
		mmCreateRecord.mock.t.Fatalf("RecordServiceMock.CreateRecord mock is already set by Set")
	}

	if mmCreateRecord.defaultExpectation == nil {
		mmCreateRecord.defaultExpectation = &RecordServiceMockCreateRecordExpectation{mock: mmCreateRecord.mock}
	}
	mmCreateRecord.defaultExpectation.results = &RecordServiceMockCreateRecordResults{err}
	mmCreateRecord.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateRecord.mock
}

// Set uses given function f to mock the RecordService.CreateRecord method
func (mmCreateRecord *mRecordServiceMockCreateRecord) Set(f func(record *models.Record) (err error)) *RecordServiceMock {
	if mmCreateRecord.defaultExpectation != nil {
		mmCreateRecord.mock.t.Fatalf("Default expectation is already set for the RecordService.CreateRecord method")
	}

	if len(mmCreateRecord.expectations) > 0 {
		mmCreateRecord.mock.t.Fatalf("Some expectations are already set for the RecordService.CreateRecord method")
	}

	mmCreateRecord.mock.funcCreateRecord = f
	mmCreateRecord.mock.funcCreateRecordOrigin = minimock.CallerInfo(1)
	return mmCreateRecord.mock
}

// When sets expectation for the RecordService.CreateRecord which will trigger the result defined by the following
// Then helper
func (mmCreateRecord *mRecordServiceMockCreateRecord) When(record *models.Record) *RecordServiceMockCreateRecordExpectation {
	if mmCreateRecord.mock.funcCreateRecord != nil {
		mmCreateRecord.mock.t.Fatalf("RecordServiceMock.CreateRecord mock is already set by Set")
	}

	expectation := &RecordServiceMockCreateRecordExpectation{
		mock:               mmCreateRecord.mock,
		params:             &RecordServiceMockCreateRecordParams{record},
		expectationOrigins: RecordServiceMockCreateRecordExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateRecord.expectations = append(mmCreateRecord.expectations, expectation)
	return expectation
}

// Then sets up RecordService.CreateRecord return parameters for the expectation previously defined by the When method
func (e *RecordServiceMockCreateRecordExpectation) Then(err error) *RecordServiceMock {
	e.results = &RecordServiceMockCreateRecordResults{err}
	return e.mock
}

// Times sets number of times RecordService.CreateRecord should be invoked
func (mmCreateRecord *mRecordServiceMockCreateRecord) Times(n uint64) *mRecordServiceMockCreateRecord {
	if n == 0 {
		mmCreateRecord.mock.t.Fatalf("Times of RecordServiceMock.CreateRecord mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateRecord.expectedInvocations, n)
	mmCreateRecord.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateRecord
}

func (mmCreateRecord *mRecordServiceMockCreateRecord) invocationsDone() bool {
	if len(mmCreateRecord.expectations) == 0 && mmCreateRecord.defaultExpectation == nil && mmCreateRecord.mock.funcCreateRecord == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateRecord.mock.afterCreateRecordCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateRecord.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateRecord implements mm_recordsv1post.RecordService
func (mmCreateRecord *RecordServiceMock) CreateRecord(record *models.Record) (err error) {
	mm_atomic.AddUint64(&mmCreateRecord.beforeCreateRecordCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateRecord.afterCreateRecordCounter, 1)

	mmCreateRecord.t.Helper()

	if mmCreateRecord.inspectFuncCreateRecord != nil {
		mmCreateRecord.inspectFuncCreateRecord(record)
	}

	mm_params := RecordServiceMockCreateRecordParams{record}

	// Record call args
	mmCreateRecord.CreateRecordMock.mutex.Lock()
	mmCreateRecord.CreateRecordMock.callArgs = append(mmCreateRecord.CreateRecordMock.callArgs, &mm_params)
	mmCreateRecord.CreateRecordMock.mutex.Unlock()

	for _, e := range mmCreateRecord.CreateRecordMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreateRecord.CreateRecordMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateRecord.CreateRecordMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateRecord.CreateRecordMock.defaultExpectation.params
		mm_want_ptrs := mmCreateRecord.CreateRecordMock.defaultExpectation.paramPtrs

		mm_got := RecordServiceMockCreateRecordParams{record}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.record != nil && !minimock.Equal(*mm_want_ptrs.record, mm_got.record) {
				mmCreateRecord.t.Errorf("RecordServiceMock.CreateRecord got unexpected parameter record, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateRecord.CreateRecordMock.defaultExpectation.expectationOrigins.originRecord, *mm_want_ptrs.record, mm_got.record, minimock.Diff(*mm_want_ptrs.record, mm_got.record))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateRecord.t.Errorf("RecordServiceMock.CreateRecord got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateRecord.CreateRecordMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateRecord.CreateRecordMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateRecord.t.Fatal("No results are set for the RecordServiceMock.CreateRecord")
		}
		return (*mm_results).err
	}
	if mmCreateRecord.funcCreateRecord != nil {
		return mmCreateRecord.funcCreateRecord(record)
	}
	mmCreateRecord.t.Fatalf("Unexpected call to RecordServiceMock.CreateRecord. %v", record)
	return
}

// CreateRecordAfterCounter returns a count of finished RecordServiceMock.CreateRecord invocations
func (mmCreateRecord *RecordServiceMock) CreateRecordAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateRecord.afterCreateRecordCounter)
}

// CreateRecordBeforeCounter returns a count of RecordServiceMock.CreateRecord invocations
func (mmCreateRecord *RecordServiceMock) CreateRecordBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateRecord.beforeCreateRecordCounter)
}

// Calls returns a list of arguments used in each call to RecordServiceMock.CreateRecord.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateRecord *mRecordServiceMockCreateRecord) Calls() []*RecordServiceMockCreateRecordParams {
	mmCreateRecord.mutex.RLock()

	argCopy := make([]*RecordServiceMockCreateRecordParams, len(mmCreateRecord.callArgs))
	copy(argCopy, mmCreateRecord.callArgs)

	mmCreateRecord.mutex.RUnlock()

	return argCopy
}

// MinimockCreateRecordDone returns true if the count of the CreateRecord invocations corresponds
// the number of defined expectations
func (m *RecordServiceMock) MinimockCreateRecordDone() bool {
	if m.CreateRecordMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateRecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateRecordMock.invocationsDone()
}

// MinimockCreateRecordInspect logs each unmet expectation
func (m *RecordServiceMock) MinimockCreateRecordInspect() {
	for _, e := range m.CreateRecordMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RecordServiceMock.CreateRecord at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateRecordCounter := mm_atomic.LoadUint64(&m.afterCreateRecordCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateRecordMock.defaultExpectation != nil && afterCreateRecordCounter < 1 {
		if m.CreateRecordMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RecordServiceMock.CreateRecord at\n%s", m.CreateRecordMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RecordServiceMock.CreateRecord at\n%s with params: %#v", m.CreateRecordMock.defaultExpectation.expectationOrigins.origin, *m.CreateRecordMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateRecord != nil && afterCreateRecordCounter < 1 {
		m.t.Errorf("Expected call to RecordServiceMock.CreateRecord at\n%s", m.funcCreateRecordOrigin)
	}

	if !m.CreateRecordMock.invocationsDone() && afterCreateRecordCounter > 0 {
		m.t.Errorf("Expected %d calls to RecordServiceMock.CreateRecord at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateRecordMock.expectedInvocations), m.CreateRecordMock.expectedInvocationsOrigin, afterCreateRecordCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RecordServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateRecordInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RecordServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RecordServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateRecordDone()
}
