// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/hydra13/gophkeeper/internal/models"
)

// ChunkDownloaderMock implements mm_uploads_by_id_chunks_v1_get.ChunkDownloader
type ChunkDownloaderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDownloadChunk          func(uploadID int64, chunkIndex int64) (cp1 *models.ChunkDownloadResponse, err error)
	funcDownloadChunkOrigin    string
	inspectFuncDownloadChunk   func(uploadID int64, chunkIndex int64)
	afterDownloadChunkCounter  uint64
	beforeDownloadChunkCounter uint64
	DownloadChunkMock          mChunkDownloaderMockDownloadChunk
}

// NewChunkDownloaderMock returns a mock for mm_uploads_by_id_chunks_v1_get.ChunkDownloader
func NewChunkDownloaderMock(t minimock.Tester) *ChunkDownloaderMock {
	m := &ChunkDownloaderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DownloadChunkMock = mChunkDownloaderMockDownloadChunk{mock: m}
	m.DownloadChunkMock.callArgs = []*ChunkDownloaderMockDownloadChunkParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mChunkDownloaderMockDownloadChunk struct {
	optional           bool
	mock               *ChunkDownloaderMock
	defaultExpectation *ChunkDownloaderMockDownloadChunkExpectation
	expectations       []*ChunkDownloaderMockDownloadChunkExpectation

	callArgs []*ChunkDownloaderMockDownloadChunkParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ChunkDownloaderMockDownloadChunkExpectation specifies expectation struct of the ChunkDownloader.DownloadChunk
type ChunkDownloaderMockDownloadChunkExpectation struct {
	mock               *ChunkDownloaderMock
	params             *ChunkDownloaderMockDownloadChunkParams
	paramPtrs          *ChunkDownloaderMockDownloadChunkParamPtrs
	expectationOrigins ChunkDownloaderMockDownloadChunkExpectationOrigins
	results            *ChunkDownloaderMockDownloadChunkResults
	returnOrigin       string
	Counter            uint64
}

// ChunkDownloaderMockDownloadChunkParams contains parameters of the ChunkDownloader.DownloadChunk
type ChunkDownloaderMockDownloadChunkParams struct {
	uploadID   int64
	chunkIndex int64
}

// ChunkDownloaderMockDownloadChunkParamPtrs contains pointers to parameters of the ChunkDownloader.DownloadChunk
type ChunkDownloaderMockDownloadChunkParamPtrs struct {
	uploadID   *int64
	chunkIndex *int64
}

// ChunkDownloaderMockDownloadChunkResults contains results of the ChunkDownloader.DownloadChunk
type ChunkDownloaderMockDownloadChunkResults struct {
	cp1 *models.ChunkDownloadResponse
	err error
}

// ChunkDownloaderMockDownloadChunkOrigins contains origins of expectations of the ChunkDownloader.DownloadChunk
type ChunkDownloaderMockDownloadChunkExpectationOrigins struct {
	origin           string
	originUploadID   string
	originChunkIndex string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Optional() *mChunkDownloaderMockDownloadChunk {
	mmDownloadChunk.optional = true
	return mmDownloadChunk
}

// Expect sets up expected params for ChunkDownloader.DownloadChunk
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Expect(uploadID int64, chunkIndex int64) *mChunkDownloaderMockDownloadChunk {
	if mmDownloadChunk.mock.funcDownloadChunk != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Set")
	}

	if mmDownloadChunk.defaultExpectation == nil {
		mmDownloadChunk.defaultExpectation = &ChunkDownloaderMockDownloadChunkExpectation{}
	}

	if mmDownloadChunk.defaultExpectation.paramPtrs != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by ExpectParams functions")
	}

	mmDownloadChunk.defaultExpectation.params = &ChunkDownloaderMockDownloadChunkParams{uploadID, chunkIndex}
	mmDownloadChunk.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDownloadChunk.expectations {
		if minimock.Equal(e.params, mmDownloadChunk.defaultExpectation.params) {
			mmDownloadChunk.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDownloadChunk.defaultExpectation.params)
		}
	}

	return mmDownloadChunk
}

// ExpectUploadIDParam1 sets up expected param uploadID for ChunkDownloader.DownloadChunk
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) ExpectUploadIDParam1(uploadID int64) *mChunkDownloaderMockDownloadChunk {
	if mmDownloadChunk.mock.funcDownloadChunk != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Set")
	}

	if mmDownloadChunk.defaultExpectation == nil {
		mmDownloadChunk.defaultExpectation = &ChunkDownloaderMockDownloadChunkExpectation{}
	}

	if mmDownloadChunk.defaultExpectation.params != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Expect")
	}

	if mmDownloadChunk.defaultExpectation.paramPtrs == nil {
		mmDownloadChunk.defaultExpectation.paramPtrs = &ChunkDownloaderMockDownloadChunkParamPtrs{}
	}
	mmDownloadChunk.defaultExpectation.paramPtrs.uploadID = &uploadID
	mmDownloadChunk.defaultExpectation.expectationOrigins.originUploadID = minimock.CallerInfo(1)

	return mmDownloadChunk
}

// ExpectChunkIndexParam2 sets up expected param chunkIndex for ChunkDownloader.DownloadChunk
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) ExpectChunkIndexParam2(chunkIndex int64) *mChunkDownloaderMockDownloadChunk {
	if mmDownloadChunk.mock.funcDownloadChunk != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Set")
	}

	if mmDownloadChunk.defaultExpectation == nil {
		mmDownloadChunk.defaultExpectation = &ChunkDownloaderMockDownloadChunkExpectation{}
	}

	if mmDownloadChunk.defaultExpectation.params != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Expect")
	}

	if mmDownloadChunk.defaultExpectation.paramPtrs == nil {
		mmDownloadChunk.defaultExpectation.paramPtrs = &ChunkDownloaderMockDownloadChunkParamPtrs{}
	}
	mmDownloadChunk.defaultExpectation.paramPtrs.chunkIndex = &chunkIndex
	mmDownloadChunk.defaultExpectation.expectationOrigins.originChunkIndex = minimock.CallerInfo(1)

	return mmDownloadChunk
}

// Inspect accepts an inspector function that has same arguments as the ChunkDownloader.DownloadChunk
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Inspect(f func(uploadID int64, chunkIndex int64)) *mChunkDownloaderMockDownloadChunk {
	if mmDownloadChunk.mock.inspectFuncDownloadChunk != nil {
		mmDownloadChunk.mock.t.Fatalf("Inspect function is already set for ChunkDownloaderMock.DownloadChunk")
	}

	mmDownloadChunk.mock.inspectFuncDownloadChunk = f

	return mmDownloadChunk
}

// Return sets up results that will be returned by ChunkDownloader.DownloadChunk
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Return(cp1 *models.ChunkDownloadResponse, err error) *ChunkDownloaderMock {
	if mmDownloadChunk.mock.funcDownloadChunk != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Set")
	}

	if mmDownloadChunk.defaultExpectation == nil {
		mmDownloadChunk.defaultExpectation = &ChunkDownloaderMockDownloadChunkExpectation{mock: mmDownloadChunk.mock}
	}
	mmDownloadChunk.defaultExpectation.results = &ChunkDownloaderMockDownloadChunkResults{cp1, err}
	mmDownloadChunk.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDownloadChunk.mock
}

// Set uses given function f to mock the ChunkDownloader.DownloadChunk method
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Set(f func(uploadID int64, chunkIndex int64) (cp1 *models.ChunkDownloadResponse, err error)) *ChunkDownloaderMock {
	if mmDownloadChunk.defaultExpectation != nil {
		mmDownloadChunk.mock.t.Fatalf("Default expectation is already set for the ChunkDownloader.DownloadChunk method")
	}

	if len(mmDownloadChunk.expectations) > 0 {
		mmDownloadChunk.mock.t.Fatalf("Some expectations are already set for the ChunkDownloader.DownloadChunk method")
	}

	mmDownloadChunk.mock.funcDownloadChunk = f
	mmDownloadChunk.mock.funcDownloadChunkOrigin = minimock.CallerInfo(1)
	return mmDownloadChunk.mock
}

// When sets expectation for the ChunkDownloader.DownloadChunk which will trigger the result defined by the following
// Then helper
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) When(uploadID int64, chunkIndex int64) *ChunkDownloaderMockDownloadChunkExpectation {
	if mmDownloadChunk.mock.funcDownloadChunk != nil {
		mmDownloadChunk.mock.t.Fatalf("ChunkDownloaderMock.DownloadChunk mock is already set by Set")
	}

	expectation := &ChunkDownloaderMockDownloadChunkExpectation{
		mock:               mmDownloadChunk.mock,
		params:             &ChunkDownloaderMockDownloadChunkParams{uploadID, chunkIndex},
		expectationOrigins: ChunkDownloaderMockDownloadChunkExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDownloadChunk.expectations = append(mmDownloadChunk.expectations, expectation)
	return expectation
}

// Then sets up ChunkDownloader.DownloadChunk return parameters for the expectation previously defined by the When method
func (e *ChunkDownloaderMockDownloadChunkExpectation) Then(cp1 *models.ChunkDownloadResponse, err error) *ChunkDownloaderMock {
	e.results = &ChunkDownloaderMockDownloadChunkResults{cp1, err}
	return e.mock
}

// Times sets number of times ChunkDownloader.DownloadChunk should be invoked
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Times(n uint64) *mChunkDownloaderMockDownloadChunk {
	if n == 0 {
		mmDownloadChunk.mock.t.Fatalf("Times of ChunkDownloaderMock.DownloadChunk mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDownloadChunk.expectedInvocations, n)
	mmDownloadChunk.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDownloadChunk
}

func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) invocationsDone() bool {
	if len(mmDownloadChunk.expectations) == 0 && mmDownloadChunk.defaultExpectation == nil && mmDownloadChunk.mock.funcDownloadChunk == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDownloadChunk.mock.afterDownloadChunkCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDownloadChunk.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DownloadChunk implements mm_uploads_by_id_chunks_v1_get.ChunkDownloader
func (mmDownloadChunk *ChunkDownloaderMock) DownloadChunk(uploadID int64, chunkIndex int64) (cp1 *models.ChunkDownloadResponse, err error) {
	mm_atomic.AddUint64(&mmDownloadChunk.beforeDownloadChunkCounter, 1)
	defer mm_atomic.AddUint64(&mmDownloadChunk.afterDownloadChunkCounter, 1)

	mmDownloadChunk.t.Helper()

	if mmDownloadChunk.inspectFuncDownloadChunk != nil {
		mmDownloadChunk.inspectFuncDownloadChunk(uploadID, chunkIndex)
	}

	mm_params := ChunkDownloaderMockDownloadChunkParams{uploadID, chunkIndex}

	// Record call args
	mmDownloadChunk.DownloadChunkMock.mutex.Lock()
	mmDownloadChunk.DownloadChunkMock.callArgs = append(mmDownloadChunk.DownloadChunkMock.callArgs, &mm_params)
	mmDownloadChunk.DownloadChunkMock.mutex.Unlock()

	for _, e := range mmDownloadChunk.DownloadChunkMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmDownloadChunk.DownloadChunkMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDownloadChunk.DownloadChunkMock.defaultExpectation.Counter, 1)
		mm_want := mmDownloadChunk.DownloadChunkMock.defaultExpectation.params
		mm_want_ptrs := mmDownloadChunk.DownloadChunkMock.defaultExpectation.paramPtrs

		mm_got := ChunkDownloaderMockDownloadChunkParams{uploadID, chunkIndex}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.uploadID != nil && !minimock.Equal(*mm_want_ptrs.uploadID, mm_got.uploadID) {
				mmDownloadChunk.t.Errorf("ChunkDownloaderMock.DownloadChunk got unexpected parameter uploadID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDownloadChunk.DownloadChunkMock.defaultExpectation.expectationOrigins.originUploadID, *mm_want_ptrs.uploadID, mm_got.uploadID, minimock.Diff(*mm_want_ptrs.uploadID, mm_got.uploadID))
			}

			if mm_want_ptrs.chunkIndex != nil && !minimock.Equal(*mm_want_ptrs.chunkIndex, mm_got.chunkIndex) {
				mmDownloadChunk.t.Errorf("ChunkDownloaderMock.DownloadChunk got unexpected parameter chunkIndex, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDownloadChunk.DownloadChunkMock.defaultExpectation.expectationOrigins.originChunkIndex, *mm_want_ptrs.chunkIndex, mm_got.chunkIndex, minimock.Diff(*mm_want_ptrs.chunkIndex, mm_got.chunkIndex))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDownloadChunk.t.Errorf("ChunkDownloaderMock.DownloadChunk got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDownloadChunk.DownloadChunkMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDownloadChunk.DownloadChunkMock.defaultExpectation.results
		if mm_results == nil {
			mmDownloadChunk.t.Fatal("No results are set for the ChunkDownloaderMock.DownloadChunk")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmDownloadChunk.funcDownloadChunk != nil {
		return mmDownloadChunk.funcDownloadChunk(uploadID, chunkIndex)
	}
	mmDownloadChunk.t.Fatalf("Unexpected call to ChunkDownloaderMock.DownloadChunk. %v %v", uploadID, chunkIndex)
	return
}

// DownloadChunkAfterCounter returns a count of finished ChunkDownloaderMock.DownloadChunk invocations
func (mmDownloadChunk *ChunkDownloaderMock) DownloadChunkAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDownloadChunk.afterDownloadChunkCounter)
}

// DownloadChunkBeforeCounter returns a count of ChunkDownloaderMock.DownloadChunk invocations
func (mmDownloadChunk *ChunkDownloaderMock) DownloadChunkBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDownloadChunk.beforeDownloadChunkCounter)
}

// Calls returns a list of arguments used in each call to ChunkDownloaderMock.DownloadChunk.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDownloadChunk *mChunkDownloaderMockDownloadChunk) Calls() []*ChunkDownloaderMockDownloadChunkParams {
	mmDownloadChunk.mutex.RLock()

	argCopy := make([]*ChunkDownloaderMockDownloadChunkParams, len(mmDownloadChunk.callArgs))
	copy(argCopy, mmDownloadChunk.callArgs)

	mmDownloadChunk.mutex.RUnlock()

	return argCopy
}

// MinimockDownloadChunkDone returns true if the count of the DownloadChunk invocations corresponds
// the number of defined expectations
func (m *ChunkDownloaderMock) MinimockDownloadChunkDone() bool {
	if m.DownloadChunkMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DownloadChunkMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DownloadChunkMock.invocationsDone()
}

// MinimockDownloadChunkInspect logs each unmet expectation
func (m *ChunkDownloaderMock) MinimockDownloadChunkInspect() {
	for _, e := range m.DownloadChunkMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ChunkDownloaderMock.DownloadChunk at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDownloadChunkCounter := mm_atomic.LoadUint64(&m.afterDownloadChunkCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DownloadChunkMock.defaultExpectation != nil && afterDownloadChunkCounter < 1 {
		if m.DownloadChunkMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ChunkDownloaderMock.DownloadChunk at\n%s", m.DownloadChunkMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ChunkDownloaderMock.DownloadChunk at\n%s with params: %#v", m.DownloadChunkMock.defaultExpectation.expectationOrigins.origin, *m.DownloadChunkMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDownloadChunk != nil && afterDownloadChunkCounter < 1 {
		m.t.Errorf("Expected call to ChunkDownloaderMock.DownloadChunk at\n%s", m.funcDownloadChunkOrigin)
	}

	if !m.DownloadChunkMock.invocationsDone() && afterDownloadChunkCounter > 0 {
		m.t.Errorf("Expected %d calls to ChunkDownloaderMock.DownloadChunk at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DownloadChunkMock.expectedInvocations), m.DownloadChunkMock.expectedInvocationsOrigin, afterDownloadChunkCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ChunkDownloaderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDownloadChunkInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ChunkDownloaderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ChunkDownloaderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDownloadChunkDone()
}
